// SPDX-FileCopyrightText: 2026 Alethia Labs OÜ <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

package verify

import (
	"context"
	"encoding/json"
	"os"
	"testing"

	tfjson "github.com/hashicorp/terraform-json"
)

// TestLiveReVerifyRealPlans exercises the remediation re-verify gate against TWO
// REAL OpenTofu plans (generated by `tofu plan` + `tofu show -json`): a "bad" plan
// that fails a control and a "fixed" plan that resolves it. Asserts the baseline
// fails and the fix is Accepted (resolved, no regression) — the deterministic gate
// the AI remediation loop relies on, proven on genuine tofu output. Gated behind
// ELENCH_PLAN_BAD / ELENCH_PLAN_FIXED env paths so it is skipped in normal CI.
func TestLiveReVerifyRealPlans(t *testing.T) {
	badPath := os.Getenv("ELENCH_PLAN_BAD")
	fixedPath := os.Getenv("ELENCH_PLAN_FIXED")
	if badPath == "" || fixedPath == "" {
		t.Skip("set ELENCH_PLAN_BAD and ELENCH_PLAN_FIXED to real plan JSON paths to run")
	}
	ctx := context.Background()
	bad := loadPlanFromPath(t, badPath)
	fixed := loadPlanFromPath(t, fixedPath)

	report, err := Evaluate(ctx, bad)
	if err != nil {
		t.Fatal(err)
	}
	if report.Verdict != StatusFail {
		t.Fatalf("baseline (bad) plan should fail, got %s", report.Verdict)
	}

	res, err := ReVerify(ctx, report, fixed)
	if err != nil {
		t.Fatal(err)
	}
	if !res.Accepted {
		t.Fatalf("fixed plan should be accepted; resolved=%v stillFailing=%v newlyFailing=%v",
			res.Resolved, res.StillFailing, res.NewlyFailing)
	}
	t.Logf("LIVE remediation: resolved=%v (candidate verdict=%s, accepted=%v)",
		res.Resolved, res.CandidateVerdict, res.Accepted)
}

func loadPlanFromPath(t *testing.T, path string) *tfjson.Plan {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var p tfjson.Plan
	if err := json.Unmarshal(b, &p); err != nil {
		t.Fatalf("unmarshal %s: %v", path, err)
	}
	return &p
}
