apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runner.fullname" . }}-config
type: Opaque
stringData:
  cluster_id: {{ .Values.config.clusterId | quote }}
  api_token: {{ .Values.config.apiToken | quote }}
