# SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
# SPDX-License-Identifier: AGPL-3.0-only
#
# Proof that the two guards added for #1753 actually REFUSE and actually PRODUCE what they claim.
#
# Both defects come from the same weekly full-bar run (30738253176), and both were invisible to
# `tofu validate`, which never evaluates a variable validation and never renders a local:
#
#   1. aws_account_id arrived EMPTY. It is interpolated into account-scoped ARNs across the whole
#      template, so the apply died hours in, at the RDS secret's KMS key, with an error that named
#      KMS and never the missing input:
#        InvalidArnException: An ARN in the specified key policy is invalid.
#      The emitted plan JSON carried "aws_account_id":{"value":""} while the credentials were fine.
#
#   2. The ECR lifecycle policy was created with EMPTY text, because create_lifecycle_policy
#      defaults to true and the document was never threaded to the upstream module:
#        InvalidParameterException: Invalid parameter at 'lifecyclePolicyText' failed to satisfy
#        constraint: 'Member must have length greater than or equal to 100'
#      Not an e2e-only bug — every tenant with provision_ecr + a native registry hit it.
#
# A guard nobody has seen fail is indistinguishable from no guard, so each is pinned from BOTH
# sides: the rejection AND the acceptance. Providers are mocked and every provisionable component
# is off, so this needs no credentials and runs on any PR.

mock_provider "aws" {
  # The mock returns a generated string for every unset attribute, which the aws provider then
  # rejects for aws_iam_policy.policy ("not a JSON object") deep inside the upstream EKS module.
  # That has nothing to do with what is under test, so every rendered policy document is stubbed
  # with valid, minimal JSON.
  mock_data "aws_iam_policy_document" {
    defaults = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[]}"
    }
  }

  # Likewise for the identity/partition data sources the upstream EKS module reads: the mock's
  # generated strings are not valid ARNs ("arn:ClhV:iam::…" fails the partition regex), and the
  # provider validates them. Real-looking values keep the plan walking.
  mock_data "aws_partition" {
    defaults = {
      partition  = "aws"
      dns_suffix = "amazonaws.com"
    }
  }
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "270587882865"
      arn        = "arn:aws:iam::270587882865:role/e2e"
      user_id    = "AROAEXAMPLE:e2e"
    }
  }
  mock_data "aws_iam_session_context" {
    defaults = {
      issuer_arn  = "arn:aws:iam::270587882865:role/e2e"
      issuer_id   = "AROAEXAMPLE"
      issuer_name = "e2e"
    }
  }

  # IAM ARNs generated by the mock flow straight into a downstream resource's policy_arn/role_arn,
  # which the provider validates as ARNs. Same reason as above: not under test, must merely parse.
  mock_resource "aws_iam_policy" {
    defaults = {
      arn = "arn:aws:iam::270587882865:policy/mock"
    }
  }
  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::270587882865:role/mock"
    }
  }

  # The mock leaves computed NESTED BLOCKS as empty lists, and the upstream module indexes into
  # them ([0]) to reach the OIDC issuer and the CA data. Populate the two it reads.
  mock_resource "aws_eks_cluster" {
    defaults = {
      arn                   = "arn:aws:eks:us-east-1:270587882865:cluster/mock"
      certificate_authority = [{ data = "bW9jaw==" }]
      identity              = [{ oidc = [{ issuer = "https://oidc.eks.us-east-1.amazonaws.com/id/MOCK" }] }]
    }
  }

  # Two more format-validated ids the provider checks before any API call.
  mock_resource "aws_launch_template" {
    defaults = {
      id = "lt-0123456789abcdef0"
    }
  }
  mock_data "aws_eks_addon_version" {
    defaults = {
      version = "v1.0.0-eksbuild.1"
    }
  }
}

# main.tf declares a SECOND aws provider (alias `virginia`, for the WAF module). mock_provider
# mocks one provider CONFIGURATION, not one provider type, so without this the aliased one still
# tries to authenticate — "No valid credential sources found" — even with every WAF flag off.
# It defines no resources here, so it needs no mocked attributes.
mock_provider "aws" {
  alias = "virginia"
}

mock_provider "random" {}

variables {
  region       = "us-east-1"
  vpc_cidr     = "10.0.0.0/16"
  environment  = "production"
  project_name = "alethia-nl"

  # The cluster and network stay at their defaults (on). Turning them off does not currently plan —
  # irsa.tf and outputs.tf index module.eks[0] unconditionally, and checks_network.tf then demands
  # an external VPC id — so a greenfield shape is the only one available to a mocked plan. Both
  # properties under test are decided from plain variables and locals regardless, so the extra
  # mocked graph costs nothing but seconds. (The provision_eks = false shape not planning is a
  # separate, pre-existing template defect; it is not what this suite is about.)
  provision_ecr = false
  create_rds    = false

  # The template declares these with no default, so a plan cannot start without them. They are
  # inert here (every corresponding component is off) and exist only to satisfy the input contract.
  sqs_queues                       = {}
  sns_topics                       = {}
  create_elasticache_redis         = false
  redis_cluster_size               = 1
  redis_cluster_mode_enabled       = false
  redis_instance_type              = "cache.t3.micro"
  redis_engine_version             = "7.1"
  redis_family                     = "redis7"
  redis_allowed_cidr_blocks        = []
  redis_allowed_security_group_ids = []
  redis_cloudwatch_logs_enabled    = false
  custom_secrets                   = []
  ddb_table_configuration          = []
  ddb_global_table_configuration   = []
  waf_logging_enabled              = false
  waf_log_retention_days           = 14
  waf_sampled_requests_enabled     = false
  waf_webacl_cloudwatch_enabled    = false
}

################################################################################
# aws_account_id — the fail-closed guard
################################################################################

# The real account id from run 30738253176, in the shape that must be ACCEPTED. Without this half
# the guard could be satisfied by refusing everything, and a regex that rejected legal ids would go
# unnoticed until it blocked a real tenant.
run "a_twelve_digit_account_id_is_accepted" {
  command = plan

  variables {
    aws_account_id = "270587882865"
  }
}

# The exact value the full-bar nightly emitted. This is the assertion that distinguishes a real
# gate from the silent interpolation it replaces: empty must BLOCK the plan, not render
# `arn:aws:iam:::root` and fail mid-apply.
run "an_empty_account_id_blocks_the_plan" {
  command = plan

  variables {
    aws_account_id = ""
  }

  expect_failures = [var.aws_account_id]
}

# Malformed, not merely empty. A truncated or mistyped id produces the same invalid ARN, so the
# guard checks the SHAPE rather than just non-emptiness — 11 digits is the nearest miss.
run "a_malformed_account_id_blocks_the_plan" {
  command = plan

  variables {
    aws_account_id = "27058788286"
  }

  expect_failures = [var.aws_account_id]
}

################################################################################
# The ECR lifecycle policy document
################################################################################

# AWS's own constraint is the assertion: >= 100 characters. Asserting merely "not empty" would have
# passed for a `{}` document and still failed at apply, which is the failure mode being fixed.
run "the_default_lifecycle_policy_satisfies_the_aws_minimum" {
  command = plan

  variables {
    aws_account_id = "270587882865"
    provision_ecr  = true
    ecr_names_map  = { app = "app-images" }
  }

  assert {
    condition     = length(module.ecr.lifecycle_policy_document) >= 100
    error_message = "The ECR lifecycle policy must be >= 100 characters — AWS rejects anything shorter, which is exactly how run 30738253176 died. Got ${length(module.ecr.lifecycle_policy_document)}."
  }

  # Both rules must survive. A document that expired untagged images but kept every tagged image
  # ever pushed would satisfy the length bound above and still let the registry grow without limit.
  assert {
    condition     = can(regex("sinceImagePushed", module.ecr.lifecycle_policy_document)) && can(regex("imageCountMoreThan", module.ecr.lifecycle_policy_document))
    error_message = "The default policy must both expire untagged images and cap the tagged image count, got ${module.ecr.lifecycle_policy_document}."
  }
}

# An operator-supplied document must WIN. Without this the variable could be silently ignored and
# every tenant would be stuck on the default — the same class of dead-input bug as the missing
# repository_lifecycle_policy that caused this issue.
run "an_explicit_lifecycle_policy_overrides_the_default" {
  command = plan

  variables {
    aws_account_id                  = "270587882865"
    provision_ecr                   = true
    ecr_names_map                   = { app = "app-images" }
    ecr_repository_lifecycle_policy = "{\"rules\":[{\"rulePriority\":1,\"description\":\"operator supplied policy, padded past the AWS 100-character minimum\",\"selection\":{\"tagStatus\":\"untagged\",\"countType\":\"sinceImagePushed\",\"countUnit\":\"days\",\"countNumber\":1},\"action\":{\"type\":\"expire\"}}]}"
  }

  assert {
    condition     = can(regex("operator supplied policy", module.ecr.lifecycle_policy_document))
    error_message = "An explicit ecr_repository_lifecycle_policy must override the default, got ${module.ecr.lifecycle_policy_document}."
  }
}

# An EMPTY string must fall back to the default rather than being passed through. "" is precisely
# what the upstream module defaults to and precisely what AWS rejects, so coalesce()-style handling
# that treats "" as a present value would reintroduce the original bug through a different door.
run "an_empty_lifecycle_policy_falls_back_to_the_default" {
  command = plan

  variables {
    aws_account_id                  = "270587882865"
    provision_ecr                   = true
    ecr_names_map                   = { app = "app-images" }
    ecr_repository_lifecycle_policy = ""
  }

  assert {
    condition     = length(module.ecr.lifecycle_policy_document) >= 100
    error_message = "An empty ecr_repository_lifecycle_policy must fall back to the default, not pass \"\" through to AWS. Got ${length(module.ecr.lifecycle_policy_document)} characters."
  }
}
