# SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
# SPDX-License-Identifier: AGPL-3.0-only
#
# Proof that `provision_eks = false` — a shape the template has ALWAYS advertised — actually plans.
#
# `variable "provision_eks"` ships with `default = true` and `module "eks"` carries
# `count = var.provision_eks ? 1 : 0`, so the option looked supported. It was not: thirteen call
# sites indexed `module.eks[0]` with no guard, and the plan died before a single resource existed
# with an error that names neither the flag nor the file that set it (#1772):
#
#   Error: Invalid index
#     module.eks is empty tuple
#     The given key does not identify an element in this collection value.
#
# Thirteen sites, measured by planning this suite against the unfixed template — eight in outputs.tf
# and five in irsa.tf — and they are two distinct defects, both pinned below:
#
#   1. UNGUARDED indexes — the eight cluster outputs. An output that ERRORS is how this stayed
#      invisible: gating the IRSA modules alone still leaves the plan dead.
#   2. WRONG-FLAG counts — the five IRSA modules, plus the modules gated on enable_karpenter /
#      provision_ecr / rds_iam_irsa / registry_pull_provider whose BODIES read module.eks[0]. Each of
#      those flags is orthogonal to the cluster, so every one was an independent door to the same
#      crash.
#
# A fourteenth site is NOT reachable from here and is worth naming so nobody deletes its guard as
# redundant: the `kubernetes`/`helm` provider blocks in main.tf. A provider config cannot take a
# `count`, and tofu prunes an unused provider config without evaluating it — so those two survived
# only because this template declares zero kubernetes_*/helm_* resources. They are guarded with
# `try()` anyway; see the note there, including why mocking those providers would hide the bug.
#
# NOT a site, though it was believed to be one while this was being fixed: `local.eso_irsa_role_name`
# in secrets-xacct.tf. `local.enable_secrets_xacct` already carries `var.provision_eks`, and OpenTofu
# SHORT-CIRCUITS a conditional whose condition is known at plan time, so the untaken branch's
# `module.eks[0]` is never evaluated. Both halves of that local are pinned below regardless.
#
# `tofu validate` cannot see any of this — it never expands a count and never renders an output —
# which is exactly why the shape shipped broken. Only a mocked PLAN reaches it.
#
# Both sides are pinned throughout: the cluster-less shape must PLAN and create nothing, the
# cluster-ful shape must still create the roles. Without the second half, deleting every IRSA module
# would pass this suite.

mock_provider "aws" {
  # The mock returns a generated string for every unset attribute, which the aws provider then
  # rejects for aws_iam_policy.policy ("not a JSON object") deep inside the upstream EKS module.
  # That has nothing to do with what is under test, so every rendered policy document is stubbed
  # with valid, minimal JSON.
  mock_data "aws_iam_policy_document" {
    defaults = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[]}"
    }
  }

  # Likewise for the identity/partition data sources the upstream EKS module reads: the mock's
  # generated strings are not valid ARNs ("arn:ClhV:iam::…" fails the partition regex), and the
  # provider validates them. Real-looking values keep the plan walking.
  mock_data "aws_partition" {
    defaults = {
      partition  = "aws"
      dns_suffix = "amazonaws.com"
    }
  }
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "270587882865"
      arn        = "arn:aws:iam::270587882865:role/e2e"
      user_id    = "AROAEXAMPLE:e2e"
    }
  }
  mock_data "aws_iam_session_context" {
    defaults = {
      issuer_arn  = "arn:aws:iam::270587882865:role/e2e"
      issuer_id   = "AROAEXAMPLE"
      issuer_name = "e2e"
    }
  }

  # IAM ARNs generated by the mock flow straight into a downstream resource's policy_arn/role_arn,
  # which the provider validates as ARNs. Same reason as above: not under test, must merely parse.
  mock_resource "aws_iam_policy" {
    defaults = {
      arn = "arn:aws:iam::270587882865:policy/mock"
    }
  }
  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::270587882865:role/mock"
    }
  }

  # The mock leaves computed NESTED BLOCKS as empty lists, and the upstream module indexes into
  # them ([0]) to reach the OIDC issuer and the CA data. Populate the two it reads.
  mock_resource "aws_eks_cluster" {
    defaults = {
      arn                   = "arn:aws:eks:us-east-1:270587882865:cluster/mock"
      certificate_authority = [{ data = "bW9jaw==" }]
      identity              = [{ oidc = [{ issuer = "https://oidc.eks.us-east-1.amazonaws.com/id/MOCK" }] }]
    }
  }

  # Two more format-validated ids the provider checks before any API call.
  mock_resource "aws_launch_template" {
    defaults = {
      id = "lt-0123456789abcdef0"
    }
  }

  # The Aurora module feeds the KMS key ARN straight into kms_key_id /
  # performance_insights_kms_key_id, both of which the provider parses as ARNs before any API call.
  # Needed only by the cluster-less-database run below; the generated string fails "invalid prefix".
  mock_resource "aws_kms_key" {
    defaults = {
      arn = "arn:aws:kms:us-east-1:270587882865:key/1a2b3c4d-5e6f-7081-92a3-b4c5d6e7f809"
    }
  }

  # Karpenter's interruption queue ARN flows into four aws_cloudwatch_event_target.arn, which the
  # provider parses as ARNs. Needed only by the cluster-ful run below.
  mock_resource "aws_sqs_queue" {
    defaults = {
      arn = "arn:aws:sqs:us-east-1:270587882865:mock-karpenter"
    }
  }
  mock_data "aws_eks_addon_version" {
    defaults = {
      version = "v1.0.0-eksbuild.1"
    }
  }
}

# main.tf declares a SECOND aws provider (alias `virginia`, for the WAF module). mock_provider
# mocks one provider CONFIGURATION, not one provider type, so without this the aliased one still
# tries to authenticate — "No valid credential sources found" — even with every WAF flag off.
# It defines no resources here, so it needs no mocked attributes.
mock_provider "aws" {
  alias = "virginia"
}

mock_provider "random" {}

variables {
  aws_account_id = "270587882865"
  region         = "us-east-1"
  vpc_cidr       = "10.0.0.0/16"
  environment    = "production"
  project_name   = "alethia-nl"

  # THE shape under test. Every run below inherits it unless it deliberately turns the cluster back
  # on to pin the other side of a guard.
  provision_eks = false

  # Everything that hangs off the cluster starts off, so each run can switch exactly one of them on
  # and attribute a failure unambiguously.
  provision_ecr          = false
  create_rds             = false
  rds_iam_irsa           = false
  rds_iam_auth_enabled   = false
  enable_karpenter       = false
  registry_pull_provider = "native"

  # The template declares these with no default, so a plan cannot start without them. They are
  # inert here (every corresponding component is off) and exist only to satisfy the input contract.
  sqs_queues                       = {}
  sns_topics                       = {}
  create_elasticache_redis         = false
  redis_cluster_size               = 1
  redis_cluster_mode_enabled       = false
  redis_instance_type              = "cache.t3.micro"
  redis_engine_version             = "7.1"
  redis_family                     = "redis7"
  redis_allowed_cidr_blocks        = []
  redis_allowed_security_group_ids = []
  redis_cloudwatch_logs_enabled    = false
  custom_secrets                   = []
  ddb_table_configuration          = []
  ddb_global_table_configuration   = []
  waf_logging_enabled              = false
  waf_log_retention_days           = 14
  waf_sampled_requests_enabled     = false
  waf_webacl_cloudwatch_enabled    = false
}

################################################################################
# 1. The bare cluster-less shape — the regression proof for #1772
################################################################################

# The run that failed before this fix. It asserts nothing beyond the counts because REACHING the
# assertions at all is the property: any surviving ungated module.eks[0] fails the plan first.
run "a_clusterless_project_plans" {
  command = plan

  assert {
    condition     = length(module.eks) == 0
    error_message = "provision_eks = false must produce no EKS module instance."
  }

  # The five IRSA roles from irsa.tf. Each federates to module.eks[0].oidc_provider_arn, so each was
  # its own copy of the crash; a role trusting an OIDC provider that does not exist would also be
  # dead weight if it were somehow created.
  assert {
    condition = alltrue([
      length(module.irsa_alethia_agent) == 0,
      length(module.irsa_fluentbit_cloudwatch) == 0,
      length(module.irsa_karpenter) == 0,
      length(module.irsa_ai_bedrock) == 0,
      length(module.s3_bucket_irsa_role) == 0,
    ])
    error_message = "No cluster means no OIDC provider to federate to — every IRSA role must drop out."
  }

  # The policies those roles consume must drop out WITH them. Gating only the role leaves an IAM
  # policy attached to nothing, which nothing later detaches — the orphan class irsa.tf's own
  # aws_iam_policy.rds_iam_auth comment records being fixed once before.
  assert {
    condition = alltrue([
      length(aws_iam_policy.irsa_alethia_agent) == 0,
      length(aws_iam_policy.irsa_karpenter) == 0,
      length(aws_iam_policy.irsa_ai_bedrock_custom) == 0,
      length(aws_iam_policy.irsa_ai_bedrock_s3) == 0,
    ])
    error_message = "An IAM policy whose only consumer dropped out is an orphan; the counts must match."
  }

  # secrets-xacct.tf's local. This half passes on the UNFIXED template too — `enable_secrets_xacct`
  # already carried `var.provision_eks` and tofu short-circuits — so it is a contract pin, not a
  # #1772 regression proof. It earns its place only together with its non-vacuous other half in
  # `a_cluster_derives_the_external_secrets_role_name` below; without that, this line would still
  # pass if the local were hard-coded to "".
  assert {
    condition     = local.eso_irsa_role_name == ""
    error_message = "With no cluster there is no external-secrets IRSA role name to derive; expected \"\"."
  }

  # The cluster outputs must resolve to null rather than exploding. The runner harvests root outputs
  # into jobs.execution_metadata, so a null is a legible "absent" and an error is a failed job.
  assert {
    condition = alltrue([
      output.eks_cluster_arn == null,
      output.eks_cluster_name == null,
      output.eks_cluster_endpoint == null,
      output.eks_irsa_external_dns_arn == null,
      output.eks_irsa_alb_controller_arn == null,
      output.eks_irsa_external_secrets_arn == null,
      output.node_iam_role_name == null,
      output.node_security_group == null,
      output.fluentbit_sa_role_arn == null,
    ])
    error_message = "Cluster outputs must be null on a cluster-less shape, not an Invalid index error."
  }
}

################################################################################
# 2. The WRONG-FLAG counts — each an independent second door to the same crash
################################################################################

# Karpenter, ECR builds, the cross-account ECR pull identity, the OCI Helm chart-repo identity and
# the cross-account Secrets Manager identity are all orthogonal to `provision_eks`, so each could be
# switched on independently while the cluster was off. Every one of them read module.eks[0] in its
# body. They are exercised together because they must ALL be silently inert, not because they
# interact — a failure here names its own file in the error.
run "clusterless_still_plans_with_every_cluster_addon_requested" {
  command = plan

  variables {
    enable_karpenter                = true
    provision_ecr                   = true
    ecr_names_map                   = { app = "app-images" }
    rds_iam_irsa                    = true
    registry_pull_provider          = "ecr-xacct"
    registry_pull_target_role_arn   = "arn:aws:iam::999999999999:role/alethia-ecr-pull"
    helm_repo_pull_target_role_arns = ["arn:aws:iam::999999999999:role/alethia-helm-pull"]
    secrets_xacct_provider          = "aws-sm-xacct"
    secrets_xacct_target_role_arn   = "arn:aws:iam::999999999999:role/alethia-secrets-read"
  }

  assert {
    condition = alltrue([
      length(module.karpenter) == 0,
      length(module.irsa_ecr_build) == 0,
      length(aws_iam_policy.irsa_ecr_build) == 0,
      length(module.rds_iam_auth) == 0,
      length(aws_iam_policy.rds_iam_auth) == 0,
      length(module.ecr_pull_xacct) == 0,
      length(aws_iam_policy.ecr_pull_xacct) == 0,
      length(module.helm_repo_pull) == 0,
      length(aws_iam_policy.helm_repo_pull) == 0,
      length(aws_iam_role_policy.secrets_xacct_assume) == 0,
    ])
    error_message = "Every cluster-scoped add-on must be inert without a cluster — and inert means absent, not a failed plan."
  }

  # ECR repositories themselves are NOT cluster-scoped: provision_ecr must still build them. Without
  # this the whole section could be satisfied by disabling ECR alongside the cluster, which would
  # break a real, useful shape (a registry-only project) to fix a crash.
  assert {
    condition     = length(module.ecr.repository_names) == 1
    error_message = "ECR repositories are independent of the cluster and must still be created; got ${length(module.ecr.repository_names)}."
  }

  # The build identity and the ServiceAccount it trusts are a PAIR. Naming an identity the kaniko
  # renderer would schedule builds under while the role is null hands it a SA that can push nothing.
  assert {
    condition     = output.ecr_build_role_arn == null && output.ecr_build_service_account == null
    error_message = "ecr_build_role_arn and ecr_build_service_account must resolve together — both null with no cluster."
  }

  # All three Karpenter outputs, with enable_karpenter = true and NO cluster. Asserting module counts
  # alone would miss karpenter_node_tags, which is read by packages/core/provisioner/karpenter.go and
  # was keyed on the raw `enable_karpenter` flag — it emitted a live tag map for an EC2NodeClass that
  # can never be rendered. A non-null here is a positive claim that Karpenter exists.
  assert {
    condition = alltrue([
      output.karpenter_queue_name == null,
      output.karpenter_sa_role == null,
      output.karpenter_node_tags == null,
    ])
    error_message = "Karpenter is requested but there is no cluster to scale — all three karpenter outputs must be null."
  }
}

# A database WITHOUT a cluster is a legitimate shape (`create_rds = true, provision_eks = false`) and
# it has its own break site: rds.tf passed `[module.eks[0].node_security_group_id]` as the RDS
# ingress security group. Separated from the run above because it plans the whole Aurora module.
run "a_database_without_a_cluster_plans" {
  command = plan

  variables {
    create_rds = true
    # db_name defaults to "" and checks_data.tf refuses that (a database with no database in it), so
    # the shape under test has to be a valid one.
    rds_config = {
      engine         = "aurora-postgresql"
      engine_version = "16.8"
      engine_mode    = "provisioned"
      cluster_family = "aurora-postgresql16"
      cluster_size   = 1
      db_port        = 5432
      db_name        = "alethia"
    }
  }

  assert {
    condition     = length(module.rds_maindb) == 1
    error_message = "create_rds must still build a database when the cluster is off."
  }

  assert {
    condition     = output.rds_cluster_endpoint != null
    error_message = "A cluster-less database must still export its endpoint."
  }
}

################################################################################
# 3. The OTHER side — with a cluster, the roles must actually be there
################################################################################

# Everything above would also pass if `module "eks"` and every IRSA role were simply deleted. This
# run is what makes the suite an invariant rather than a licence to remove the cluster.
run "a_cluster_still_creates_every_irsa_role" {
  command = plan

  variables {
    provision_eks    = true
    provision_ecr    = true
    ecr_names_map    = { app = "app-images" }
    enable_karpenter = true
  }

  assert {
    condition = alltrue([
      length(module.eks) == 1,
      length(module.irsa_alethia_agent) == 1,
      length(module.irsa_fluentbit_cloudwatch) == 1,
      length(module.irsa_karpenter) == 1,
      length(module.irsa_ai_bedrock) == 1,
      length(module.s3_bucket_irsa_role) == 1,
      length(module.irsa_ecr_build) == 1,
      length(module.karpenter) == 1,
    ])
    error_message = "With provision_eks = true every IRSA role and the Karpenter module must be created."
  }

  assert {
    condition = alltrue([
      length(aws_iam_policy.irsa_alethia_agent) == 1,
      length(aws_iam_policy.irsa_karpenter) == 1,
      length(aws_iam_policy.irsa_ai_bedrock_custom) == 1,
      length(aws_iam_policy.irsa_ai_bedrock_s3) == 1,
      length(aws_iam_policy.irsa_ecr_build) == 1,
    ])
    error_message = "The policies must be created alongside the roles that consume them."
  }

  # The pair from section 2, the other way round.
  assert {
    condition     = output.ecr_build_role_arn != null && output.ecr_build_service_account == "alethia-build:kaniko-builder"
    error_message = "With a cluster the build role and its ServiceAccount coordinates must both resolve, got ${coalesce(output.ecr_build_service_account, "null")}."
  }

  # The Karpenter outputs, the other way round. Without this half the null assertions in section 2
  # would be satisfied by an output that is null unconditionally.
  assert {
    condition = alltrue([
      output.karpenter_queue_name != null,
      output.karpenter_sa_role != null,
      output.karpenter_node_tags != null,
    ])
    error_message = "With a cluster AND enable_karpenter, all three karpenter outputs must resolve."
  }
}

# The GREENFIELD default, and the reason it needs its own run: `enable_karpenter` defaults to FALSE
# while module.irsa_karpenter counts on `provision_eks` ALONE (deliberately — gating the role on
# enable_karpenter too would change what every already-applied cluster holds). So this is the shape
# every ordinary project and every e2e floor run takes, and guarding karpenter_sa_role on the module
# alone silently flips it from null to a live IRSA role ARN here — telling any consumer that
# Karpenter is installed when nothing installed it. #1772 must not change ANY greenfield answer.
run "a_cluster_without_karpenter_reports_no_karpenter" {
  command = plan

  variables {
    provision_eks    = true
    enable_karpenter = false
  }

  assert {
    condition = alltrue([
      output.karpenter_queue_name == null,
      output.karpenter_sa_role == null,
      output.karpenter_node_tags == null,
    ])
    error_message = "enable_karpenter = false must report no Karpenter, even though the IRSA role is created with the cluster."
  }

  # And the role IS created — that is what makes the assertion above a real distinction rather than
  # a restatement of the module count.
  assert {
    condition     = length(module.irsa_karpenter) == 1 && length(module.karpenter) == 0
    error_message = "The Karpenter IRSA role rides the cluster (unchanged from before #1772); the Karpenter module rides enable_karpenter."
  }
}

# The non-vacuous half of the secrets-xacct local asserted in section 1. Together they pin that the
# ESO role name is DERIVED from the cluster's external-secrets IRSA ARN rather than being constant.
run "a_cluster_derives_the_external_secrets_role_name" {
  command = plan

  variables {
    provision_eks                 = true
    secrets_xacct_provider        = "aws-sm-xacct"
    secrets_xacct_target_role_arn = "arn:aws:iam::999999999999:role/alethia-secrets-read"
  }

  assert {
    condition     = local.eso_irsa_role_name != "" && length(aws_iam_role_policy.secrets_xacct_assume) == 1
    error_message = "With a cluster and aws-sm-xacct selected, the ESO IRSA role name must resolve and the cross-account assume policy must be created."
  }
}

################################################################################
# 4. RDS-IAM-001 — the fail-closed guard the cluster gate must not silently drop
################################################################################

# `rds_iam_irsa` without `create_rds` has nothing to scope rds-db:connect to, and irsa.tf blocks the
# apply rather than rendering `dbuser:/alethia_app` — a malformed ARN that grants nothing and reports
# a healthy apply. Adding `provision_eks` to that policy's count moved WHEN the guard is reachable,
# so it is re-pinned here: with a cluster it still BLOCKS.
#
# Note for anyone auditing this file: this run sets `provision_eks = true`, so it passes on the
# UNFIXED template too. That is by design — it re-pins #710, it is not a #1772 regression proof. It
# is the one run here that could be mistaken for evidence.
run "rds_iam_without_a_database_still_blocks_the_plan" {
  command = plan

  variables {
    provision_eks = true
    rds_iam_irsa  = true
    create_rds    = false
  }

  expect_failures = [aws_iam_policy.rds_iam_auth]
}

# And the deliberate consequence: with NO cluster the guard is not merely bypassed, the thing it
# guards does not exist. There is no policy to render, so there is nothing to fail closed about.
# Pinned so the asymmetry is a decision on record rather than a hole someone later "fixes".
run "rds_iam_without_a_cluster_creates_nothing_to_guard" {
  command = plan

  variables {
    rds_iam_irsa = true
    create_rds   = false
  }

  assert {
    condition     = length(aws_iam_policy.rds_iam_auth) == 0 && length(module.rds_iam_auth) == 0
    error_message = "With no cluster the RDS-IAM policy and role must both be absent — nothing to scope, nothing to orphan."
  }
}

# #1772 SOFTENED exactly one guard: check.keyless_rds_iam_irsa_wired gained a `!var.provision_eks ||`
# term, because the role it looks for is now cluster-gated and the check would otherwise fire on
# every cluster-less shape. Softening a guard is the cheapest way to make a stubborn plan pass, so
# the term is pinned from both sides here — otherwise the diff's most dangerous line is its only
# untested one. `check` blocks WARN rather than block, so expect_failures is the only way to observe
# one at all.
run "keyless_rds_iam_still_refuses_a_half_wired_cluster" {
  command = plan

  variables {
    provision_eks        = true
    create_rds           = true
    rds_iam_auth_enabled = true
    rds_iam_irsa         = false
    rds_config = {
      engine         = "aurora-postgresql"
      engine_version = "16.8"
      engine_mode    = "provisioned"
      cluster_family = "aurora-postgresql16"
      cluster_size   = 1
      db_port        = 5432
      db_name        = "alethia"
    }
  }

  expect_failures = [check.keyless_rds_iam_irsa_wired]
}

# The acceptance half: a fully wired cluster must NOT trip it. Without this the guard could be
# satisfied by refusing every shape, and `rds_iam_auth_enabled` would be unusable.
run "keyless_rds_iam_accepts_a_fully_wired_cluster" {
  command = plan

  variables {
    provision_eks        = true
    create_rds           = true
    rds_iam_auth_enabled = true
    rds_iam_irsa         = true
    rds_config = {
      engine         = "aurora-postgresql"
      engine_version = "16.8"
      engine_mode    = "provisioned"
      cluster_family = "aurora-postgresql16"
      cluster_size   = 1
      db_port        = 5432
      db_name        = "alethia"
    }
  }

  assert {
    condition     = length(module.rds_iam_auth) == 1 && length(aws_iam_policy.rds_iam_auth) == 1
    error_message = "A fully wired keyless RDS-IAM cluster must create both the IRSA role and its policy."
  }
}

# And the run that pins the added term ITSELF, which neither of the two above reaches — both set
# `provision_eks = true`, so both pass with or without it. A keyless database and no cluster is a
# coherent request (the app may run outside this template), and the missing IRSA role is then the
# correct answer, not a misconfiguration to warn about. Asserting no expect_failures is the
# assertion: a tripped `check` fails a `tofu test` run, so removing `!var.provision_eks ||` from
# checks_data.tf reds this file.
run "keyless_rds_iam_without_a_cluster_is_not_a_misconfiguration" {
  command = plan

  variables {
    create_rds           = true
    rds_iam_auth_enabled = true
    rds_iam_irsa         = true
    rds_config = {
      engine         = "aurora-postgresql"
      engine_version = "16.8"
      engine_mode    = "provisioned"
      cluster_family = "aurora-postgresql16"
      cluster_size   = 1
      db_port        = 5432
      db_name        = "alethia"
    }
  }

  assert {
    condition     = length(module.rds_iam_auth) == 0 && length(module.rds_maindb) == 1
    error_message = "A keyless database without a cluster must build the database and skip the IRSA role, without warning about it."
  }
}

################################################################################
# 5. The brownfield subnet gate must NOT have been weakened
################################################################################

# Making `provision_eks = false` plan is adjacent to `provision_vpc = false`, and the cheapest way to
# make a stubborn plan pass is to soften a guard that was refusing for a good reason. #1352's gate
# refuses an external VPC with no resolved private subnets, and it is pinned from BOTH sides here so
# that any such softening reds this file instead of shipping.
run "an_external_vpc_without_subnets_still_blocks_the_plan" {
  command = plan

  variables {
    provision_vpc          = false
    vpc_id                 = "vpc-0123456789abcdef0"
    vpc_private_subnet_ids = [""]
  }

  expect_failures = [
    check.external_vpc_subnets_present,
    terraform_data.brownfield_subnet_guard,
  ]
}

# The acceptance half. Without it the gate above could be satisfied by refusing every brownfield
# shape, and a template that could never adopt an existing VPC would look correct.
run "an_external_vpc_with_subnets_is_accepted" {
  command = plan

  variables {
    provision_vpc          = false
    vpc_id                 = "vpc-0123456789abcdef0"
    vpc_private_subnet_ids = ["subnet-0aaaaaaaaaaaaaaaa", "subnet-0bbbbbbbbbbbbbbbb"]
    vpc_public_subnet_ids  = ["subnet-0cccccccccccccccc", "subnet-0dddddddddddddddd"]
  }

  # The AZ outputs are deliberately null on brownfield (#1352): the user's subnets may live in AZs
  # other than region+a/b/c, so emitting the hardcoded list would LIE.
  assert {
    condition     = output.az1 == null && output.subnet1 == "subnet-0aaaaaaaaaaaaaaaa"
    error_message = "On an external VPC the AZ outputs must be null and the subnet outputs must echo the supplied ids."
  }
}
