{{- if eq .Values.secrets.provider "externalSecrets" -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "portal.fullname" . }}-externalsecret
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secrets.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.secrets.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "portal.fullname" . }}-secrets
  data:
    {{- toYaml .Values.secrets.externalSecret.data | nindent 4 }}
{{- end }}
