{{- if eq .Values.secrets.provider "kubernetes" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.fullname" . }}-secrets
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
