apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}-vertex
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: vertex
spec:
  type: {{ .Values.vertex.service.type }}
  ports:
    - port: {{ .Values.vertex.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: vertex
