apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}-vertex
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: vertex
spec:
  replicas: {{ .Values.vertex.replicaCount }}
  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: vertex
  template:
    metadata:
      labels:
        {{- include "portal.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: vertex
    spec:
      serviceAccountName: {{ include "portal.serviceAccountName" . }}
      containers:
        - name: vertex
          image: "{{ .Values.vertex.image.repository }}:{{ .Values.vertex.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.vertex.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "portal.fullname" . }}-secrets
          {{- with .Values.vertex.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.vertex.resources | nindent 12 }}
