// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * A REAL, engine-produced signed verify receipt for the homepage "prove it" hero.
 *
 * This is not hand-written marketing data. It was generated by running the actual
 * elench engine (`packages/core/verify`) over a real pass fixture and signing the
 * result — so every control id, framework mapping, verdict, and the plan hash are
 * exactly what the product emits. Regenerate with:
 *
 *   cd packages/core/verify
 *   go run ./cmd/elench-verify -json testdata/pass_keyless_least_priv.json   # the report
 *   # + verify.BuildReceipt(...) + verify.Sign(...) with a deterministic demo key
 *
 * The signature is genuine ed25519 over the receipt's canonical JSON and verifies
 * offline against the demo public key below (base64, std):
 *
 *   XKFQsHz+0dXjbT5X4xgZEySi3rTScKgD8w9XP2QEeM4=
 *
 * The demo key is NOT the production signing key — it exists only so this public
 * sample is reproducible and independently verifiable. In the product the receipt
 * is signed by the runner (see `packages/core/verify` receipt.go / signing.go).
 *
 * Types mirror the Go `verify` package and `apps/console/types/jsonb.types.ts`.
 * TODO(shared): promote these verify types to a `@repo/*` package so console +
 * marketing share one definition instead of mirroring (see CLAUDE.md shared-code rule).
 */

/** One of elench's four honest verdicts. `not_evaluable` is NEVER a silent pass. */
export type VerifyStatus = "pass" | "fail" | "warn" | "not_evaluable";

/** A concrete plan resource a control flagged. */
export interface VerifyFinding {
	address: string;
	message: string;
}

/** One control's result: what it checked, its verdict, and what it could not see. */
export interface VerifyControlResult {
	id: string;
	title: string;
	severity: "high" | "medium" | "low";
	status: VerifyStatus;
	frameworks?: string[];
	provider: string;
	findings?: VerifyFinding[];
	/** Plain-language note on what this control could NOT inspect on this plan. */
	coverage?: string;
}

/** Tally of control outcomes across the report. */
export interface VerifySummary {
	pass: number;
	fail: number;
	warn: number;
	not_evaluable: number;
}

/** The full verification report over one OpenTofu plan. */
export interface VerifyReport {
	verdict: VerifyStatus;
	catalog_version: string;
	provider: string;
	controls: VerifyControlResult[];
	summary: VerifySummary;
}

/** The per-apply evidence record (mirrors Go `verify.Receipt`). */
export interface VerifyReceiptBody {
	version: string;
	plan_sha256: string;
	tofu_version?: string;
	provider_versions?: Record<string, string>;
	catalog_version: string;
	provider: string;
	verdict: VerifyStatus;
	report: VerifyReport;
	runner?: string;
	evaluated_at?: string;
}

/** A receipt plus its detached signature (mirrors Go `verify.SignedReceipt`). */
export interface SignedReceipt {
	receipt: VerifyReceiptBody;
	algorithm: string;
	key_id?: string;
	signature?: string;
}

/** The engine-produced, signed sample rendered by the homepage receipt hero. */
export const SAMPLE_RECEIPT: SignedReceipt = {
	receipt: {
		version: "elench-receipt-1",
		plan_sha256:
			"48edfe75823ff86d431603b1d5ff67495ffa225d2fc11b174772cd9bb4b80660",
		tofu_version: "1.8.3",
		provider_versions: {
			"registry.opentofu.org/hashicorp/aws": "5.62.0",
		},
		catalog_version: "elench-controls-0.4.0",
		provider: "aws",
		verdict: "pass",
		report: {
			verdict: "pass",
			catalog_version: "elench-controls-0.4.0",
			provider: "aws",
			controls: [
				{
					id: "KEYLESS-001",
					title: "No static IAM access keys",
					severity: "high",
					status: "pass",
					frameworks: ["CIS-AWS-1.4", "SOC2-CC6.1"],
					provider: "aws",
				},
				{
					id: "OIDC-001",
					title: "Federated trust is bound to a specific subject",
					severity: "high",
					status: "pass",
					frameworks: ["SOC2-CC6.1"],
					provider: "aws",
				},
				{
					id: "LEASTPRIV-001",
					title: "No over-broad IAM grants (named patterns)",
					severity: "high",
					status: "pass",
					frameworks: ["CIS-AWS-1.16", "SOC2-CC6.3"],
					provider: "aws",
				},
			],
			summary: { pass: 3, fail: 0, warn: 0, not_evaluable: 0 },
		},
		runner: "alethia-runner/demo",
		evaluated_at: "2026-07-18T09:14:22Z",
	},
	algorithm: "ed25519",
	key_id: "be93304c0cf79abd",
	signature:
		"d8couw2a4ohFsS+yA6/hLDljSO9vaWJVPwfXCj2LSJgsdMGbaPuT0UsSBjG/iNp3MKKuKcnfjNPc9N+GZhSmAQ==",
};
