/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./../../types/database.types";

export const publicCloudProviderSchema = z.union([
  z.literal("aws"),
  z.literal("azure"),
  z.literal("gcp"),
]);

export const publicClusterStatusSchema = z.union([
  z.literal("PENDING"),
  z.literal("ONLINE"),
  z.literal("OFFLINE"),
]);

export const publicDeploymentResourceStatusSchema = z.union([
  z.literal("creating"),
  z.literal("created"),
  z.literal("updating"),
  z.literal("deleting"),
  z.literal("deleted"),
  z.literal("failed"),
]);

export const publicDeploymentStatusSchema = z.union([
  z.literal("pending"),
  z.literal("initializing"),
  z.literal("planning"),
  z.literal("applying"),
  z.literal("completed"),
  z.literal("failed"),
  z.literal("cancelled"),
  z.literal("destroying"),
]);

export const publicGitProviderSchema = z.union([
  z.literal("github"),
  z.literal("bitbucket"),
  z.literal("gitlab"),
]);

export const publicIacToolSchema = z.union([
  z.literal("pulumi"),
  z.literal("terraform"),
]);

export const publicIntegrationAuthMethodSchema = z.union([
  z.literal("oauth"),
  z.literal("iam_role"),
  z.literal("service_account"),
  z.literal("service_principal"),
  z.literal("ram_role"),
]);

export const publicIntegrationCategorySchema = z.union([
  z.literal("git"),
  z.literal("cloud"),
]);

export const publicIntegrationStatusSchema = z.union([
  z.literal("active"),
  z.literal("coming_soon"),
]);

export const publicLogsLevelSchema = z.union([
  z.literal("debug"),
  z.literal("info"),
  z.literal("warn"),
  z.literal("error"),
  z.literal("critical"),
]);

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicBootstrapJobsRowSchema = z.object({
  completed_at: z.string().nullable(),
  created_at: z.string().nullable(),
  error_message: z.string().nullable(),
  id: z.string(),
  status: z.string(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
  vineyard_id: z.string(),
});

export const publicBootstrapJobsInsertSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  id: z.string().optional(),
  status: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
  vineyard_id: z.string(),
});

export const publicBootstrapJobsUpdateSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  id: z.string().optional(),
  status: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
  vineyard_id: z.string().optional(),
});

export const publicBootstrapJobsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("bootstrap_jobs_vineyard_id_fkey"),
    columns: z.tuple([z.literal("vineyard_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vineyards"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicBootstrapLogsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.number(),
  job_id: z.string(),
  log_chunk: z.string(),
  stream_type: z.string(),
});

export const publicBootstrapLogsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  job_id: z.string(),
  log_chunk: z.string(),
  stream_type: z.string().optional(),
});

export const publicBootstrapLogsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  job_id: z.string().optional(),
  log_chunk: z.string().optional(),
  stream_type: z.string().optional(),
});

export const publicBootstrapLogsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("bootstrap_logs_job_id_fkey"),
    columns: z.tuple([z.literal("job_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("bootstrap_jobs"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCliLoginsRowSchema = z.object({
  created_at: z.string().nullable(),
  device_code: z.string(),
  expires_at: z.string().nullable(),
  profile_id: z.string().nullable(),
  refresh_token: z.string().nullable(),
  verification_code: z.string().nullable(),
});

export const publicCliLoginsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  device_code: z.string(),
  expires_at: z.string().optional().nullable(),
  profile_id: z.string().optional().nullable(),
  refresh_token: z.string().optional().nullable(),
  verification_code: z.string().optional().nullable(),
});

export const publicCliLoginsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  device_code: z.string().optional(),
  expires_at: z.string().optional().nullable(),
  profile_id: z.string().optional().nullable(),
  refresh_token: z.string().optional().nullable(),
  verification_code: z.string().optional().nullable(),
});

export const publicCliLoginsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("cli_logins_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCloudIdentitiesRowSchema = z.object({
  created_at: z.string().nullable(),
  credentials: z.object({
    role_arn: z.string().optional().nullable(),
    external_id: z.string().optional().nullable(),
    account_id: z.string().optional().nullable(),
  }),
  id: z.string(),
  is_verified: z.boolean().nullable(),
  name: z.string(),
  provider: publicCloudProviderSchema,
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicCloudIdentitiesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  credentials: z
    .object({
      role_arn: z.string().optional().nullable(),
      external_id: z.string().optional().nullable(),
      account_id: z.string().optional().nullable(),
    })
    .optional(),
  id: z.string().optional(),
  is_verified: z.boolean().optional().nullable(),
  name: z.string().optional(),
  provider: publicCloudProviderSchema,
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicCloudIdentitiesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  credentials: z
    .object({
      role_arn: z.string().optional().nullable(),
      external_id: z.string().optional().nullable(),
      account_id: z.string().optional().nullable(),
    })
    .optional(),
  id: z.string().optional(),
  is_verified: z.boolean().optional().nullable(),
  name: z.string().optional(),
  provider: publicCloudProviderSchema.optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicClustersRowSchema = z.object({
  agent_token_hash: z.string().nullable(),
  created_at: z.string().nullable(),
  id: z.string(),
  last_heartbeat: z.string().nullable(),
  metadata: z
    .record(z.string(), z.any())
    .and(
      z.object({
        region: z.string().optional().nullable(),
        vpc_cidr: z.string().optional().nullable(),
      }),
    )
    .nullable(),
  name: z.string(),
  status: publicClusterStatusSchema.nullable(),
  user_id: z.string(),
});

export const publicClustersInsertSchema = z.object({
  agent_token_hash: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  last_heartbeat: z.string().optional().nullable(),
  metadata: z
    .record(z.string(), z.any())
    .and(
      z.object({
        region: z.string().optional().nullable(),
        vpc_cidr: z.string().optional().nullable(),
      }),
    )
    .optional()
    .nullable(),
  name: z.string(),
  status: publicClusterStatusSchema.optional().nullable(),
  user_id: z.string(),
});

export const publicClustersUpdateSchema = z.object({
  agent_token_hash: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  last_heartbeat: z.string().optional().nullable(),
  metadata: z
    .record(z.string(), z.any())
    .and(
      z.object({
        region: z.string().optional().nullable(),
        vpc_cidr: z.string().optional().nullable(),
      }),
    )
    .optional()
    .nullable(),
  name: z.string().optional(),
  status: publicClusterStatusSchema.optional().nullable(),
  user_id: z.string().optional(),
});

export const publicConfigurationsRowSchema = z.object({
  applications_destination_repo: z.string().nullable(),
  applications_template_repo: z.string().nullable(),
  aws_account_id: z.string().nullable(),
  aws_region: z.string().nullable(),
  cloud_identity_id: z.string().nullable(),
  cluster_id: z.string().nullable(),
  container_platform: z.string(),
  create_rds: z.boolean().nullable(),
  create_vpc: z.boolean().nullable(),
  created_at: z.string().nullable(),
  db_max_capacity: z.number().nullable(),
  db_min_capacity: z.number().nullable(),
  description: z.string().nullable(),
  dns_domain_name: z.string().nullable(),
  dns_hosted_zone: z.string().nullable(),
  download_count: z.number().nullable(),
  eks_cluster_admins: z.string().nullable(),
  enable_cloudfront_waf: z.boolean().nullable(),
  enable_dns: z.boolean().nullable(),
  enable_gitops_destination: z.boolean().nullable(),
  enable_karpenter: z.boolean().nullable(),
  enable_redis: z.boolean().nullable(),
  env_git_repo: z.string().nullable(),
  environment_repository: z.string().nullable(),
  environment_stage: z.string(),
  full_config: jsonSchema.nullable(),
  gitops_app_template: z.string().nullable(),
  gitops_app_token: z.string().nullable(),
  gitops_argocd_token: z.string().nullable(),
  gitops_destination_repo: z.string().nullable(),
  gitops_destinations_repo: z.string().nullable(),
  gitops_infra_destination_repo: z.string().nullable(),
  gitops_repository: z.string().nullable(),
  id: z.string(),
  last_downloaded_at: z.string().nullable(),
  project_name: z.string(),
  redis_allowed_cidr_blocks: z.string().nullable(),
  ses_queues_topics: z.string().nullable(),
  status: z.string().nullable(),
  terraform_version: z.string(),
  ui_position_x: z.number().nullable(),
  ui_position_y: z.number().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
  vineyard_id: z.string().nullable(),
  vpc_cidr: z.string().nullable(),
});

export const publicConfigurationsInsertSchema = z.object({
  applications_destination_repo: z.string().optional().nullable(),
  applications_template_repo: z.string().optional().nullable(),
  aws_account_id: z.string().optional().nullable(),
  aws_region: z.string().optional().nullable(),
  cloud_identity_id: z.string().optional().nullable(),
  cluster_id: z.string().optional().nullable(),
  container_platform: z.string(),
  create_rds: z.boolean().optional().nullable(),
  create_vpc: z.boolean().optional().nullable(),
  created_at: z.string().optional().nullable(),
  db_max_capacity: z.number().optional().nullable(),
  db_min_capacity: z.number().optional().nullable(),
  description: z.string().optional().nullable(),
  dns_domain_name: z.string().optional().nullable(),
  dns_hosted_zone: z.string().optional().nullable(),
  download_count: z.number().optional().nullable(),
  eks_cluster_admins: z.string().optional().nullable(),
  enable_cloudfront_waf: z.boolean().optional().nullable(),
  enable_dns: z.boolean().optional().nullable(),
  enable_gitops_destination: z.boolean().optional().nullable(),
  enable_karpenter: z.boolean().optional().nullable(),
  enable_redis: z.boolean().optional().nullable(),
  env_git_repo: z.string().optional().nullable(),
  environment_repository: z.string().optional().nullable(),
  environment_stage: z.string(),
  full_config: jsonSchema.optional().nullable(),
  gitops_app_template: z.string().optional().nullable(),
  gitops_app_token: z.string().optional().nullable(),
  gitops_argocd_token: z.string().optional().nullable(),
  gitops_destination_repo: z.string().optional().nullable(),
  gitops_destinations_repo: z.string().optional().nullable(),
  gitops_infra_destination_repo: z.string().optional().nullable(),
  gitops_repository: z.string().optional().nullable(),
  id: z.string().optional(),
  last_downloaded_at: z.string().optional().nullable(),
  project_name: z.string(),
  redis_allowed_cidr_blocks: z.string().optional().nullable(),
  ses_queues_topics: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  terraform_version: z.string(),
  ui_position_x: z.number().optional().nullable(),
  ui_position_y: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
  vineyard_id: z.string().optional().nullable(),
  vpc_cidr: z.string().optional().nullable(),
});

export const publicConfigurationsUpdateSchema = z.object({
  applications_destination_repo: z.string().optional().nullable(),
  applications_template_repo: z.string().optional().nullable(),
  aws_account_id: z.string().optional().nullable(),
  aws_region: z.string().optional().nullable(),
  cloud_identity_id: z.string().optional().nullable(),
  cluster_id: z.string().optional().nullable(),
  container_platform: z.string().optional(),
  create_rds: z.boolean().optional().nullable(),
  create_vpc: z.boolean().optional().nullable(),
  created_at: z.string().optional().nullable(),
  db_max_capacity: z.number().optional().nullable(),
  db_min_capacity: z.number().optional().nullable(),
  description: z.string().optional().nullable(),
  dns_domain_name: z.string().optional().nullable(),
  dns_hosted_zone: z.string().optional().nullable(),
  download_count: z.number().optional().nullable(),
  eks_cluster_admins: z.string().optional().nullable(),
  enable_cloudfront_waf: z.boolean().optional().nullable(),
  enable_dns: z.boolean().optional().nullable(),
  enable_gitops_destination: z.boolean().optional().nullable(),
  enable_karpenter: z.boolean().optional().nullable(),
  enable_redis: z.boolean().optional().nullable(),
  env_git_repo: z.string().optional().nullable(),
  environment_repository: z.string().optional().nullable(),
  environment_stage: z.string().optional(),
  full_config: jsonSchema.optional().nullable(),
  gitops_app_template: z.string().optional().nullable(),
  gitops_app_token: z.string().optional().nullable(),
  gitops_argocd_token: z.string().optional().nullable(),
  gitops_destination_repo: z.string().optional().nullable(),
  gitops_destinations_repo: z.string().optional().nullable(),
  gitops_infra_destination_repo: z.string().optional().nullable(),
  gitops_repository: z.string().optional().nullable(),
  id: z.string().optional(),
  last_downloaded_at: z.string().optional().nullable(),
  project_name: z.string().optional(),
  redis_allowed_cidr_blocks: z.string().optional().nullable(),
  ses_queues_topics: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  terraform_version: z.string().optional(),
  ui_position_x: z.number().optional().nullable(),
  ui_position_y: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
  vineyard_id: z.string().optional().nullable(),
  vpc_cidr: z.string().optional().nullable(),
});

export const publicConfigurationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("configurations_cloud_identity_id_fkey"),
    columns: z.tuple([z.literal("cloud_identity_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("cloud_identities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("configurations_cluster_id_fkey"),
    columns: z.tuple([z.literal("cluster_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("clusters"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("configurations_vineyard_id_fkey"),
    columns: z.tuple([z.literal("vineyard_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vineyards"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDeploymentLogsRowSchema = z.object({
  created_at: z.string().nullable(),
  deployment_id: z.string(),
  id: z.string(),
  level: publicLogsLevelSchema,
  message: z.string(),
  step: z.string().nullable(),
});

export const publicDeploymentLogsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  deployment_id: z.string(),
  id: z.string().optional(),
  level: publicLogsLevelSchema,
  message: z.string(),
  step: z.string().optional().nullable(),
});

export const publicDeploymentLogsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  deployment_id: z.string().optional(),
  id: z.string().optional(),
  level: publicLogsLevelSchema.optional(),
  message: z.string().optional(),
  step: z.string().optional().nullable(),
});

export const publicDeploymentLogsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("deployment_logs_deployment_id_fkey"),
    columns: z.tuple([z.literal("deployment_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("deployments"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDeploymentResourcesRowSchema = z.object({
  aws_arn: z.string().nullable(),
  created_at: z.string().nullable(),
  deployment_id: z.string(),
  id: z.string(),
  properties: jsonSchema.nullable(),
  resource_id: z.string().nullable(),
  resource_name: z.string(),
  resource_type: z.string(),
  status: publicDeploymentResourceStatusSchema,
  updated_at: z.string().nullable(),
});

export const publicDeploymentResourcesInsertSchema = z.object({
  aws_arn: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  deployment_id: z.string(),
  id: z.string().optional(),
  properties: jsonSchema.optional().nullable(),
  resource_id: z.string().optional().nullable(),
  resource_name: z.string(),
  resource_type: z.string(),
  status: publicDeploymentResourceStatusSchema.optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicDeploymentResourcesUpdateSchema = z.object({
  aws_arn: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  deployment_id: z.string().optional(),
  id: z.string().optional(),
  properties: jsonSchema.optional().nullable(),
  resource_id: z.string().optional().nullable(),
  resource_name: z.string().optional(),
  resource_type: z.string().optional(),
  status: publicDeploymentResourceStatusSchema.optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicDeploymentResourcesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("deployment_resources_deployment_id_fkey"),
    columns: z.tuple([z.literal("deployment_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("deployments"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDeploymentsRowSchema = z.object({
  aws_region: z.string().nullable(),
  completed_at: z.string().nullable(),
  completed_steps: z.number().nullable(),
  configuration_id: z.string().nullable(),
  created_at: z.string().nullable(),
  current_step: z.string().nullable(),
  description: z.string().nullable(),
  duration_seconds: z.number().nullable(),
  error_message: z.string().nullable(),
  iac_tool: publicIacToolSchema,
  id: z.string(),
  lock_id: z.string().nullable(),
  logs: z.string().nullable(),
  name: z.string(),
  outputs: jsonSchema.nullable(),
  profile_id: z.string(),
  progress_percentage: z.number().nullable(),
  pulumi_version: z.string().nullable(),
  started_at: z.string().nullable(),
  state_bucket: z.string().nullable(),
  state_key: z.string().nullable(),
  status: publicDeploymentStatusSchema,
  terraform_version: z.string().nullable(),
  total_steps: z.number().nullable(),
  updated_at: z.string().nullable(),
});

export const publicDeploymentsInsertSchema = z.object({
  aws_region: z.string().optional().nullable(),
  completed_at: z.string().optional().nullable(),
  completed_steps: z.number().optional().nullable(),
  configuration_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  current_step: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  duration_seconds: z.number().optional().nullable(),
  error_message: z.string().optional().nullable(),
  iac_tool: publicIacToolSchema,
  id: z.string().optional(),
  lock_id: z.string().optional().nullable(),
  logs: z.string().optional().nullable(),
  name: z.string(),
  outputs: jsonSchema.optional().nullable(),
  profile_id: z.string(),
  progress_percentage: z.number().optional().nullable(),
  pulumi_version: z.string().optional().nullable(),
  started_at: z.string().optional().nullable(),
  state_bucket: z.string().optional().nullable(),
  state_key: z.string().optional().nullable(),
  status: publicDeploymentStatusSchema.optional(),
  terraform_version: z.string().optional().nullable(),
  total_steps: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicDeploymentsUpdateSchema = z.object({
  aws_region: z.string().optional().nullable(),
  completed_at: z.string().optional().nullable(),
  completed_steps: z.number().optional().nullable(),
  configuration_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  current_step: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  duration_seconds: z.number().optional().nullable(),
  error_message: z.string().optional().nullable(),
  iac_tool: publicIacToolSchema.optional(),
  id: z.string().optional(),
  lock_id: z.string().optional().nullable(),
  logs: z.string().optional().nullable(),
  name: z.string().optional(),
  outputs: jsonSchema.optional().nullable(),
  profile_id: z.string().optional(),
  progress_percentage: z.number().optional().nullable(),
  pulumi_version: z.string().optional().nullable(),
  started_at: z.string().optional().nullable(),
  state_bucket: z.string().optional().nullable(),
  state_key: z.string().optional().nullable(),
  status: publicDeploymentStatusSchema.optional(),
  terraform_version: z.string().optional().nullable(),
  total_steps: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicDeploymentsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("deployments_configuration_id_fkey"),
    columns: z.tuple([z.literal("configuration_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("configurations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("deployments_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicHarvestsRowSchema = z.object({
  completed_at: z.string().nullable(),
  configuration_id: z.string(),
  created_at: z.string().nullable(),
  error_message: z.string().nullable(),
  id: z.string(),
  logs: z.string().nullable(),
  status: z.string(),
  ui_position_x: z.number().nullable(),
  ui_position_y: z.number().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicHarvestsInsertSchema = z.object({
  completed_at: z.string().optional().nullable(),
  configuration_id: z.string(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  id: z.string().optional(),
  logs: z.string().optional().nullable(),
  status: z.string().optional(),
  ui_position_x: z.number().optional().nullable(),
  ui_position_y: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const publicHarvestsUpdateSchema = z.object({
  completed_at: z.string().optional().nullable(),
  configuration_id: z.string().optional(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  id: z.string().optional(),
  logs: z.string().optional().nullable(),
  status: z.string().optional(),
  ui_position_x: z.number().optional().nullable(),
  ui_position_y: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicHarvestsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("harvests_configuration_id_fkey"),
    columns: z.tuple([z.literal("configuration_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("configurations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicIntegrationsRowSchema = z.object({
  auth_method: publicIntegrationAuthMethodSchema,
  category: publicIntegrationCategorySchema,
  created_at: z.string().nullable(),
  description: z.string(),
  docs_url: z.string().nullable(),
  icon_url: z.string(),
  id: z.string(),
  name: z.string(),
  organization: z.string(),
  privacy_url: z.string().nullable(),
  slug: z.string(),
  sort_order: z.number(),
  status: publicIntegrationStatusSchema,
  support_url: z.string().nullable(),
  updated_at: z.string().nullable(),
});

export const publicIntegrationsInsertSchema = z.object({
  auth_method: publicIntegrationAuthMethodSchema,
  category: publicIntegrationCategorySchema,
  created_at: z.string().optional().nullable(),
  description: z.string(),
  docs_url: z.string().optional().nullable(),
  icon_url: z.string(),
  id: z.string().optional(),
  name: z.string(),
  organization: z.string(),
  privacy_url: z.string().optional().nullable(),
  slug: z.string(),
  sort_order: z.number().optional(),
  status: publicIntegrationStatusSchema.optional(),
  support_url: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicIntegrationsUpdateSchema = z.object({
  auth_method: publicIntegrationAuthMethodSchema.optional(),
  category: publicIntegrationCategorySchema.optional(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional(),
  docs_url: z.string().optional().nullable(),
  icon_url: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  organization: z.string().optional(),
  privacy_url: z.string().optional().nullable(),
  slug: z.string().optional(),
  sort_order: z.number().optional(),
  status: publicIntegrationStatusSchema.optional(),
  support_url: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicJobLogsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.number(),
  job_id: z.string(),
  log_chunk: z.string(),
  stream_type: z.string().nullable(),
});

export const publicJobLogsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  job_id: z.string(),
  log_chunk: z.string(),
  stream_type: z.string().optional().nullable(),
});

export const publicJobLogsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  job_id: z.string().optional(),
  log_chunk: z.string().optional(),
  stream_type: z.string().optional().nullable(),
});

export const publicJobLogsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("job_logs_job_id_fkey"),
    columns: z.tuple([z.literal("job_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("provision_jobs"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProfilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  created_at: z.string(),
  email: z.string().nullable(),
  full_name: z.string().nullable(),
  id: z.string(),
});

export const publicProfilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
});

export const publicProfilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
});

export const publicProviderTokensRowSchema = z.object({
  access_token: z.string(),
  created_at: z.string().nullable(),
  expires_at: z.string().nullable(),
  id: z.string(),
  provider: publicGitProviderSchema,
  refresh_token: z.string().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicProviderTokensInsertSchema = z.object({
  access_token: z.string(),
  created_at: z.string().optional().nullable(),
  expires_at: z.string().optional().nullable(),
  id: z.string().optional(),
  provider: publicGitProviderSchema,
  refresh_token: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicProviderTokensUpdateSchema = z.object({
  access_token: z.string().optional(),
  created_at: z.string().optional().nullable(),
  expires_at: z.string().optional().nullable(),
  id: z.string().optional(),
  provider: publicGitProviderSchema.optional(),
  refresh_token: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicProvisionJobsRowSchema = z.object({
  claimed_at: z.string().nullable(),
  cloud_identity_id: z.string().nullable(),
  cluster_id: z.string().nullable(),
  completed_at: z.string().nullable(),
  config_snapshot: jsonSchema,
  configuration_hash: z.string().nullable(),
  configuration_id: z.string().nullable(),
  created_at: z.string().nullable(),
  error_message: z.string().nullable(),
  execution_metadata: jsonSchema.nullable(),
  id: z.string(),
  job_type: z.string(),
  started_at: z.string().nullable(),
  status: z.string(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
  vineyard_id: z.string(),
  worker_id: z.string().nullable(),
});

export const publicProvisionJobsInsertSchema = z.object({
  claimed_at: z.string().optional().nullable(),
  cloud_identity_id: z.string().optional().nullable(),
  cluster_id: z.string().optional().nullable(),
  completed_at: z.string().optional().nullable(),
  config_snapshot: jsonSchema.optional(),
  configuration_hash: z.string().optional().nullable(),
  configuration_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  execution_metadata: jsonSchema.optional().nullable(),
  id: z.string().optional(),
  job_type: z.string(),
  started_at: z.string().optional().nullable(),
  status: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
  vineyard_id: z.string(),
  worker_id: z.string().optional().nullable(),
});

export const publicProvisionJobsUpdateSchema = z.object({
  claimed_at: z.string().optional().nullable(),
  cloud_identity_id: z.string().optional().nullable(),
  cluster_id: z.string().optional().nullable(),
  completed_at: z.string().optional().nullable(),
  config_snapshot: jsonSchema.optional(),
  configuration_hash: z.string().optional().nullable(),
  configuration_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  execution_metadata: jsonSchema.optional().nullable(),
  id: z.string().optional(),
  job_type: z.string().optional(),
  started_at: z.string().optional().nullable(),
  status: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
  vineyard_id: z.string().optional(),
  worker_id: z.string().optional().nullable(),
});

export const publicProvisionJobsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("provision_jobs_cloud_identity_id_fkey"),
    columns: z.tuple([z.literal("cloud_identity_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("cloud_identities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("provision_jobs_cluster_id_fkey"),
    columns: z.tuple([z.literal("cluster_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("clusters"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("provision_jobs_configuration_id_fkey"),
    columns: z.tuple([z.literal("configuration_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("configurations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("provision_jobs_vineyard_id_fkey"),
    columns: z.tuple([z.literal("vineyard_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vineyards"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProvisionLogsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.number(),
  log_chunk: z.string(),
  provision_id: z.string(),
  stream_type: z.string().nullable(),
});

export const publicProvisionLogsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  log_chunk: z.string(),
  provision_id: z.string(),
  stream_type: z.string().optional().nullable(),
});

export const publicProvisionLogsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  log_chunk: z.string().optional(),
  provision_id: z.string().optional(),
  stream_type: z.string().optional().nullable(),
});

export const publicProvisionLogsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("provision_logs_provision_id_fkey"),
    columns: z.tuple([z.literal("provision_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("provisions"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProvisionsRowSchema = z.object({
  cluster_id: z.string(),
  completed_at: z.string().nullable(),
  config_snapshot: jsonSchema,
  configuration_hash: z.string().nullable(),
  created_at: z.string().nullable(),
  error_message: z.string().nullable(),
  execution_metadata: jsonSchema.nullable(),
  id: z.string(),
  started_at: z.string().nullable(),
  status: z.string().nullable(),
});

export const publicProvisionsInsertSchema = z.object({
  cluster_id: z.string(),
  completed_at: z.string().optional().nullable(),
  config_snapshot: jsonSchema,
  configuration_hash: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  execution_metadata: jsonSchema.optional().nullable(),
  id: z.string().optional(),
  started_at: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
});

export const publicProvisionsUpdateSchema = z.object({
  cluster_id: z.string().optional(),
  completed_at: z.string().optional().nullable(),
  config_snapshot: jsonSchema.optional(),
  configuration_hash: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  execution_metadata: jsonSchema.optional().nullable(),
  id: z.string().optional(),
  started_at: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
});

export const publicProvisionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("provisions_cluster_id_fkey"),
    columns: z.tuple([z.literal("cluster_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("clusters"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineyardsRowSchema = z.object({
  created_at: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicVineyardsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const publicVineyardsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicWorkersRowSchema = z.object({
  cloud_identity_id: z.string().nullable(),
  created_at: z.string().nullable(),
  id: z.string(),
  last_heartbeat: z.string().nullable(),
  metadata: jsonSchema.nullable(),
  mode: z.string(),
  name: z.string(),
  status: z.string().nullable(),
  token_hash: z.string(),
  user_id: z.string(),
});

export const publicWorkersInsertSchema = z.object({
  cloud_identity_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  last_heartbeat: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  mode: z.string(),
  name: z.string(),
  status: z.string().optional().nullable(),
  token_hash: z.string(),
  user_id: z.string().optional(),
});

export const publicWorkersUpdateSchema = z.object({
  cloud_identity_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  last_heartbeat: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  mode: z.string().optional(),
  name: z.string().optional(),
  status: z.string().optional().nullable(),
  token_hash: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicWorkersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("workers_cloud_identity_id_fkey"),
    columns: z.tuple([z.literal("cloud_identity_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("cloud_identities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicAgentHeartbeatArgsSchema = z.object({
  p_cluster_id: z.string(),
  p_token_hash: z.string(),
});

export const publicAgentHeartbeatReturnsSchema = z.undefined();

export const publicClaimNextJobArgsSchema = z.object({
  p_cloud_identity_id: z.string().optional(),
  p_worker_id: z.string(),
  p_worker_token_hash: z.string(),
});

export const publicClaimNextJobReturnsSchema = z.array(
  z.object({
    claimed_at: z.string().nullable(),
    cloud_identity_id: z.string().nullable(),
    cluster_id: z.string().nullable(),
    completed_at: z.string().nullable(),
    config_snapshot: jsonSchema,
    configuration_hash: z.string().nullable(),
    configuration_id: z.string().nullable(),
    created_at: z.string().nullable(),
    error_message: z.string().nullable(),
    execution_metadata: jsonSchema.nullable(),
    id: z.string(),
    job_type: z.string(),
    started_at: z.string().nullable(),
    status: z.string(),
    updated_at: z.string().nullable(),
    user_id: z.string(),
    vineyard_id: z.string(),
    worker_id: z.string().nullable(),
  }),
);

export const publicFetchNextProvisionArgsSchema = z.object({
  p_cluster_id: z.string(),
  p_token_hash: z.string(),
});

export const publicFetchNextProvisionReturnsSchema = z.array(
  z.object({
    cluster_id: z.string(),
    completed_at: z.string().nullable(),
    config_snapshot: jsonSchema,
    configuration_hash: z.string().nullable(),
    created_at: z.string().nullable(),
    error_message: z.string().nullable(),
    execution_metadata: jsonSchema.nullable(),
    id: z.string(),
    started_at: z.string().nullable(),
    status: z.string().nullable(),
  }),
);

export const publicGetConfigurationStatsArgsSchema = z.never();

export const publicGetConfigurationStatsReturnsSchema = z.array(
  z.object({
    archived_configs: z.number(),
    completed_configs: z.number(),
    draft_configs: z.number(),
    ecs_configs: z.number(),
    eks_configs: z.number(),
    failed_configs: z.number(),
    has_rds_configs: z.number(),
    has_vpc_configs: z.number(),
    pending_configs: z.number(),
    recent_configs: z.number(),
    this_month_configs: z.number(),
    total_configs: z.number(),
  }),
);

export const publicInsertJobLogArgsSchema = z.object({
  p_job_id: z.string(),
  p_log_chunk: z.string(),
  p_stream_type: z.string().optional(),
  p_worker_id: z.string(),
  p_worker_token_hash: z.string(),
});

export const publicInsertJobLogReturnsSchema = z.undefined();

export const publicInsertProvisionLogArgsSchema = z.object({
  p_cluster_id: z.string(),
  p_log_chunk: z.string(),
  p_provision_id: z.string(),
  p_stream_type: z.string(),
  p_token_hash: z.string(),
});

export const publicInsertProvisionLogReturnsSchema = z.undefined();

export const publicRecoverStaleJobsArgsSchema = z.never();

export const publicRecoverStaleJobsReturnsSchema = z.number();

export const publicUpdateJobStatusArgsSchema = z.object({
  p_error_message: z.string().optional(),
  p_execution_metadata: jsonSchema.optional(),
  p_job_id: z.string(),
  p_status: z.string(),
  p_worker_id: z.string(),
  p_worker_token_hash: z.string(),
});

export const publicUpdateJobStatusReturnsSchema = z.undefined();

export const publicUpdateProvisionStatusArgsSchema = z.object({
  p_cluster_id: z.string(),
  p_error_message: z.string().optional(),
  p_provision_id: z.string(),
  p_status: z.string(),
  p_token_hash: z.string(),
});

export const publicUpdateProvisionStatusReturnsSchema = z.undefined();

export const publicWorkerHeartbeatArgsSchema = z.object({
  p_worker_id: z.string(),
  p_worker_token_hash: z.string(),
});

export const publicWorkerHeartbeatReturnsSchema = z.undefined();
