/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./../../types/database.types";

export const publicAuditActionSchema = z.union([
  z.literal("CREATED"),
  z.literal("UPDATED"),
  z.literal("DELETED"),
  z.literal("PROVISIONED"),
  z.literal("DESTROYED"),
  z.literal("COMPONENT_ADDED"),
  z.literal("COMPONENT_UPDATED"),
  z.literal("COMPONENT_REMOVED"),
  z.literal("STATUS_CHANGED"),
]);

export const publicCacheEngineSchema = z.union([
  z.literal("redis"),
  z.literal("valkey"),
]);

export const publicCloudProviderSchema = z.union([
  z.literal("aws"),
  z.literal("azure"),
  z.literal("gcp"),
]);

export const publicClusterStatusSchema = z.union([
  z.literal("PENDING"),
  z.literal("ONLINE"),
  z.literal("OFFLINE"),
]);

export const publicComponentStatusSchema = z.union([
  z.literal("PENDING"),
  z.literal("CREATING"),
  z.literal("ACTIVE"),
  z.literal("UPDATING"),
  z.literal("FAILED"),
  z.literal("DESTROYING"),
  z.literal("DESTROYED"),
]);

export const publicDeploymentResourceStatusSchema = z.union([
  z.literal("creating"),
  z.literal("created"),
  z.literal("updating"),
  z.literal("deleting"),
  z.literal("deleted"),
  z.literal("failed"),
]);

export const publicDeploymentStatusSchema = z.union([
  z.literal("pending"),
  z.literal("initializing"),
  z.literal("planning"),
  z.literal("applying"),
  z.literal("completed"),
  z.literal("failed"),
  z.literal("cancelled"),
  z.literal("destroying"),
]);

export const publicEnvironmentStageSchema = z.union([
  z.literal("development"),
  z.literal("staging"),
  z.literal("production"),
]);

export const publicGitCredentialMethodSchema = z.union([
  z.literal("oauth"),
  z.literal("pat"),
  z.literal("deploy_key"),
]);

export const publicGitCredentialPurposeSchema = z.union([
  z.literal("argocd"),
  z.literal("applications"),
  z.literal("infrastructure"),
]);

export const publicGitProviderSchema = z.union([
  z.literal("github"),
  z.literal("bitbucket"),
  z.literal("gitlab"),
]);

export const publicIacToolSchema = z.union([
  z.literal("pulumi"),
  z.literal("terraform"),
]);

export const publicIntegrationAuthMethodSchema = z.union([
  z.literal("oauth"),
  z.literal("iam_role"),
  z.literal("service_account"),
  z.literal("service_principal"),
  z.literal("ram_role"),
  z.literal("api_key"),
]);

export const publicIntegrationCategorySchema = z.union([
  z.literal("git"),
  z.literal("cloud"),
  z.literal("observability"),
  z.literal("registry"),
  z.literal("dns"),
  z.literal("secrets"),
]);

export const publicIntegrationStatusSchema = z.union([
  z.literal("active"),
  z.literal("coming_soon"),
]);

export const publicLogsLevelSchema = z.union([
  z.literal("debug"),
  z.literal("info"),
  z.literal("warn"),
  z.literal("error"),
  z.literal("critical"),
]);

export const publicNosqlBillingModeSchema = z.union([
  z.literal("PAY_PER_REQUEST"),
  z.literal("PROVISIONED"),
]);

export const publicNosqlKeyTypeSchema = z.union([
  z.literal("S"),
  z.literal("N"),
  z.literal("B"),
]);

export const publicNosqlTableTypeSchema = z.union([
  z.literal("standard"),
  z.literal("global"),
]);

export const publicProvisionJobStatusSchema = z.union([
  z.literal("QUEUED"),
  z.literal("CLAIMED"),
  z.literal("PROCESSING"),
  z.literal("SUCCESS"),
  z.literal("FAILED"),
  z.literal("CANCELLED"),
]);

export const publicProvisionJobTypeSchema = z.union([
  z.literal("DESTROY_WORKER"),
  z.literal("DEPLOY"),
  z.literal("DESTROY"),
  z.literal("CONNECTION_TEST"),
  z.literal("FETCH_RESOURCES"),
  z.literal("PLAN"),
  z.literal("DEPLOY_WORKER"),
  z.literal("UPDATE_WORKER"),
]);

export const publicRegistryTagMutabilitySchema = z.union([
  z.literal("MUTABLE"),
  z.literal("IMMUTABLE"),
]);

export const publicVineStatusSchema = z.union([
  z.literal("DRAFT"),
  z.literal("QUEUED"),
  z.literal("PROVISIONING"),
  z.literal("ACTIVE"),
  z.literal("FAILED"),
  z.literal("DESTROYING"),
  z.literal("DESTROYED"),
]);

export const publicWorkerModeSchema = z.union([
  z.literal("self-hosted"),
  z.literal("cloud-hosted"),
]);

export const publicWorkerStatusSchema = z.union([
  z.literal("ONLINE"),
  z.literal("OFFLINE"),
  z.literal("DRAINING"),
]);

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicCliLoginsRowSchema = z.object({
  created_at: z.string().nullable(),
  device_code: z.string(),
  expires_at: z.string().nullable(),
  profile_id: z.string().nullable(),
  refresh_token: z.string().nullable(),
  verification_code: z.string().nullable(),
});

export const publicCliLoginsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  device_code: z.string(),
  expires_at: z.string().optional().nullable(),
  profile_id: z.string().optional().nullable(),
  refresh_token: z.string().optional().nullable(),
  verification_code: z.string().optional().nullable(),
});

export const publicCliLoginsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  device_code: z.string().optional(),
  expires_at: z.string().optional().nullable(),
  profile_id: z.string().optional().nullable(),
  refresh_token: z.string().optional().nullable(),
  verification_code: z.string().optional().nullable(),
});

export const publicCliLoginsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("cli_logins_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCloudIdentitiesRowSchema = z.object({
  cached_at: z.string().nullable(),
  cached_resources: z
    .object({
      regions: z.array(z.string()).optional(),
      vpcs: z
        .record(
          z.string(),
          z.array(
            z.object({
              ID: z.string(),
              CIDR: z.string(),
              Name: z.string(),
              IsDefault: z.boolean(),
            }),
          ),
        )
        .optional(),
      subnets: z
        .union([
          z.record(
            z.string(),
            z.record(
              z.string(),
              z.array(
                z.object({
                  ID: z.string(),
                  CIDR: z.string(),
                  VpcID: z.string(),
                  AvailabilityZone: z.string(),
                }),
              ),
            ),
          ),
          z.record(
            z.string(),
            z.array(
              z.object({
                name: z.string(),
                region: z.string(),
                ipCidrRange: z.string(),
                network: z.string(),
              }),
            ),
          ),
          z.record(
            z.string(),
            z.array(
              z.object({
                name: z.string(),
                id: z.string(),
                addressPrefix: z.string(),
                vnetName: z.string(),
              }),
            ),
          ),
        ])
        .optional(),
      hosted_zones: z
        .array(
          z.object({
            ID: z.string(),
            Name: z.string(),
            RecordCount: z.number(),
            IsPrivate: z.boolean(),
          }),
        )
        .optional(),
      networks: z
        .array(
          z.object({
            name: z.string(),
            selfLink: z.string(),
            autoCreateSubnetworks: z.boolean(),
          }),
        )
        .optional(),
      managed_zones: z
        .array(
          z.object({
            name: z.string(),
            dnsName: z.string(),
            visibility: z.string(),
          }),
        )
        .optional(),
      locations: z.array(z.string()).optional(),
      vnets: z
        .array(
          z.object({
            name: z.string(),
            id: z.string(),
            location: z.string(),
            addressPrefixes: z.array(z.string()),
          }),
        )
        .optional(),
      dns_zones: z
        .array(
          z.object({
            name: z.string(),
            id: z.string(),
            zoneType: z.string(),
          }),
        )
        .optional(),
    })
    .nullable(),
  created_at: z.string().nullable(),
  credentials: z.object({
    role_arn: z.string().optional().nullable(),
    external_id: z.string().optional().nullable(),
    account_id: z.string().optional().nullable(),
  }),
  id: z.string(),
  is_verified: z.boolean().nullable(),
  name: z.string(),
  provider: publicCloudProviderSchema,
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicCloudIdentitiesInsertSchema = z.object({
  cached_at: z.string().optional().nullable(),
  cached_resources: z
    .object({
      regions: z.array(z.string()).optional(),
      vpcs: z
        .record(
          z.string(),
          z.array(
            z.object({
              ID: z.string(),
              CIDR: z.string(),
              Name: z.string(),
              IsDefault: z.boolean(),
            }),
          ),
        )
        .optional(),
      subnets: z
        .union([
          z.record(
            z.string(),
            z.record(
              z.string(),
              z.array(
                z.object({
                  ID: z.string(),
                  CIDR: z.string(),
                  VpcID: z.string(),
                  AvailabilityZone: z.string(),
                }),
              ),
            ),
          ),
          z.record(
            z.string(),
            z.array(
              z.object({
                name: z.string(),
                region: z.string(),
                ipCidrRange: z.string(),
                network: z.string(),
              }),
            ),
          ),
          z.record(
            z.string(),
            z.array(
              z.object({
                name: z.string(),
                id: z.string(),
                addressPrefix: z.string(),
                vnetName: z.string(),
              }),
            ),
          ),
        ])
        .optional(),
      hosted_zones: z
        .array(
          z.object({
            ID: z.string(),
            Name: z.string(),
            RecordCount: z.number(),
            IsPrivate: z.boolean(),
          }),
        )
        .optional(),
      networks: z
        .array(
          z.object({
            name: z.string(),
            selfLink: z.string(),
            autoCreateSubnetworks: z.boolean(),
          }),
        )
        .optional(),
      managed_zones: z
        .array(
          z.object({
            name: z.string(),
            dnsName: z.string(),
            visibility: z.string(),
          }),
        )
        .optional(),
      locations: z.array(z.string()).optional(),
      vnets: z
        .array(
          z.object({
            name: z.string(),
            id: z.string(),
            location: z.string(),
            addressPrefixes: z.array(z.string()),
          }),
        )
        .optional(),
      dns_zones: z
        .array(
          z.object({
            name: z.string(),
            id: z.string(),
            zoneType: z.string(),
          }),
        )
        .optional(),
    })
    .optional()
    .nullable(),
  created_at: z.string().optional().nullable(),
  credentials: z
    .object({
      role_arn: z.string().optional().nullable(),
      external_id: z.string().optional().nullable(),
      account_id: z.string().optional().nullable(),
    })
    .optional(),
  id: z.string().optional(),
  is_verified: z.boolean().optional().nullable(),
  name: z.string().optional(),
  provider: publicCloudProviderSchema,
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicCloudIdentitiesUpdateSchema = z.object({
  cached_at: z.string().optional().nullable(),
  cached_resources: z
    .object({
      regions: z.array(z.string()).optional(),
      vpcs: z
        .record(
          z.string(),
          z.array(
            z.object({
              ID: z.string(),
              CIDR: z.string(),
              Name: z.string(),
              IsDefault: z.boolean(),
            }),
          ),
        )
        .optional(),
      subnets: z
        .union([
          z.record(
            z.string(),
            z.record(
              z.string(),
              z.array(
                z.object({
                  ID: z.string(),
                  CIDR: z.string(),
                  VpcID: z.string(),
                  AvailabilityZone: z.string(),
                }),
              ),
            ),
          ),
          z.record(
            z.string(),
            z.array(
              z.object({
                name: z.string(),
                region: z.string(),
                ipCidrRange: z.string(),
                network: z.string(),
              }),
            ),
          ),
          z.record(
            z.string(),
            z.array(
              z.object({
                name: z.string(),
                id: z.string(),
                addressPrefix: z.string(),
                vnetName: z.string(),
              }),
            ),
          ),
        ])
        .optional(),
      hosted_zones: z
        .array(
          z.object({
            ID: z.string(),
            Name: z.string(),
            RecordCount: z.number(),
            IsPrivate: z.boolean(),
          }),
        )
        .optional(),
      networks: z
        .array(
          z.object({
            name: z.string(),
            selfLink: z.string(),
            autoCreateSubnetworks: z.boolean(),
          }),
        )
        .optional(),
      managed_zones: z
        .array(
          z.object({
            name: z.string(),
            dnsName: z.string(),
            visibility: z.string(),
          }),
        )
        .optional(),
      locations: z.array(z.string()).optional(),
      vnets: z
        .array(
          z.object({
            name: z.string(),
            id: z.string(),
            location: z.string(),
            addressPrefixes: z.array(z.string()),
          }),
        )
        .optional(),
      dns_zones: z
        .array(
          z.object({
            name: z.string(),
            id: z.string(),
            zoneType: z.string(),
          }),
        )
        .optional(),
    })
    .optional()
    .nullable(),
  created_at: z.string().optional().nullable(),
  credentials: z
    .object({
      role_arn: z.string().optional().nullable(),
      external_id: z.string().optional().nullable(),
      account_id: z.string().optional().nullable(),
    })
    .optional(),
  id: z.string().optional(),
  is_verified: z.boolean().optional().nullable(),
  name: z.string().optional(),
  provider: publicCloudProviderSchema.optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicIntegrationsRowSchema = z.object({
  auth_method: publicIntegrationAuthMethodSchema,
  category: publicIntegrationCategorySchema,
  created_at: z.string().nullable(),
  description: z.string(),
  docs_url: z.string().nullable(),
  icon_url: z.string(),
  id: z.string(),
  name: z.string(),
  organization: z.string(),
  privacy_url: z.string().nullable(),
  slug: z.string(),
  sort_order: z.number(),
  status: publicIntegrationStatusSchema,
  support_url: z.string().nullable(),
  updated_at: z.string().nullable(),
});

export const publicIntegrationsInsertSchema = z.object({
  auth_method: publicIntegrationAuthMethodSchema,
  category: publicIntegrationCategorySchema,
  created_at: z.string().optional().nullable(),
  description: z.string(),
  docs_url: z.string().optional().nullable(),
  icon_url: z.string(),
  id: z.string().optional(),
  name: z.string(),
  organization: z.string(),
  privacy_url: z.string().optional().nullable(),
  slug: z.string(),
  sort_order: z.number().optional(),
  status: publicIntegrationStatusSchema.optional(),
  support_url: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicIntegrationsUpdateSchema = z.object({
  auth_method: publicIntegrationAuthMethodSchema.optional(),
  category: publicIntegrationCategorySchema.optional(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional(),
  docs_url: z.string().optional().nullable(),
  icon_url: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  organization: z.string().optional(),
  privacy_url: z.string().optional().nullable(),
  slug: z.string().optional(),
  sort_order: z.number().optional(),
  status: publicIntegrationStatusSchema.optional(),
  support_url: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicJobLogsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.number(),
  job_id: z.string(),
  log_chunk: z.string(),
  stream_type: z.string().nullable(),
});

export const publicJobLogsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  job_id: z.string(),
  log_chunk: z.string(),
  stream_type: z.string().optional().nullable(),
});

export const publicJobLogsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  job_id: z.string().optional(),
  log_chunk: z.string().optional(),
  stream_type: z.string().optional().nullable(),
});

export const publicJobLogsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("job_logs_job_id_fkey"),
    columns: z.tuple([z.literal("job_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("provision_jobs"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProfilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  created_at: z.string(),
  email: z.string().nullable(),
  full_name: z.string().nullable(),
  id: z.string(),
});

export const publicProfilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
});

export const publicProfilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
});

export const publicProviderTokensRowSchema = z.object({
  access_token: z.string(),
  created_at: z.string().nullable(),
  expires_at: z.string().nullable(),
  id: z.string(),
  provider: publicGitProviderSchema,
  refresh_token: z.string().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicProviderTokensInsertSchema = z.object({
  access_token: z.string(),
  created_at: z.string().optional().nullable(),
  expires_at: z.string().optional().nullable(),
  id: z.string().optional(),
  provider: publicGitProviderSchema,
  refresh_token: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicProviderTokensUpdateSchema = z.object({
  access_token: z.string().optional(),
  created_at: z.string().optional().nullable(),
  expires_at: z.string().optional().nullable(),
  id: z.string().optional(),
  provider: publicGitProviderSchema.optional(),
  refresh_token: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicProvisionJobsRowSchema = z.object({
  assigned_worker_id: z.string().nullable(),
  claimed_at: z.string().nullable(),
  cloud_identity_id: z.string().nullable(),
  completed_at: z.string().nullable(),
  config_snapshot: z.record(z.string(), z.unknown()),
  configuration_hash: z.string().nullable(),
  created_at: z.string().nullable(),
  error_message: z.string().nullable(),
  execution_metadata: z.record(z.string(), z.unknown()).nullable(),
  id: z.string(),
  job_type: publicProvisionJobTypeSchema,
  plan_job_id: z.string().nullable(),
  started_at: z.string().nullable(),
  status: publicProvisionJobStatusSchema,
  updated_at: z.string().nullable(),
  user_id: z.string(),
  vine_id: z.string().nullable(),
  vineyard_id: z.string().nullable(),
  worker_id: z.string().nullable(),
});

export const publicProvisionJobsInsertSchema = z.object({
  assigned_worker_id: z.string().optional().nullable(),
  claimed_at: z.string().optional().nullable(),
  cloud_identity_id: z.string().optional().nullable(),
  completed_at: z.string().optional().nullable(),
  config_snapshot: z.record(z.string(), z.unknown()).optional(),
  configuration_hash: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  execution_metadata: z.record(z.string(), z.unknown()).optional().nullable(),
  id: z.string().optional(),
  job_type: publicProvisionJobTypeSchema,
  plan_job_id: z.string().optional().nullable(),
  started_at: z.string().optional().nullable(),
  status: publicProvisionJobStatusSchema.optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
  vine_id: z.string().optional().nullable(),
  vineyard_id: z.string().optional().nullable(),
  worker_id: z.string().optional().nullable(),
});

export const publicProvisionJobsUpdateSchema = z.object({
  assigned_worker_id: z.string().optional().nullable(),
  claimed_at: z.string().optional().nullable(),
  cloud_identity_id: z.string().optional().nullable(),
  completed_at: z.string().optional().nullable(),
  config_snapshot: z.record(z.string(), z.unknown()).optional(),
  configuration_hash: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  execution_metadata: z.record(z.string(), z.unknown()).optional().nullable(),
  id: z.string().optional(),
  job_type: publicProvisionJobTypeSchema.optional(),
  plan_job_id: z.string().optional().nullable(),
  started_at: z.string().optional().nullable(),
  status: publicProvisionJobStatusSchema.optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
  vine_id: z.string().optional().nullable(),
  vineyard_id: z.string().optional().nullable(),
  worker_id: z.string().optional().nullable(),
});

export const publicProvisionJobsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("provision_jobs_assigned_worker_id_fkey"),
    columns: z.tuple([z.literal("assigned_worker_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("workers"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("provision_jobs_cloud_identity_id_fkey"),
    columns: z.tuple([z.literal("cloud_identity_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("cloud_identities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("provision_jobs_plan_job_id_fkey"),
    columns: z.tuple([z.literal("plan_job_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("provision_jobs"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("provision_jobs_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("provision_jobs_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("provision_jobs_vineyard_id_fkey"),
    columns: z.tuple([z.literal("vineyard_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vineyards"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("provision_jobs_worker_id_fkey"),
    columns: z.tuple([z.literal("worker_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("workers"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineAuditLogRowSchema = z.object({
  action: publicAuditActionSchema,
  changes: z.record(z.string(), z.unknown()).nullable(),
  component_id: z.string().nullable(),
  component_type: z.string().nullable(),
  created_at: z.string(),
  id: z.number(),
  user_id: z.string(),
  vine_id: z.string(),
});

export const publicVineAuditLogInsertSchema = z.object({
  action: publicAuditActionSchema,
  changes: z.record(z.string(), z.unknown()).optional().nullable(),
  component_id: z.string().optional().nullable(),
  component_type: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  user_id: z.string().optional(),
  vine_id: z.string(),
});

export const publicVineAuditLogUpdateSchema = z.object({
  action: publicAuditActionSchema.optional(),
  changes: z.record(z.string(), z.unknown()).optional().nullable(),
  component_id: z.string().optional().nullable(),
  component_type: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  user_id: z.string().optional(),
  vine_id: z.string().optional(),
});

export const publicVineAuditLogRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_audit_log_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_audit_log_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineCachesRowSchema = z.object({
  allowed_cidr_blocks: z.array(z.string()).nullable(),
  created_at: z.string(),
  endpoint: z.string().nullable(),
  engine: publicCacheEngineSchema.nullable(),
  estimated_monthly_cost: z.number().nullable(),
  id: z.string(),
  multi_az: z.boolean().nullable(),
  name: z.string(),
  node_type: z.string().nullable(),
  num_cache_nodes: z.number().nullable(),
  status: publicComponentStatusSchema,
  status_message: z.string().nullable(),
  updated_at: z.string(),
  vine_id: z.string(),
});

export const publicVineCachesInsertSchema = z.object({
  allowed_cidr_blocks: z.array(z.string()).optional().nullable(),
  created_at: z.string().optional(),
  endpoint: z.string().optional().nullable(),
  engine: publicCacheEngineSchema.optional().nullable(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  multi_az: z.boolean().optional().nullable(),
  name: z.string(),
  node_type: z.string().optional().nullable(),
  num_cache_nodes: z.number().optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
});

export const publicVineCachesUpdateSchema = z.object({
  allowed_cidr_blocks: z.array(z.string()).optional().nullable(),
  created_at: z.string().optional(),
  endpoint: z.string().optional().nullable(),
  engine: publicCacheEngineSchema.optional().nullable(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  multi_az: z.boolean().optional().nullable(),
  name: z.string().optional(),
  node_type: z.string().optional().nullable(),
  num_cache_nodes: z.number().optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
});

export const publicVineCachesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_caches_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_caches_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineClusterRowSchema = z.object({
  argocd_admin_password: z.string().nullable(),
  argocd_url: z.string().nullable(),
  cluster_admins: z
    .array(
      z.object({
        username: z.string(),
        groups: z.array(z.string()),
      }),
    )
    .nullable(),
  cluster_arn: z.string().nullable(),
  cluster_endpoint: z.string().nullable(),
  cluster_name: z.string().nullable(),
  cluster_version: z.string().nullable(),
  created_at: z.string(),
  estimated_monthly_cost: z.number().nullable(),
  id: z.string(),
  instance_types: z.array(z.string()).nullable(),
  node_desired_size: z.number().nullable(),
  node_max_size: z.number().nullable(),
  node_min_size: z.number().nullable(),
  provider_config: z
    .object({
      enable_karpenter: z.boolean().optional(),
      enable_autopilot: z.boolean().optional(),
    })
    .nullable(),
  status: publicComponentStatusSchema,
  status_message: z.string().nullable(),
  updated_at: z.string(),
  vine_id: z.string(),
});

export const publicVineClusterInsertSchema = z.object({
  argocd_admin_password: z.string().optional().nullable(),
  argocd_url: z.string().optional().nullable(),
  cluster_admins: z
    .array(
      z.object({
        username: z.string(),
        groups: z.array(z.string()),
      }),
    )
    .optional()
    .nullable(),
  cluster_arn: z.string().optional().nullable(),
  cluster_endpoint: z.string().optional().nullable(),
  cluster_name: z.string().optional().nullable(),
  cluster_version: z.string().optional().nullable(),
  created_at: z.string().optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  instance_types: z.array(z.string()).optional().nullable(),
  node_desired_size: z.number().optional().nullable(),
  node_max_size: z.number().optional().nullable(),
  node_min_size: z.number().optional().nullable(),
  provider_config: z
    .object({
      enable_karpenter: z.boolean().optional(),
      enable_autopilot: z.boolean().optional(),
    })
    .optional()
    .nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
});

export const publicVineClusterUpdateSchema = z.object({
  argocd_admin_password: z.string().optional().nullable(),
  argocd_url: z.string().optional().nullable(),
  cluster_admins: z
    .array(
      z.object({
        username: z.string(),
        groups: z.array(z.string()),
      }),
    )
    .optional()
    .nullable(),
  cluster_arn: z.string().optional().nullable(),
  cluster_endpoint: z.string().optional().nullable(),
  cluster_name: z.string().optional().nullable(),
  cluster_version: z.string().optional().nullable(),
  created_at: z.string().optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  instance_types: z.array(z.string()).optional().nullable(),
  node_desired_size: z.number().optional().nullable(),
  node_max_size: z.number().optional().nullable(),
  node_min_size: z.number().optional().nullable(),
  provider_config: z
    .object({
      enable_karpenter: z.boolean().optional(),
      enable_autopilot: z.boolean().optional(),
    })
    .optional()
    .nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
});

export const publicVineClusterRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_eks_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_eks_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineContainerRegistriesRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  image_tag_mutability: publicRegistryTagMutabilitySchema.nullable(),
  name: z.string(),
  provider_config: z
    .object({
      vulnerability_scanning: z.boolean().optional(),
    })
    .nullable(),
  repository_url: z.string().nullable(),
  scan_on_push: z.boolean().nullable(),
  status: publicComponentStatusSchema,
  status_message: z.string().nullable(),
  updated_at: z.string(),
  vine_id: z.string(),
});

export const publicVineContainerRegistriesInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  image_tag_mutability: publicRegistryTagMutabilitySchema.optional().nullable(),
  name: z.string(),
  provider_config: z
    .object({
      vulnerability_scanning: z.boolean().optional(),
    })
    .optional()
    .nullable(),
  repository_url: z.string().optional().nullable(),
  scan_on_push: z.boolean().optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
});

export const publicVineContainerRegistriesUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  image_tag_mutability: publicRegistryTagMutabilitySchema.optional().nullable(),
  name: z.string().optional(),
  provider_config: z
    .object({
      vulnerability_scanning: z.boolean().optional(),
    })
    .optional()
    .nullable(),
  repository_url: z.string().optional().nullable(),
  scan_on_push: z.boolean().optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
});

export const publicVineContainerRegistriesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_ecr_repos_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_ecr_repos_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineDatabasesRowSchema = z.object({
  backup_retention_days: z.number().nullable(),
  cluster_arn: z.string().nullable(),
  cluster_identifier: z.string().nullable(),
  created_at: z.string(),
  credentials_kms_key_arn: z.string().nullable(),
  endpoint: z.string().nullable(),
  engine: z.string().nullable(),
  engine_version: z.string().nullable(),
  estimated_monthly_cost: z.number().nullable(),
  extra_credentials_secret_arn: z.string().nullable(),
  iam_auth: z.boolean().nullable(),
  id: z.string(),
  master_credentials_secret_arn: z.string().nullable(),
  max_capacity: z.number().nullable(),
  min_capacity: z.number().nullable(),
  name: z.string(),
  port: z.number().nullable(),
  reader_endpoint: z.string().nullable(),
  status: publicComponentStatusSchema,
  status_message: z.string().nullable(),
  updated_at: z.string(),
  vine_id: z.string(),
});

export const publicVineDatabasesInsertSchema = z.object({
  backup_retention_days: z.number().optional().nullable(),
  cluster_arn: z.string().optional().nullable(),
  cluster_identifier: z.string().optional().nullable(),
  created_at: z.string().optional(),
  credentials_kms_key_arn: z.string().optional().nullable(),
  endpoint: z.string().optional().nullable(),
  engine: z.string().optional().nullable(),
  engine_version: z.string().optional().nullable(),
  estimated_monthly_cost: z.number().optional().nullable(),
  extra_credentials_secret_arn: z.string().optional().nullable(),
  iam_auth: z.boolean().optional().nullable(),
  id: z.string().optional(),
  master_credentials_secret_arn: z.string().optional().nullable(),
  max_capacity: z.number().optional().nullable(),
  min_capacity: z.number().optional().nullable(),
  name: z.string(),
  port: z.number().optional().nullable(),
  reader_endpoint: z.string().optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
});

export const publicVineDatabasesUpdateSchema = z.object({
  backup_retention_days: z.number().optional().nullable(),
  cluster_arn: z.string().optional().nullable(),
  cluster_identifier: z.string().optional().nullable(),
  created_at: z.string().optional(),
  credentials_kms_key_arn: z.string().optional().nullable(),
  endpoint: z.string().optional().nullable(),
  engine: z.string().optional().nullable(),
  engine_version: z.string().optional().nullable(),
  estimated_monthly_cost: z.number().optional().nullable(),
  extra_credentials_secret_arn: z.string().optional().nullable(),
  iam_auth: z.boolean().optional().nullable(),
  id: z.string().optional(),
  master_credentials_secret_arn: z.string().optional().nullable(),
  max_capacity: z.number().optional().nullable(),
  min_capacity: z.number().optional().nullable(),
  name: z.string().optional(),
  port: z.number().optional().nullable(),
  reader_endpoint: z.string().optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
});

export const publicVineDatabasesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_databases_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_databases_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineDnsRowSchema = z.object({
  created_at: z.string(),
  domain_name: z.string().nullable(),
  enabled: z.boolean(),
  estimated_monthly_cost: z.number().nullable(),
  id: z.string(),
  managed_certificate: z.boolean().nullable(),
  provider_config: z
    .object({
      acm_certificate: z.boolean().optional(),
      cloudfront_waf: z.boolean().optional(),
      application_waf: z.boolean().optional(),
      cloud_armor: z.boolean().optional(),
      azure_waf: z.boolean().optional(),
    })
    .nullable(),
  status: publicComponentStatusSchema,
  status_message: z.string().nullable(),
  updated_at: z.string(),
  vine_id: z.string(),
  waf_enabled: z.boolean().nullable(),
  zone_id: z.string().nullable(),
});

export const publicVineDnsInsertSchema = z.object({
  created_at: z.string().optional(),
  domain_name: z.string().optional().nullable(),
  enabled: z.boolean().optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  managed_certificate: z.boolean().optional().nullable(),
  provider_config: z
    .object({
      acm_certificate: z.boolean().optional(),
      cloudfront_waf: z.boolean().optional(),
      application_waf: z.boolean().optional(),
      cloud_armor: z.boolean().optional(),
      azure_waf: z.boolean().optional(),
    })
    .optional()
    .nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
  waf_enabled: z.boolean().optional().nullable(),
  zone_id: z.string().optional().nullable(),
});

export const publicVineDnsUpdateSchema = z.object({
  created_at: z.string().optional(),
  domain_name: z.string().optional().nullable(),
  enabled: z.boolean().optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  managed_certificate: z.boolean().optional().nullable(),
  provider_config: z
    .object({
      acm_certificate: z.boolean().optional(),
      cloudfront_waf: z.boolean().optional(),
      application_waf: z.boolean().optional(),
      cloud_armor: z.boolean().optional(),
      azure_waf: z.boolean().optional(),
    })
    .optional()
    .nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
  waf_enabled: z.boolean().optional().nullable(),
  zone_id: z.string().optional().nullable(),
});

export const publicVineDnsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_dns_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_dns_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineGitCredentialsRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  method: publicGitCredentialMethodSchema,
  provider_identity_id: z.string().nullable(),
  purpose: publicGitCredentialPurposeSchema,
  secret_ref: z.string().nullable(),
  vine_id: z.string(),
});

export const publicVineGitCredentialsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  method: publicGitCredentialMethodSchema,
  provider_identity_id: z.string().optional().nullable(),
  purpose: publicGitCredentialPurposeSchema,
  secret_ref: z.string().optional().nullable(),
  vine_id: z.string(),
});

export const publicVineGitCredentialsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  method: publicGitCredentialMethodSchema.optional(),
  provider_identity_id: z.string().optional().nullable(),
  purpose: publicGitCredentialPurposeSchema.optional(),
  secret_ref: z.string().optional().nullable(),
  vine_id: z.string().optional(),
});

export const publicVineGitCredentialsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_git_credentials_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_git_credentials_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineNetworkRowSchema = z.object({
  allowed_cidr_blocks: z.array(z.string()).nullable(),
  cidr_block: z.string().nullable(),
  created_at: z.string(),
  estimated_monthly_cost: z.number().nullable(),
  id: z.string(),
  network_id: z.string().nullable(),
  provision_network: z.boolean(),
  single_nat_gateway: z.boolean().nullable(),
  status: publicComponentStatusSchema,
  status_message: z.string().nullable(),
  updated_at: z.string(),
  vine_id: z.string(),
});

export const publicVineNetworkInsertSchema = z.object({
  allowed_cidr_blocks: z.array(z.string()).optional().nullable(),
  cidr_block: z.string().optional().nullable(),
  created_at: z.string().optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  network_id: z.string().optional().nullable(),
  provision_network: z.boolean().optional(),
  single_nat_gateway: z.boolean().optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
});

export const publicVineNetworkUpdateSchema = z.object({
  allowed_cidr_blocks: z.array(z.string()).optional().nullable(),
  cidr_block: z.string().optional().nullable(),
  created_at: z.string().optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  network_id: z.string().optional().nullable(),
  provision_network: z.boolean().optional(),
  single_nat_gateway: z.boolean().optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
});

export const publicVineNetworkRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_vpc_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_vpc_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineNosqlTablesRowSchema = z.object({
  billing_mode: publicNosqlBillingModeSchema.nullable(),
  created_at: z.string(),
  estimated_monthly_cost: z.number().nullable(),
  global_replicas: z.array(z.string()).nullable(),
  hash_key: z.string(),
  hash_key_type: publicNosqlKeyTypeSchema.nullable(),
  id: z.string(),
  name: z.string(),
  point_in_time_recovery: z.boolean().nullable(),
  provider_config: z
    .object({
      partition_key_path: z.string().optional(),
    })
    .nullable(),
  range_key: z.string().nullable(),
  range_key_type: publicNosqlKeyTypeSchema.nullable(),
  status: publicComponentStatusSchema,
  status_message: z.string().nullable(),
  table_type: publicNosqlTableTypeSchema.nullable(),
  updated_at: z.string(),
  vine_id: z.string(),
});

export const publicVineNosqlTablesInsertSchema = z.object({
  billing_mode: publicNosqlBillingModeSchema.optional().nullable(),
  created_at: z.string().optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  global_replicas: z.array(z.string()).optional().nullable(),
  hash_key: z.string(),
  hash_key_type: publicNosqlKeyTypeSchema.optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  point_in_time_recovery: z.boolean().optional().nullable(),
  provider_config: z
    .object({
      partition_key_path: z.string().optional(),
    })
    .optional()
    .nullable(),
  range_key: z.string().optional().nullable(),
  range_key_type: publicNosqlKeyTypeSchema.optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  table_type: publicNosqlTableTypeSchema.optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
});

export const publicVineNosqlTablesUpdateSchema = z.object({
  billing_mode: publicNosqlBillingModeSchema.optional().nullable(),
  created_at: z.string().optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  global_replicas: z.array(z.string()).optional().nullable(),
  hash_key: z.string().optional(),
  hash_key_type: publicNosqlKeyTypeSchema.optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  point_in_time_recovery: z.boolean().optional().nullable(),
  provider_config: z
    .object({
      partition_key_path: z.string().optional(),
    })
    .optional()
    .nullable(),
  range_key: z.string().optional().nullable(),
  range_key_type: publicNosqlKeyTypeSchema.optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  table_type: publicNosqlTableTypeSchema.optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
});

export const publicVineNosqlTablesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_dynamodb_tables_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_dynamodb_tables_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineQueuesRowSchema = z.object({
  created_at: z.string(),
  delay_seconds: z.number().nullable(),
  estimated_monthly_cost: z.number().nullable(),
  fifo: z.boolean().nullable(),
  id: z.string(),
  message_retention: z.number().nullable(),
  name: z.string(),
  status: publicComponentStatusSchema,
  status_message: z.string().nullable(),
  updated_at: z.string(),
  vine_id: z.string(),
  visibility_timeout: z.number().nullable(),
});

export const publicVineQueuesInsertSchema = z.object({
  created_at: z.string().optional(),
  delay_seconds: z.number().optional().nullable(),
  estimated_monthly_cost: z.number().optional().nullable(),
  fifo: z.boolean().optional().nullable(),
  id: z.string().optional(),
  message_retention: z.number().optional().nullable(),
  name: z.string(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
  visibility_timeout: z.number().optional().nullable(),
});

export const publicVineQueuesUpdateSchema = z.object({
  created_at: z.string().optional(),
  delay_seconds: z.number().optional().nullable(),
  estimated_monthly_cost: z.number().optional().nullable(),
  fifo: z.boolean().optional().nullable(),
  id: z.string().optional(),
  message_retention: z.number().optional().nullable(),
  name: z.string().optional(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
  visibility_timeout: z.number().optional().nullable(),
});

export const publicVineQueuesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_queues_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_queues_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineRepositoriesRowSchema = z.object({
  apps_destination_repo: z.string().nullable(),
  apps_template_branch: z.string().nullable(),
  apps_template_repo: z.string().nullable(),
  created_at: z.string(),
  env_destination_repo: z.string().nullable(),
  env_template_branch: z.string().nullable(),
  env_template_repo: z.string(),
  gitops_destination_repo: z.string().nullable(),
  gitops_template_branch: z.string().nullable(),
  gitops_template_repo: z.string(),
  id: z.string(),
  updated_at: z.string(),
  vine_id: z.string(),
});

export const publicVineRepositoriesInsertSchema = z.object({
  apps_destination_repo: z.string().optional().nullable(),
  apps_template_branch: z.string().optional().nullable(),
  apps_template_repo: z.string().optional().nullable(),
  created_at: z.string().optional(),
  env_destination_repo: z.string().optional().nullable(),
  env_template_branch: z.string().optional().nullable(),
  env_template_repo: z.string().optional(),
  gitops_destination_repo: z.string().optional().nullable(),
  gitops_template_branch: z.string().optional().nullable(),
  gitops_template_repo: z.string().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
});

export const publicVineRepositoriesUpdateSchema = z.object({
  apps_destination_repo: z.string().optional().nullable(),
  apps_template_branch: z.string().optional().nullable(),
  apps_template_repo: z.string().optional().nullable(),
  created_at: z.string().optional(),
  env_destination_repo: z.string().optional().nullable(),
  env_template_branch: z.string().optional().nullable(),
  env_template_repo: z.string().optional(),
  gitops_destination_repo: z.string().optional().nullable(),
  gitops_template_branch: z.string().optional().nullable(),
  gitops_template_repo: z.string().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
});

export const publicVineRepositoriesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_repositories_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_repositories_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineSecretsRowSchema = z.object({
  created_at: z.string(),
  generate: z.boolean().nullable(),
  id: z.string(),
  length: z.number().nullable(),
  name: z.string(),
  special_chars: z.boolean().nullable(),
  status: publicComponentStatusSchema,
  status_message: z.string().nullable(),
  updated_at: z.string(),
  vine_id: z.string(),
});

export const publicVineSecretsInsertSchema = z.object({
  created_at: z.string().optional(),
  generate: z.boolean().optional().nullable(),
  id: z.string().optional(),
  length: z.number().optional().nullable(),
  name: z.string(),
  special_chars: z.boolean().optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
});

export const publicVineSecretsUpdateSchema = z.object({
  created_at: z.string().optional(),
  generate: z.boolean().optional().nullable(),
  id: z.string().optional(),
  length: z.number().optional().nullable(),
  name: z.string().optional(),
  special_chars: z.boolean().optional().nullable(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
});

export const publicVineSecretsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_secrets_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_secrets_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineTopicsRowSchema = z.object({
  created_at: z.string(),
  estimated_monthly_cost: z.number().nullable(),
  id: z.string(),
  name: z.string(),
  status: publicComponentStatusSchema,
  status_message: z.string().nullable(),
  subscriptions: z
    .array(
      z.object({
        protocol: z.string(),
        endpoint: z.string(),
      }),
    )
    .nullable(),
  updated_at: z.string(),
  vine_id: z.string(),
});

export const publicVineTopicsInsertSchema = z.object({
  created_at: z.string().optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  subscriptions: z
    .array(
      z.object({
        protocol: z.string(),
        endpoint: z.string(),
      }),
    )
    .optional()
    .nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string(),
});

export const publicVineTopicsUpdateSchema = z.object({
  created_at: z.string().optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  status: publicComponentStatusSchema.optional(),
  status_message: z.string().optional().nullable(),
  subscriptions: z
    .array(
      z.object({
        protocol: z.string(),
        endpoint: z.string(),
      }),
    )
    .optional()
    .nullable(),
  updated_at: z.string().optional(),
  vine_id: z.string().optional(),
});

export const publicVineTopicsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vine_topics_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vine_full"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vine_topics_vine_id_fkey"),
    columns: z.tuple([z.literal("vine_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vines"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVinesRowSchema = z.object({
  cloud_identity_id: z.string().nullable(),
  created_at: z.string(),
  environment_stage: publicEnvironmentStageSchema,
  estimated_monthly_cost: z.number().nullable(),
  id: z.string(),
  project_name: z.string(),
  region: z.string(),
  status: publicVineStatusSchema,
  terraform_version: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
  vineyard_id: z.string().nullable(),
});

export const publicVinesInsertSchema = z.object({
  cloud_identity_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  environment_stage: publicEnvironmentStageSchema.optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  project_name: z.string(),
  region: z.string().optional(),
  status: publicVineStatusSchema.optional(),
  terraform_version: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
  vineyard_id: z.string().optional().nullable(),
});

export const publicVinesUpdateSchema = z.object({
  cloud_identity_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  environment_stage: publicEnvironmentStageSchema.optional(),
  estimated_monthly_cost: z.number().optional().nullable(),
  id: z.string().optional(),
  project_name: z.string().optional(),
  region: z.string().optional(),
  status: publicVineStatusSchema.optional(),
  terraform_version: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
  vineyard_id: z.string().optional().nullable(),
});

export const publicVinesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vines_cloud_identity_id_fkey"),
    columns: z.tuple([z.literal("cloud_identity_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("cloud_identities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vines_vineyard_id_fkey"),
    columns: z.tuple([z.literal("vineyard_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vineyards"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineyardsRowSchema = z.object({
  created_at: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicVineyardsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const publicVineyardsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicWorkerReleasesRowSchema = z.object({
  id: z.string(),
  release_notes: z.string(),
  released_at: z.string(),
  version: z.string(),
});

export const publicWorkerReleasesInsertSchema = z.object({
  id: z.string().optional(),
  release_notes: z.string().optional(),
  released_at: z.string().optional(),
  version: z.string(),
});

export const publicWorkerReleasesUpdateSchema = z.object({
  id: z.string().optional(),
  release_notes: z.string().optional(),
  released_at: z.string().optional(),
  version: z.string().optional(),
});

export const publicWorkersRowSchema = z.object({
  cloud_identity_id: z.string().nullable(),
  created_at: z.string().nullable(),
  id: z.string(),
  is_default: z.boolean(),
  last_heartbeat: z.string().nullable(),
  metadata: z.record(z.string(), z.unknown()).nullable(),
  mode: publicWorkerModeSchema,
  name: z.string(),
  release_id: z.string().nullable(),
  status: publicWorkerStatusSchema.nullable(),
  token_hash: z.string(),
  user_id: z.string().nullable(),
  version: z.string().nullable(),
});

export const publicWorkersInsertSchema = z.object({
  cloud_identity_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_default: z.boolean().optional(),
  last_heartbeat: z.string().optional().nullable(),
  metadata: z.record(z.string(), z.unknown()).optional().nullable(),
  mode: publicWorkerModeSchema,
  name: z.string(),
  release_id: z.string().optional().nullable(),
  status: publicWorkerStatusSchema.optional().nullable(),
  token_hash: z.string(),
  user_id: z.string().optional().nullable(),
  version: z.string().optional().nullable(),
});

export const publicWorkersUpdateSchema = z.object({
  cloud_identity_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_default: z.boolean().optional(),
  last_heartbeat: z.string().optional().nullable(),
  metadata: z.record(z.string(), z.unknown()).optional().nullable(),
  mode: publicWorkerModeSchema.optional(),
  name: z.string().optional(),
  release_id: z.string().optional().nullable(),
  status: publicWorkerStatusSchema.optional().nullable(),
  token_hash: z.string().optional(),
  user_id: z.string().optional().nullable(),
  version: z.string().optional().nullable(),
});

export const publicWorkersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("workers_cloud_identity_id_fkey"),
    columns: z.tuple([z.literal("cloud_identity_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("cloud_identities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("workers_release_id_fkey"),
    columns: z.tuple([z.literal("release_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("worker_releases"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVineFullRowSchema = z.object({
  acm_certificate_enable: z.boolean().nullable(),
  application_waf_enabled: z.boolean().nullable(),
  applications_destination_repo: z.string().nullable(),
  applications_template_repo: z.string().nullable(),
  applications_template_repo_branch: z.string().nullable(),
  aws_account_id: z.string().nullable(),
  aws_region: z.string().nullable(),
  cloud_identity_id: z.string().nullable(),
  cloud_provider: publicCloudProviderSchema.nullable(),
  cloudfront_waf_enabled: z.boolean().nullable(),
  cluster_admins: jsonSchema.nullable(),
  cluster_endpoint: z.string().nullable(),
  cluster_name: z.string().nullable(),
  cluster_status: z.string().nullable(),
  cluster_version: z.string().nullable(),
  create_rds: z.boolean().nullable(),
  create_vpc: z.boolean().nullable(),
  created_at: z.string().nullable(),
  db_max_capacity: z.number().nullable(),
  db_min_capacity: z.number().nullable(),
  dns_hosted_zone: z.string().nullable(),
  dns_main_domain: z.string().nullable(),
  dns_status: z.string().nullable(),
  eks_status: z.string().nullable(),
  enable_dns: z.boolean().nullable(),
  enable_karpenter: z.boolean().nullable(),
  enable_redis: z.boolean().nullable(),
  env_git_repo: z.string().nullable(),
  env_template_repo: z.string().nullable(),
  env_template_repo_branch: z.string().nullable(),
  environment_stage: z.string().nullable(),
  estimated_monthly_cost: z.number().nullable(),
  gitops_destination_repo: z.string().nullable(),
  gitops_template_repo: z.string().nullable(),
  gitops_template_repo_branch: z.string().nullable(),
  id: z.string().nullable(),
  instance_types: z.array(z.string()).nullable(),
  network_status: z.string().nullable(),
  node_desired_size: z.number().nullable(),
  node_max_size: z.number().nullable(),
  node_min_size: z.number().nullable(),
  project_name: z.string().nullable(),
  region: z.string().nullable(),
  selected_vpc_id: z.string().nullable(),
  single_nat_gateway: z.boolean().nullable(),
  status: z.string().nullable(),
  terraform_version: z.string().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string().nullable(),
  vineyard_id: z.string().nullable(),
  vpc_cidr: z.string().nullable(),
  vpc_status: z.string().nullable(),
  waf_enabled: z.boolean().nullable(),
});

export const publicVineFullRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vines_cloud_identity_id_fkey"),
    columns: z.tuple([z.literal("cloud_identity_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("cloud_identities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("vines_vineyard_id_fkey"),
    columns: z.tuple([z.literal("vineyard_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vineyards"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicClaimNextJobArgsSchema = z.object({
  p_cloud_identity_id: z.string().optional(),
  p_worker_id: z.string(),
  p_worker_token_hash: z.string(),
});

export const publicClaimNextJobReturnsSchema = z.array(
  z.object({
    assigned_worker_id: z.string().nullable(),
    claimed_at: z.string().nullable(),
    cloud_identity_id: z.string().nullable(),
    completed_at: z.string().nullable(),
    config_snapshot: jsonSchema,
    configuration_hash: z.string().nullable(),
    created_at: z.string().nullable(),
    error_message: z.string().nullable(),
    execution_metadata: jsonSchema.nullable(),
    id: z.string(),
    job_type: publicProvisionJobTypeSchema,
    plan_job_id: z.string().nullable(),
    started_at: z.string().nullable(),
    status: publicProvisionJobStatusSchema,
    updated_at: z.string().nullable(),
    user_id: z.string(),
    vine_id: z.string().nullable(),
    vineyard_id: z.string().nullable(),
    worker_id: z.string().nullable(),
  }),
);

export const publicInsertJobLogArgsSchema = z.object({
  p_job_id: z.string(),
  p_log_chunk: z.string(),
  p_stream_type: z.string().optional(),
  p_worker_id: z.string(),
  p_worker_token_hash: z.string(),
});

export const publicInsertJobLogReturnsSchema = z.undefined();

export const publicRecoverStaleJobsArgsSchema = z.never();

export const publicRecoverStaleJobsReturnsSchema = z.number();

export const publicSetDefaultWorkerArgsSchema = z.object({
  p_worker_id: z.string().optional(),
});

export const publicSetDefaultWorkerReturnsSchema = z.undefined();

export const publicUpdateJobStatusArgsSchema = z.object({
  p_error_message: z.string().optional(),
  p_execution_metadata: jsonSchema.optional(),
  p_job_id: z.string(),
  p_status: z.string(),
  p_worker_id: z.string(),
  p_worker_token_hash: z.string(),
});

export const publicUpdateJobStatusReturnsSchema = z.undefined();
