/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./database.schemas";
export type PublicCloudProvider = z.infer<
  typeof generated.publicCloudProviderSchema
>;
export type PublicClusterStatus = z.infer<
  typeof generated.publicClusterStatusSchema
>;
export type PublicDeploymentResourceStatus = z.infer<
  typeof generated.publicDeploymentResourceStatusSchema
>;
export type PublicDeploymentStatus = z.infer<
  typeof generated.publicDeploymentStatusSchema
>;
export type PublicGitProvider = z.infer<
  typeof generated.publicGitProviderSchema
>;
export type PublicIacTool = z.infer<typeof generated.publicIacToolSchema>;
export type PublicLogsLevel = z.infer<typeof generated.publicLogsLevelSchema>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicBootstrapJobsRow = z.infer<
  typeof generated.publicBootstrapJobsRowSchema
>;
export type PublicBootstrapJobsInsert = z.infer<
  typeof generated.publicBootstrapJobsInsertSchema
>;
export type PublicBootstrapJobsUpdate = z.infer<
  typeof generated.publicBootstrapJobsUpdateSchema
>;
export type PublicBootstrapJobsRelationships = z.infer<
  typeof generated.publicBootstrapJobsRelationshipsSchema
>;
export type PublicBootstrapLogsRow = z.infer<
  typeof generated.publicBootstrapLogsRowSchema
>;
export type PublicBootstrapLogsInsert = z.infer<
  typeof generated.publicBootstrapLogsInsertSchema
>;
export type PublicBootstrapLogsUpdate = z.infer<
  typeof generated.publicBootstrapLogsUpdateSchema
>;
export type PublicBootstrapLogsRelationships = z.infer<
  typeof generated.publicBootstrapLogsRelationshipsSchema
>;
export type PublicCliLoginsRow = z.infer<
  typeof generated.publicCliLoginsRowSchema
>;
export type PublicCliLoginsInsert = z.infer<
  typeof generated.publicCliLoginsInsertSchema
>;
export type PublicCliLoginsUpdate = z.infer<
  typeof generated.publicCliLoginsUpdateSchema
>;
export type PublicCliLoginsRelationships = z.infer<
  typeof generated.publicCliLoginsRelationshipsSchema
>;
export type PublicCloudIdentitiesRow = z.infer<
  typeof generated.publicCloudIdentitiesRowSchema
>;
export type PublicCloudIdentitiesInsert = z.infer<
  typeof generated.publicCloudIdentitiesInsertSchema
>;
export type PublicCloudIdentitiesUpdate = z.infer<
  typeof generated.publicCloudIdentitiesUpdateSchema
>;
export type PublicClustersRow = z.infer<
  typeof generated.publicClustersRowSchema
>;
export type PublicClustersInsert = z.infer<
  typeof generated.publicClustersInsertSchema
>;
export type PublicClustersUpdate = z.infer<
  typeof generated.publicClustersUpdateSchema
>;
export type PublicConfigurationsRow = z.infer<
  typeof generated.publicConfigurationsRowSchema
>;
export type PublicConfigurationsInsert = z.infer<
  typeof generated.publicConfigurationsInsertSchema
>;
export type PublicConfigurationsUpdate = z.infer<
  typeof generated.publicConfigurationsUpdateSchema
>;
export type PublicConfigurationsRelationships = z.infer<
  typeof generated.publicConfigurationsRelationshipsSchema
>;
export type PublicDeploymentLogsRow = z.infer<
  typeof generated.publicDeploymentLogsRowSchema
>;
export type PublicDeploymentLogsInsert = z.infer<
  typeof generated.publicDeploymentLogsInsertSchema
>;
export type PublicDeploymentLogsUpdate = z.infer<
  typeof generated.publicDeploymentLogsUpdateSchema
>;
export type PublicDeploymentLogsRelationships = z.infer<
  typeof generated.publicDeploymentLogsRelationshipsSchema
>;
export type PublicDeploymentResourcesRow = z.infer<
  typeof generated.publicDeploymentResourcesRowSchema
>;
export type PublicDeploymentResourcesInsert = z.infer<
  typeof generated.publicDeploymentResourcesInsertSchema
>;
export type PublicDeploymentResourcesUpdate = z.infer<
  typeof generated.publicDeploymentResourcesUpdateSchema
>;
export type PublicDeploymentResourcesRelationships = z.infer<
  typeof generated.publicDeploymentResourcesRelationshipsSchema
>;
export type PublicDeploymentsRow = z.infer<
  typeof generated.publicDeploymentsRowSchema
>;
export type PublicDeploymentsInsert = z.infer<
  typeof generated.publicDeploymentsInsertSchema
>;
export type PublicDeploymentsUpdate = z.infer<
  typeof generated.publicDeploymentsUpdateSchema
>;
export type PublicDeploymentsRelationships = z.infer<
  typeof generated.publicDeploymentsRelationshipsSchema
>;
export type PublicHarvestsRow = z.infer<
  typeof generated.publicHarvestsRowSchema
>;
export type PublicHarvestsInsert = z.infer<
  typeof generated.publicHarvestsInsertSchema
>;
export type PublicHarvestsUpdate = z.infer<
  typeof generated.publicHarvestsUpdateSchema
>;
export type PublicHarvestsRelationships = z.infer<
  typeof generated.publicHarvestsRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<
  typeof generated.publicProfilesRowSchema
>;
export type PublicProfilesInsert = z.infer<
  typeof generated.publicProfilesInsertSchema
>;
export type PublicProfilesUpdate = z.infer<
  typeof generated.publicProfilesUpdateSchema
>;
export type PublicProviderTokensRow = z.infer<
  typeof generated.publicProviderTokensRowSchema
>;
export type PublicProviderTokensInsert = z.infer<
  typeof generated.publicProviderTokensInsertSchema
>;
export type PublicProviderTokensUpdate = z.infer<
  typeof generated.publicProviderTokensUpdateSchema
>;
export type PublicProvisionLogsRow = z.infer<
  typeof generated.publicProvisionLogsRowSchema
>;
export type PublicProvisionLogsInsert = z.infer<
  typeof generated.publicProvisionLogsInsertSchema
>;
export type PublicProvisionLogsUpdate = z.infer<
  typeof generated.publicProvisionLogsUpdateSchema
>;
export type PublicProvisionLogsRelationships = z.infer<
  typeof generated.publicProvisionLogsRelationshipsSchema
>;
export type PublicProvisionsRow = z.infer<
  typeof generated.publicProvisionsRowSchema
>;
export type PublicProvisionsInsert = z.infer<
  typeof generated.publicProvisionsInsertSchema
>;
export type PublicProvisionsUpdate = z.infer<
  typeof generated.publicProvisionsUpdateSchema
>;
export type PublicProvisionsRelationships = z.infer<
  typeof generated.publicProvisionsRelationshipsSchema
>;
export type PublicVineyardsRow = z.infer<
  typeof generated.publicVineyardsRowSchema
>;
export type PublicVineyardsInsert = z.infer<
  typeof generated.publicVineyardsInsertSchema
>;
export type PublicVineyardsUpdate = z.infer<
  typeof generated.publicVineyardsUpdateSchema
>;
export type PublicAgentHeartbeatArgs = z.infer<
  typeof generated.publicAgentHeartbeatArgsSchema
>;
export type PublicAgentHeartbeatReturns = z.infer<
  typeof generated.publicAgentHeartbeatReturnsSchema
>;
export type PublicFetchNextProvisionArgs = z.infer<
  typeof generated.publicFetchNextProvisionArgsSchema
>;
export type PublicFetchNextProvisionReturns = z.infer<
  typeof generated.publicFetchNextProvisionReturnsSchema
>;
export type PublicGetConfigurationStatsArgs = z.infer<
  typeof generated.publicGetConfigurationStatsArgsSchema
>;
export type PublicGetConfigurationStatsReturns = z.infer<
  typeof generated.publicGetConfigurationStatsReturnsSchema
>;
export type PublicInsertProvisionLogArgs = z.infer<
  typeof generated.publicInsertProvisionLogArgsSchema
>;
export type PublicInsertProvisionLogReturns = z.infer<
  typeof generated.publicInsertProvisionLogReturnsSchema
>;
export type PublicUpdateProvisionStatusArgs = z.infer<
  typeof generated.publicUpdateProvisionStatusArgsSchema
>;
export type PublicUpdateProvisionStatusReturns = z.infer<
  typeof generated.publicUpdateProvisionStatusReturnsSchema
>;
