CREATE TYPE "public"."breakglass_action" AS ENUM('open_session', 'inspect_job', 'retry_job', 'cancel_job', 'unstick_env', 'drain_runner', 'restart_runner', 'replay_webhook', 'force_release_state_lock', 'state_surgery', 'orphan_detect', 'orphan_clean');--> statement-breakpoint
CREATE TYPE "public"."breakglass_blast_radius" AS ENUM('none', 'low', 'medium', 'high');--> statement-breakpoint
ALTER TYPE "public"."provision_job_type" ADD VALUE 'STATE_SURGERY';--> statement-breakpoint
CREATE TABLE "breakglass_approval" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"approver_email" text NOT NULL,
	"action" "breakglass_action" NOT NULL,
	"resource_type" text NOT NULL,
	"resource_id" text NOT NULL,
	"input_hash" text NOT NULL,
	"reason" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed_at" timestamp with time zone,
	"consumed_by" text
);
--> statement-breakpoint
CREATE TABLE "breakglass_audit" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "breakglass_audit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"session_id" uuid,
	"actor_email" text NOT NULL,
	"action" "breakglass_action" NOT NULL,
	"blast_radius" "breakglass_blast_radius" NOT NULL,
	"resource_type" text NOT NULL,
	"resource_id" text,
	"input" jsonb,
	"reason" text NOT NULL,
	"approver_email" text,
	"approval_id" uuid,
	"phase" text NOT NULL,
	"outcome" text,
	"detail" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "breakglass_session" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"operator_email" text NOT NULL,
	"reason" text NOT NULL,
	"opened_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"closed_at" timestamp with time zone,
	"ip" text,
	"user_agent" text
);
--> statement-breakpoint
CREATE INDEX "idx_breakglass_approval_lookup" ON "breakglass_approval" USING btree ("action","resource_id");--> statement-breakpoint
CREATE INDEX "idx_breakglass_audit_session" ON "breakglass_audit" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_breakglass_audit_created" ON "breakglass_audit" USING btree ("created_at");