CREATE TYPE "public"."platform_collection_method" AS ENUM('stripe', 'external');--> statement-breakpoint
CREATE TABLE "enterprise_contract" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"plan" text NOT NULL,
	"seats" bigint,
	"term_start" timestamp with time zone NOT NULL,
	"term_end" timestamp with time zone,
	"collection_method" "platform_collection_method" NOT NULL,
	"amount_cents" bigint,
	"currency" text DEFAULT 'usd' NOT NULL,
	"contract_ref" text,
	"invoice_ref" text,
	"notes" text,
	"stripe_customer_id" text,
	"stripe_subscription_id" text,
	"created_by_email" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	"revoked_by_email" text
);
--> statement-breakpoint
CREATE TABLE "platform_audit" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "platform_audit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"actor_email" text NOT NULL,
	"action" text NOT NULL,
	"target_org_id" uuid,
	"input" jsonb,
	"reason" text NOT NULL,
	"phase" text NOT NULL,
	"outcome" text,
	"detail" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_enterprise_contract_org" ON "enterprise_contract" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_enterprise_contract_term_end" ON "enterprise_contract" USING btree ("term_end");--> statement-breakpoint
CREATE INDEX "idx_platform_audit_org" ON "platform_audit" USING btree ("target_org_id");--> statement-breakpoint
CREATE INDEX "idx_platform_audit_created" ON "platform_audit" USING btree ("created_at");