CREATE TABLE "payment_holds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"subscription_id" text NOT NULL,
	"customer_id" text NOT NULL,
	"payer_key" text NOT NULL,
	"invoice_id" text NOT NULL,
	"payment_intent_id" text,
	"state" text NOT NULL,
	"release_reason" text,
	"released_at" timestamp with time zone,
	"released_by" text,
	"release_note" text,
	"refund_attempt" integer DEFAULT 0 NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"next_check_at" timestamp with time zone,
	"alerted_at" timestamp with time zone,
	"notice_last_sent_at" timestamp with time zone,
	"notified_state" text,
	"notified_at" timestamp with time zone,
	"opened_by_user_id" text,
	"opened_by" text NOT NULL,
	"open_note" text,
	"state_since" timestamp with time zone DEFAULT now() NOT NULL,
	"last_pay" text,
	"refund_action_since" timestamp with time zone,
	"age_alerted_at" timestamp with time zone,
	"observed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"nudged_at" timestamp with time zone,
	"version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payment_holds_state_known" CHECK (state IN ('closing', 'cancel_unproven', 'payment_in_flight', 'invoice_payable', 'refund_due', 'refund_pending', 'needs_operator', 'released')),
	CONSTRAINT "payment_holds_release_reason_known" CHECK (release_reason IS NULL OR release_reason IN ('voided_unpaid', 'deleted_draft', 'refunded', 'already_refunded', 'adopted', 'expired_unpaid', 'operator')),
	CONSTRAINT "payment_holds_opened_by_known" CHECK (opened_by IN ('purchase', 'backfill', 'link')),
	CONSTRAINT "payment_holds_notified_state_known" CHECK (notified_state IS NULL OR notified_state IN ('refund_pending', 'released:refunded', 'released:adopted')),
	CONSTRAINT "payment_holds_release_shape" CHECK ((state = 'released') = (release_reason IS NOT NULL AND released_at IS NOT NULL)),
	CONSTRAINT "payment_holds_open_is_scheduled" CHECK (state = 'released' OR next_check_at IS NOT NULL)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "payment_holds_open_subscription_uidx" ON "payment_holds" USING btree ("subscription_id") WHERE state <> 'released';--> statement-breakpoint
CREATE INDEX "payment_holds_open_payer_idx" ON "payment_holds" USING btree ("payer_key") WHERE state <> 'released';