/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./database.schemas";
export type PublicAuditAction = z.infer<
  typeof generated.publicAuditActionSchema
>;
export type PublicCacheEngine = z.infer<
  typeof generated.publicCacheEngineSchema
>;
export type PublicCloudProvider = z.infer<
  typeof generated.publicCloudProviderSchema
>;
export type PublicClusterStatus = z.infer<
  typeof generated.publicClusterStatusSchema
>;
export type PublicComponentStatus = z.infer<
  typeof generated.publicComponentStatusSchema
>;
export type PublicDeploymentResourceStatus = z.infer<
  typeof generated.publicDeploymentResourceStatusSchema
>;
export type PublicDeploymentStatus = z.infer<
  typeof generated.publicDeploymentStatusSchema
>;
export type PublicEnvironmentStage = z.infer<
  typeof generated.publicEnvironmentStageSchema
>;
export type PublicGitCredentialMethod = z.infer<
  typeof generated.publicGitCredentialMethodSchema
>;
export type PublicGitCredentialPurpose = z.infer<
  typeof generated.publicGitCredentialPurposeSchema
>;
export type PublicGitProvider = z.infer<
  typeof generated.publicGitProviderSchema
>;
export type PublicIacTool = z.infer<typeof generated.publicIacToolSchema>;
export type PublicIntegrationAuthMethod = z.infer<
  typeof generated.publicIntegrationAuthMethodSchema
>;
export type PublicIntegrationCategory = z.infer<
  typeof generated.publicIntegrationCategorySchema
>;
export type PublicIntegrationStatus = z.infer<
  typeof generated.publicIntegrationStatusSchema
>;
export type PublicLogsLevel = z.infer<typeof generated.publicLogsLevelSchema>;
export type PublicNosqlBillingMode = z.infer<
  typeof generated.publicNosqlBillingModeSchema
>;
export type PublicNosqlKeyType = z.infer<
  typeof generated.publicNosqlKeyTypeSchema
>;
export type PublicNosqlTableType = z.infer<
  typeof generated.publicNosqlTableTypeSchema
>;
export type PublicProvisionJobStatus = z.infer<
  typeof generated.publicProvisionJobStatusSchema
>;
export type PublicProvisionJobType = z.infer<
  typeof generated.publicProvisionJobTypeSchema
>;
export type PublicRegistryTagMutability = z.infer<
  typeof generated.publicRegistryTagMutabilitySchema
>;
export type PublicVineStatus = z.infer<typeof generated.publicVineStatusSchema>;
export type PublicWorkerMode = z.infer<typeof generated.publicWorkerModeSchema>;
export type PublicWorkerStatus = z.infer<
  typeof generated.publicWorkerStatusSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicCliLoginsRow = z.infer<
  typeof generated.publicCliLoginsRowSchema
>;
export type PublicCliLoginsInsert = z.infer<
  typeof generated.publicCliLoginsInsertSchema
>;
export type PublicCliLoginsUpdate = z.infer<
  typeof generated.publicCliLoginsUpdateSchema
>;
export type PublicCliLoginsRelationships = z.infer<
  typeof generated.publicCliLoginsRelationshipsSchema
>;
export type PublicCloudIdentitiesRow = z.infer<
  typeof generated.publicCloudIdentitiesRowSchema
>;
export type PublicCloudIdentitiesInsert = z.infer<
  typeof generated.publicCloudIdentitiesInsertSchema
>;
export type PublicCloudIdentitiesUpdate = z.infer<
  typeof generated.publicCloudIdentitiesUpdateSchema
>;
export type PublicIntegrationsRow = z.infer<
  typeof generated.publicIntegrationsRowSchema
>;
export type PublicIntegrationsInsert = z.infer<
  typeof generated.publicIntegrationsInsertSchema
>;
export type PublicIntegrationsUpdate = z.infer<
  typeof generated.publicIntegrationsUpdateSchema
>;
export type PublicJobLogsRow = z.infer<typeof generated.publicJobLogsRowSchema>;
export type PublicJobLogsInsert = z.infer<
  typeof generated.publicJobLogsInsertSchema
>;
export type PublicJobLogsUpdate = z.infer<
  typeof generated.publicJobLogsUpdateSchema
>;
export type PublicJobLogsRelationships = z.infer<
  typeof generated.publicJobLogsRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<
  typeof generated.publicProfilesRowSchema
>;
export type PublicProfilesInsert = z.infer<
  typeof generated.publicProfilesInsertSchema
>;
export type PublicProfilesUpdate = z.infer<
  typeof generated.publicProfilesUpdateSchema
>;
export type PublicProviderTokensRow = z.infer<
  typeof generated.publicProviderTokensRowSchema
>;
export type PublicProviderTokensInsert = z.infer<
  typeof generated.publicProviderTokensInsertSchema
>;
export type PublicProviderTokensUpdate = z.infer<
  typeof generated.publicProviderTokensUpdateSchema
>;
export type PublicProvisionJobsRow = z.infer<
  typeof generated.publicProvisionJobsRowSchema
>;
export type PublicProvisionJobsInsert = z.infer<
  typeof generated.publicProvisionJobsInsertSchema
>;
export type PublicProvisionJobsUpdate = z.infer<
  typeof generated.publicProvisionJobsUpdateSchema
>;
export type PublicProvisionJobsRelationships = z.infer<
  typeof generated.publicProvisionJobsRelationshipsSchema
>;
export type PublicVineAuditLogRow = z.infer<
  typeof generated.publicVineAuditLogRowSchema
>;
export type PublicVineAuditLogInsert = z.infer<
  typeof generated.publicVineAuditLogInsertSchema
>;
export type PublicVineAuditLogUpdate = z.infer<
  typeof generated.publicVineAuditLogUpdateSchema
>;
export type PublicVineAuditLogRelationships = z.infer<
  typeof generated.publicVineAuditLogRelationshipsSchema
>;
export type PublicVineCachesRow = z.infer<
  typeof generated.publicVineCachesRowSchema
>;
export type PublicVineCachesInsert = z.infer<
  typeof generated.publicVineCachesInsertSchema
>;
export type PublicVineCachesUpdate = z.infer<
  typeof generated.publicVineCachesUpdateSchema
>;
export type PublicVineCachesRelationships = z.infer<
  typeof generated.publicVineCachesRelationshipsSchema
>;
export type PublicVineClusterRow = z.infer<
  typeof generated.publicVineClusterRowSchema
>;
export type PublicVineClusterInsert = z.infer<
  typeof generated.publicVineClusterInsertSchema
>;
export type PublicVineClusterUpdate = z.infer<
  typeof generated.publicVineClusterUpdateSchema
>;
export type PublicVineClusterRelationships = z.infer<
  typeof generated.publicVineClusterRelationshipsSchema
>;
export type PublicVineContainerRegistriesRow = z.infer<
  typeof generated.publicVineContainerRegistriesRowSchema
>;
export type PublicVineContainerRegistriesInsert = z.infer<
  typeof generated.publicVineContainerRegistriesInsertSchema
>;
export type PublicVineContainerRegistriesUpdate = z.infer<
  typeof generated.publicVineContainerRegistriesUpdateSchema
>;
export type PublicVineContainerRegistriesRelationships = z.infer<
  typeof generated.publicVineContainerRegistriesRelationshipsSchema
>;
export type PublicVineDatabasesRow = z.infer<
  typeof generated.publicVineDatabasesRowSchema
>;
export type PublicVineDatabasesInsert = z.infer<
  typeof generated.publicVineDatabasesInsertSchema
>;
export type PublicVineDatabasesUpdate = z.infer<
  typeof generated.publicVineDatabasesUpdateSchema
>;
export type PublicVineDatabasesRelationships = z.infer<
  typeof generated.publicVineDatabasesRelationshipsSchema
>;
export type PublicVineDnsRow = z.infer<typeof generated.publicVineDnsRowSchema>;
export type PublicVineDnsInsert = z.infer<
  typeof generated.publicVineDnsInsertSchema
>;
export type PublicVineDnsUpdate = z.infer<
  typeof generated.publicVineDnsUpdateSchema
>;
export type PublicVineDnsRelationships = z.infer<
  typeof generated.publicVineDnsRelationshipsSchema
>;
export type PublicVineGitCredentialsRow = z.infer<
  typeof generated.publicVineGitCredentialsRowSchema
>;
export type PublicVineGitCredentialsInsert = z.infer<
  typeof generated.publicVineGitCredentialsInsertSchema
>;
export type PublicVineGitCredentialsUpdate = z.infer<
  typeof generated.publicVineGitCredentialsUpdateSchema
>;
export type PublicVineGitCredentialsRelationships = z.infer<
  typeof generated.publicVineGitCredentialsRelationshipsSchema
>;
export type PublicVineNetworkRow = z.infer<
  typeof generated.publicVineNetworkRowSchema
>;
export type PublicVineNetworkInsert = z.infer<
  typeof generated.publicVineNetworkInsertSchema
>;
export type PublicVineNetworkUpdate = z.infer<
  typeof generated.publicVineNetworkUpdateSchema
>;
export type PublicVineNetworkRelationships = z.infer<
  typeof generated.publicVineNetworkRelationshipsSchema
>;
export type PublicVineNosqlTablesRow = z.infer<
  typeof generated.publicVineNosqlTablesRowSchema
>;
export type PublicVineNosqlTablesInsert = z.infer<
  typeof generated.publicVineNosqlTablesInsertSchema
>;
export type PublicVineNosqlTablesUpdate = z.infer<
  typeof generated.publicVineNosqlTablesUpdateSchema
>;
export type PublicVineNosqlTablesRelationships = z.infer<
  typeof generated.publicVineNosqlTablesRelationshipsSchema
>;
export type PublicVineQueuesRow = z.infer<
  typeof generated.publicVineQueuesRowSchema
>;
export type PublicVineQueuesInsert = z.infer<
  typeof generated.publicVineQueuesInsertSchema
>;
export type PublicVineQueuesUpdate = z.infer<
  typeof generated.publicVineQueuesUpdateSchema
>;
export type PublicVineQueuesRelationships = z.infer<
  typeof generated.publicVineQueuesRelationshipsSchema
>;
export type PublicVineRepositoriesRow = z.infer<
  typeof generated.publicVineRepositoriesRowSchema
>;
export type PublicVineRepositoriesInsert = z.infer<
  typeof generated.publicVineRepositoriesInsertSchema
>;
export type PublicVineRepositoriesUpdate = z.infer<
  typeof generated.publicVineRepositoriesUpdateSchema
>;
export type PublicVineRepositoriesRelationships = z.infer<
  typeof generated.publicVineRepositoriesRelationshipsSchema
>;
export type PublicVineSecretsRow = z.infer<
  typeof generated.publicVineSecretsRowSchema
>;
export type PublicVineSecretsInsert = z.infer<
  typeof generated.publicVineSecretsInsertSchema
>;
export type PublicVineSecretsUpdate = z.infer<
  typeof generated.publicVineSecretsUpdateSchema
>;
export type PublicVineSecretsRelationships = z.infer<
  typeof generated.publicVineSecretsRelationshipsSchema
>;
export type PublicVineStorageBucketsRow = z.infer<
  typeof generated.publicVineStorageBucketsRowSchema
>;
export type PublicVineStorageBucketsInsert = z.infer<
  typeof generated.publicVineStorageBucketsInsertSchema
>;
export type PublicVineStorageBucketsUpdate = z.infer<
  typeof generated.publicVineStorageBucketsUpdateSchema
>;
export type PublicVineStorageBucketsRelationships = z.infer<
  typeof generated.publicVineStorageBucketsRelationshipsSchema
>;
export type PublicVineTopicsRow = z.infer<
  typeof generated.publicVineTopicsRowSchema
>;
export type PublicVineTopicsInsert = z.infer<
  typeof generated.publicVineTopicsInsertSchema
>;
export type PublicVineTopicsUpdate = z.infer<
  typeof generated.publicVineTopicsUpdateSchema
>;
export type PublicVineTopicsRelationships = z.infer<
  typeof generated.publicVineTopicsRelationshipsSchema
>;
export type PublicVinesRow = z.infer<typeof generated.publicVinesRowSchema>;
export type PublicVinesInsert = z.infer<
  typeof generated.publicVinesInsertSchema
>;
export type PublicVinesUpdate = z.infer<
  typeof generated.publicVinesUpdateSchema
>;
export type PublicVinesRelationships = z.infer<
  typeof generated.publicVinesRelationshipsSchema
>;
export type PublicVineyardsRow = z.infer<
  typeof generated.publicVineyardsRowSchema
>;
export type PublicVineyardsInsert = z.infer<
  typeof generated.publicVineyardsInsertSchema
>;
export type PublicVineyardsUpdate = z.infer<
  typeof generated.publicVineyardsUpdateSchema
>;
export type PublicWorkerReleasesRow = z.infer<
  typeof generated.publicWorkerReleasesRowSchema
>;
export type PublicWorkerReleasesInsert = z.infer<
  typeof generated.publicWorkerReleasesInsertSchema
>;
export type PublicWorkerReleasesUpdate = z.infer<
  typeof generated.publicWorkerReleasesUpdateSchema
>;
export type PublicWorkersRow = z.infer<typeof generated.publicWorkersRowSchema>;
export type PublicWorkersInsert = z.infer<
  typeof generated.publicWorkersInsertSchema
>;
export type PublicWorkersUpdate = z.infer<
  typeof generated.publicWorkersUpdateSchema
>;
export type PublicWorkersRelationships = z.infer<
  typeof generated.publicWorkersRelationshipsSchema
>;
export type PublicVineFullRow = z.infer<
  typeof generated.publicVineFullRowSchema
>;
export type PublicVineFullRelationships = z.infer<
  typeof generated.publicVineFullRelationshipsSchema
>;
export type PublicClaimNextJobArgs = z.infer<
  typeof generated.publicClaimNextJobArgsSchema
>;
export type PublicClaimNextJobReturns = z.infer<
  typeof generated.publicClaimNextJobReturnsSchema
>;
export type PublicInsertJobLogArgs = z.infer<
  typeof generated.publicInsertJobLogArgsSchema
>;
export type PublicInsertJobLogReturns = z.infer<
  typeof generated.publicInsertJobLogReturnsSchema
>;
export type PublicRecoverStaleJobsArgs = z.infer<
  typeof generated.publicRecoverStaleJobsArgsSchema
>;
export type PublicRecoverStaleJobsReturns = z.infer<
  typeof generated.publicRecoverStaleJobsReturnsSchema
>;
export type PublicSetDefaultWorkerArgs = z.infer<
  typeof generated.publicSetDefaultWorkerArgsSchema
>;
export type PublicSetDefaultWorkerReturns = z.infer<
  typeof generated.publicSetDefaultWorkerReturnsSchema
>;
export type PublicUpdateJobStatusArgs = z.infer<
  typeof generated.publicUpdateJobStatusArgsSchema
>;
export type PublicUpdateJobStatusReturns = z.infer<
  typeof generated.publicUpdateJobStatusReturnsSchema
>;
