apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runner.fullname" . }}
  labels:
    {{- include "runner.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "runner.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "runner.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RUNNER_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "runner.fullname" . }}-config
                  key: cluster_id
            - name: RUNNER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "runner.fullname" . }}-config
                  key: api_token
            - name: ALETHIA_API_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "runner.fullname" . }}-config
                  key: alethia_api_origin
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
