# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grape < Formula
  desc "Grape CLI for managing infrastructure configurations."
  homepage "https://github.com/bobikenobi12/bb-thesis-2026"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bobikenobi12/bb-thesis-2026/releases/download/v0.1.3/grape_Darwin_x86_64.tar.gz"
      sha256 "49bc22e476ccb516cf32beed7019d803621e5fdc047d52a23d9e0d5f5dc584a6"

      define_method(:install) do
        bin.install "grape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bobikenobi12/bb-thesis-2026/releases/download/v0.1.3/grape_Darwin_arm64.tar.gz"
      sha256 "2a5403e2d6be8421cd79af2cb2c1992baf878241d49c220a2b0d83049fac0887"

      define_method(:install) do
        bin.install "grape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bobikenobi12/bb-thesis-2026/releases/download/v0.1.3/grape_Linux_x86_64.tar.gz"
      sha256 "558b613f58563d9106058bbb94f8bc9690884b999b339df2083319569fa95e2b"
      define_method(:install) do
        bin.install "grape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bobikenobi12/bb-thesis-2026/releases/download/v0.1.3/grape_Linux_arm64.tar.gz"
      sha256 "851b4b45e84231ef1a692501b8743c22e48eac47fc8c8659f428c60fb32c14eb"
      define_method(:install) do
        bin.install "grape"
      end
    end
  end
end
