# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grape < Formula
  desc "Grape CLI for managing infrastructure configurations."
  homepage "https://github.com/bobikenobi12/bb-thesis-2026"
  version "0.2.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bobikenobi12/bb-thesis-2026/releases/download/v0.2.1/grape_Darwin_x86_64.tar.gz"
      sha256 "52f05438b8d3303f920dafb24b6df083bd14cf76fc05e386b6d79d973ef32ec4"

      define_method(:install) do
        bin.install "grape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bobikenobi12/bb-thesis-2026/releases/download/v0.2.1/grape_Darwin_arm64.tar.gz"
      sha256 "bcbe53e42bb40f8d4601b2b3b064b8bc0222b514b6dc31796cc4b64599a864fc"

      define_method(:install) do
        bin.install "grape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bobikenobi12/bb-thesis-2026/releases/download/v0.2.1/grape_Linux_x86_64.tar.gz"
      sha256 "c097acb56653263a97e4bca20b5455cee2e77c5ec89d848769dfbd387bf91854"
      define_method(:install) do
        bin.install "grape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bobikenobi12/bb-thesis-2026/releases/download/v0.2.1/grape_Linux_arm64.tar.gz"
      sha256 "3ae98f2de39896e9c4fe7611cac7225c0e8d85b7885777bef99e36897520bafa"
      define_method(:install) do
        bin.install "grape"
      end
    end
  end

  test do
    system "#{bin}/grape", "--version"
  end
end
