// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Generates the typed TS mirror of the version-compatibility matrix from the single source
 * of truth (`packages/core/compat/matrix.json`). The same JSON is embedded by the Go engine
 * (`packages/core/compat`), so the console and the provisioner never drift — the same
 * discipline `gen-catalog.mjs` uses for the catalog.
 *
 * Run via `node apps/console/scripts/gen-matrix.mjs`. The `gen:matrix` package script + the CI
 * drift-check are wired by #1217.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const srcPath = resolve(repoRoot, "packages/core/compat/matrix.json");
const outPath = resolve(here, "../lib/compat/generated/matrix.ts");

const raw = readFileSync(srcPath, "utf8");
// Parse to validate it's well-formed before we emit.
const data = JSON.parse(raw);

// Emit a JS value as a TS literal, indented one level so it aligns under `export const ...`.
const emit = (v) => JSON.stringify(v, null, "\t").replace(/\n/g, "\n\t");

// Fail-fast shape guard: the matrix must carry every section, and its cross-field invariant
// (each cloud's default is one of its own supported minors) must hold — a malformed matrix.json
// reds here with a clear message instead of emitting a broken matrix.ts. check-types + the Go
// tests are the deeper guards; the #1217 CI drift-check re-runs this and fails on drift.
const REQUIRED_KEYS = [
	"version",
	"catalog_version",
	"k8s_cloud",
	"components",
	"addon_k8s",
	"static_couplings",
];
for (const k of REQUIRED_KEYS) {
	if (!(k in data)) throw new Error(`matrix.json is missing '${k}' (#1211)`);
}
if (typeof data.version !== "number") throw new Error("matrix.json `version` must be a number (#1211)");
if (!Array.isArray(data.components)) throw new Error("matrix.json `components` must be an array (#1211)");
if (!Array.isArray(data.static_couplings)) throw new Error("matrix.json `static_couplings` must be an array (#1211)");

for (const [slug, cloud] of Object.entries(data.k8s_cloud)) {
	if (!Array.isArray(cloud.supported) || cloud.supported.length === 0) {
		throw new Error(`matrix.json k8s_cloud.${slug} has no supported versions (#1211)`);
	}
	if (!cloud.default) throw new Error(`matrix.json k8s_cloud.${slug} has no default (#1211)`);
	if (!cloud.supported.includes(cloud.default)) {
		throw new Error(
			`matrix.json k8s_cloud.${slug} default '${cloud.default}' is not in supported [${cloud.supported}] (#1211)`,
		);
	}
}
for (const comp of data.components) {
	if (!comp.id || !Array.isArray(comp.versions)) {
		throw new Error(`matrix.json component ${comp.id ?? "?"} is malformed (#1211)`);
	}
}
for (const [id, rng] of Object.entries(data.addon_k8s)) {
	if (!("k8s_min" in rng) || !("k8s_max" in rng)) {
		throw new Error(`matrix.json addon_k8s.${id} must carry k8s_min + k8s_max (#1211)`);
	}
}

const json = emit(data);

const out = `// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// GENERATED by apps/console/scripts/gen-matrix.mjs — DO NOT EDIT.
// Source of truth: packages/core/compat/matrix.json (also embedded by the Go engine).
// Run \`node apps/console/scripts/gen-matrix.mjs\` to regenerate.

/** A managed cloud's supported Kubernetes minors (mirrors the catalog SSOT). */
export interface CloudK8s {
	supported: string[];
	default: string;
}

/** One released version of a component pinned to its supported Kubernetes window. */
export interface ComponentRelease {
	version: string;
	app_version?: string;
	k8s_min: string;
	k8s_max: string;
	note?: string;
}

/** A platform component and its recorded releases. */
export interface Component {
	id: string;
	title: string;
	versions: ComponentRelease[];
}

/** A supported Kubernetes minor window [k8s_min, k8s_max]. */
export interface K8sRange {
	k8s_min: string;
	k8s_max: string;
	note?: string;
}

/** A build-time version coupling (Go const ↔ Dockerfile ARG). Data only. */
export interface StaticCoupling {
	id: string;
	title?: string;
	value: string;
	go_const?: string;
	dockerfile_arg?: string;
	dockerfile?: string;
	note?: string;
}

/** The parsed compatibility matrix document. */
export interface Matrix {
	version: number;
	catalog_version: string;
	k8s_cloud: Record<string, CloudK8s>;
	components: Component[];
	addon_k8s: Record<string, K8sRange>;
	static_couplings: StaticCoupling[];
}

export const MATRIX: Matrix = ${json};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out);
console.log(`✓ wrote ${outPath}`);
