// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Generates the typed TS mirror of the cloud catalog from the single source of truth
 * (`packages/core/catalog/catalog.json`). The same JSON is embedded by the Go resolver,
 * so the UI and the provisioner never drift. Run via `pnpm -F console gen:catalog`;
 * CI re-runs it and fails on drift.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const srcPath = resolve(repoRoot, "packages/core/catalog/catalog.json");
const outPath = resolve(here, "../lib/cloud-providers/generated/catalog.ts");

const raw = readFileSync(srcPath, "utf8");
// Parse to validate it's well-formed before we emit; re-stringify for stable formatting.
const data = JSON.parse(raw);
const json = JSON.stringify(data, null, "\t").replace(/\n/g, "\n\t");

const out = `// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// GENERATED by apps/console/scripts/gen-catalog.mjs — DO NOT EDIT.
// Source of truth: packages/core/catalog/catalog.json (also embedded by the Go resolver).
// Run \`pnpm -F console gen:catalog\` to regenerate.

export type ProviderSlug = "aws" | "gcp" | "azure";
export type InstanceFamily = "general" | "compute" | "memory" | "gpu";
export type EngineFamily = "postgres" | "mysql";

export interface ProviderMeta {
	slug: string;
	name: string;
	cluster_service: string;
	network_name: string;
	dns_service: string;
	database_service: string;
	cache_service: string;
	nosql_service: string;
	queue_service: string;
	topic_service: string;
	storage_service: string;
	registry_service: string;
	secrets_service: string;
}

export interface Region {
	id: string;
	label: string;
	group: string;
	codes: Record<string, string>;
}

export interface Instance {
	value: string;
	label: string;
	vcpu: number;
	memory_gb: number;
	family: string;
	cost: string;
}

export interface ComputeProvider {
	default_instance: string;
	default_k8s_version: string;
	k8s_versions: string[];
	autoscaler_key: string;
	instances: Instance[];
}

export interface DBEngine {
	family: string;
	value: string;
	label: string;
	default_version: string;
}

export interface Capacity {
	unit: string;
	min: number;
	max: number;
	step: number;
	default_min: number;
	default_max: number;
}

export interface DatabaseProvider {
	capacity: Capacity;
	engines: DBEngine[];
}

export interface CacheTier {
	value: string;
	label: string;
	memory_gb: number;
	cost: string;
}

export interface CacheProvider {
	default_tier: string;
	tiers: CacheTier[];
}

export interface Catalog {
	version: number;
	providers: ProviderMeta[];
	regions: Region[];
	compute: Record<string, ComputeProvider>;
	database: Record<string, DatabaseProvider>;
	cache: Record<string, CacheProvider>;
}

export const CATALOG: Catalog = ${json};

/** Provider display + service-name metadata. */
export function providerMeta(slug: string): ProviderMeta | undefined {
	return CATALOG.providers.find((p) => p.slug === slug);
}

/** Resolve a canonical region id to a provider-specific region code. */
export function resolveRegion(
	canonicalId: string,
	provider: string,
): string | undefined {
	return CATALOG.regions.find((r) => r.id === canonicalId)?.codes[provider];
}

/** Compute (cluster node) inventory for a provider. */
export function listInstances(provider: string): Instance[] {
	return CATALOG.compute[provider]?.instances ?? [];
}

/**
 * Pick the provider machine type closest to the requested capability, preferring the
 * requested family when it has members (mirrors the Go resolver).
 */
export function nearestInstance(
	provider: string,
	vcpu: number,
	memoryGb: number,
	family?: string,
): Instance | undefined {
	const instances = listInstances(provider);
	if (instances.length === 0) return undefined;
	const sameFamily = family
		? instances.filter((i) => i.family === family)
		: [];
	const candidates = sameFamily.length > 0 ? sameFamily : instances;
	const dist = (i: Instance) =>
		Math.hypot(i.vcpu - vcpu, i.memory_gb - memoryGb);
	return candidates.reduce((best, i) => (dist(i) < dist(best) ? i : best));
}

/** Database engines for a provider. */
export function dbEngines(provider: string): DBEngine[] {
	return CATALOG.database[provider]?.engines ?? [];
}

/** Resolve an abstract engine family (postgres/mysql) to the provider engine. */
export function dbEngine(
	provider: string,
	family: string,
): DBEngine | undefined {
	return dbEngines(provider).find((e) => e.family === family);
}

/** Cache SKU inventory for a provider. */
export function cacheTiers(provider: string): CacheTier[] {
	return CATALOG.cache[provider]?.tiers ?? [];
}

/** Pick the provider cache SKU whose memory is closest to the requested size. */
export function nearestCacheTier(
	provider: string,
	memoryGb: number,
): CacheTier | undefined {
	const tiers = cacheTiers(provider);
	if (tiers.length === 0) return undefined;
	return tiers.reduce((best, t) =>
		Math.abs(t.memory_gb - memoryGb) < Math.abs(best.memory_gb - memoryGb)
			? t
			: best,
	);
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out);
console.log(`✓ wrote ${outPath}`);
