// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Generates `packages/core/routing/routes_gen.go` — the console's private route patterns as Go
 * constants — from the route manifest every conformance guard already reads
 * (`scripts/lib/console-routes.mjs`).
 *
 * The CLI builds deep links (`alethia open --project`, `project get --open`). Before this file the
 * one link it built was `{origin}/dashboard`, a legacy catch-all, and nothing could tell that the
 * project page lives at `/[org]/[project]`. Generating the patterns makes a route rename a BUILD
 * failure in Go: the constant disappears and every builder over it stops compiling.
 *
 * Direction of authority: the console owns its routes, so TS generates and Go consumes. Go cannot
 * write this file, so a Go-only change has no way to make itself right.
 *
 * Usage:
 *   pnpm -C apps/console run gen:go-routes          # regenerate
 *   pnpm -C apps/console run gen:go-routes:check    # render and COMPARE with the committed file;
 *                                                   # non-zero when stale — this is check:route-parity
 *
 * Unlike gen-go-brand's `--check`, this one compares against the committed file, because the
 * question the epic asks of it is "does the CLI's route table match the console's tree", and that is
 * a comparison. CI runs regenerate + `git diff --exit-code` as well, so the two cannot disagree.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { collectConsoleRoutes } from "../../../scripts/lib/console-routes.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "../../..");
const OUT_REL = "packages/core/routing/routes_gen.go";
const OUT = resolve(REPO, OUT_REL);

/** One route as the generator emits it. */
export interface RouteConst {
	ident: string;
	pattern: string;
}

/**
 * `/[org]/~/jobs/[id]` → `OrgJobsID`. Parameters keep their name, the `~` marker is dropped
 * from the identifier (it is kept in the pattern), and `id` is spelled `ID` the way Go spells
 * it — a lint-clean identifier is what lets the generated file be gofmt- and lint-clean as
 * WRITTEN, which the CI gate (regenerate + diff) depends on.
 */
export function identFor(urlSegments: readonly string[]): string {
	return (
		"Route" +
		urlSegments
			.filter((s) => s !== "~")
			.map((s) => s.replace(/^\[|\]$/g, ""))
			.map((s) => (s === "id" ? "ID" : s))
			.map((s) =>
				s
					.split(/[^a-zA-Z0-9]+/)
					.filter(Boolean)
					.map((w) => (w === "ID" ? w : w.charAt(0).toUpperCase() + w.slice(1)))
					.join(""),
			)
			.join("")
	);
}

/**
 * The routes worth a constant: everything but a catch-all.
 *
 * A REDIRECT-ONLY page keeps its constant, and that is the interesting decision. `/[org]/[project]`
 * is a redirect — the console decides which tab a project lands on — and it is exactly the URL a
 * person should be sent to, precisely because the CLI must not hardcode that choice. Excluding it
 * would have left `alethia project get --open` picking a tab, which is the console's answer to
 * give and change.
 *
 * A CATCH-ALL has no single URL to build (`/dashboard/[[...rest]]` matches everything under it), so
 * it is dropped rather than emitted as a pattern `Expand` would refuse at run time.
 */
export function routeConsts(
	routes: readonly {
		route: string;
		urlSegments: readonly string[];
		isRedirectOnly: boolean;
	}[],
): RouteConst[] {
	const out: RouteConst[] = [];
	const seen = new Map<string, string>();
	for (const r of routes) {
		if (r.urlSegments.some((s) => s.startsWith("[[") || s.startsWith("[...")))
			continue;
		const ident = identFor(r.urlSegments);
		const prior = seen.get(ident);
		if (prior !== undefined) {
			throw new Error(
				`routes ${prior} and ${r.route} both render as ${ident} — the identifier rule has to distinguish them`,
			);
		}
		seen.set(ident, r.route);
		out.push({ ident, pattern: r.route });
	}
	if (out.length === 0) {
		throw new Error(
			"the route manifest yielded zero constants — refusing to emit a table every builder would fail to compile against",
		);
	}
	return out;
}

/** Renders the Go file, gofmt-clean as written. */
export function renderGo(consts: readonly RouteConst[]): string {
	const width = Math.max(...consts.map((c) => c.ident.length));
	const lines = consts.map(
		(c) => `\t${c.ident.padEnd(width)} = ${JSON.stringify(c.pattern)}`,
	);
	const list = consts.map((c) => `\t${c.ident},`);
	return [
		"// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>",
		"// SPDX-License-Identifier: AGPL-3.0-only",
		"",
		"// Code generated by apps/console/scripts/gen-go-routes.ts; DO NOT EDIT.",
		"// Regenerate with: pnpm -C apps/console run gen:go-routes",
		"//",
		"// Source of truth: apps/console/app/(private)/** through scripts/lib/console-routes.mjs, the",
		"// same manifest the console's conformance guards read. A route the console renames or removes",
		"// disappears from here, and every builder over it stops compiling.",
		"",
		"package routing",
		"",
		"// The console's private route patterns, as Next.js spells them.",
		"const (",
		...lines,
		")",
		"",
		`// Routes is every pattern above, in manifest order — ${consts.length} routes.`,
		"var Routes = []string{",
		...list,
		"}",
		"",
	].join("\n");
}

function main(): void {
	const checkOnly = process.argv.includes("--check");
	// `collectConsoleRoutes` is JSDoc-typed in a `.mjs`, so `routes` arrives as `object[]` — enough
	// for the JS consumers, not enough to hand to a typed function. Narrowed here, once, rather than
	// widening `routeConsts`, which is the half worth type-checking.
	const manifest = collectConsoleRoutes({ repoRoot: REPO }) as {
		routes: { route: string; urlSegments: string[]; isRedirectOnly: boolean }[];
	};
	const consts = routeConsts(manifest.routes);
	const go = renderGo(consts);

	if (checkOnly) {
		let committed = "";
		try {
			committed = readFileSync(OUT, "utf8");
		} catch {
			console.error(
				`::error::${OUT_REL} does not exist — run 'pnpm -C apps/console run gen:go-routes' and commit.`,
			);
			process.exit(1);
		}
		if (committed !== go) {
			console.error(
				`::error::${OUT_REL} is stale against the console's route tree (${consts.length} routes) — run 'pnpm -C apps/console run gen:go-routes' and commit. A route the CLI builds a link over may have moved.`,
			);
			process.exit(1);
		}
		console.log(
			`route parity: ${consts.length} routes, ${OUT_REL} matches the console's tree`,
		);
		return;
	}

	writeFileSync(OUT, go, "utf8");
	console.log(`wrote ${OUT_REL} — ${consts.length} routes`);
}

if (
	process.argv[1] !== undefined &&
	import.meta.url === pathToFileURL(process.argv[1]).href
) {
	main();
}
