{{- if and (eq .Provider "aws") .EnableKarpenter }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: oci://public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: "0.37.0"
    helm:
      values: |
        fullnameOverride: karpenter
        serviceAccount:
          create: true
          name: karpenter
        replicas: 2
        settings:
          clusterName: {{ .ClusterName }}
          clusterEndpoint: {{ .ClusterEndpoint }}
          interruptionQueue: {{ .KarpenterQueueName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
{{- end }}
