// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Cross-language parity for the Kubernetes-version resolution — the Go half (#5314).
//
// The apply gate judges ResolveK8sVersion's answer; the console's compat surfaces judge
// apps/console/lib/compat/resolve.ts's. If the two resolved an unset version differently, the
// canvas would warn about one Kubernetes version while the gate refused (or passed) another. Go is
// the authority — this is what tofu receives — so it writes the fixture and
// apps/console/tests/lib/compat/k8s-version-resolution-parity.test.ts proves the TS mirror agrees.
//
// Regenerate:  UPDATE_FIXTURES=1 go test ./cloud/ -run TestK8sVersionResolutionParityFixture

package cloud

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

const k8sResolutionFixture = "k8s_version_resolution.json"

// k8sResolutionCase is one (provider, config version) → resolved version answer.
type k8sResolutionCase struct {
	Provider      string `json:"provider"`
	ConfigVersion string `json:"config_version"`
	Want          string `json:"want"`
}

// k8sResolutionFile is the fixture's wire shape.
type k8sResolutionFile struct {
	Doc   string              `json:"_doc"`
	Cases []k8sResolutionCase `json:"cases"`
}

// buildK8sResolution computes Go's answer for every catalogued cloud, unset and pinned, plus a
// provider the catalog does not know.
func buildK8sResolution() k8sResolutionFile {
	out := k8sResolutionFile{Doc: "GENERATED by packages/core/cloud/k8s_version_resolution_parity_test.go. DO NOT EDIT. " +
		"Regenerate: UPDATE_FIXTURES=1 go test ./cloud/ -run TestK8sVersionResolutionParityFixture."}
	for _, provider := range []string{"aws", "gcp", "azure", "alibaba", "hetzner", "no-such-cloud"} {
		for _, v := range []string{"", "1.30", "1.34.2"} {
			out.Cases = append(out.Cases, k8sResolutionCase{Provider: provider, ConfigVersion: v, Want: ResolveK8sVersion(provider, v)})
		}
	}
	return out
}

// TestK8sVersionResolutionParityFixture freezes Go's resolution, or regenerates it under
// UPDATE_FIXTURES=1. A catalog default bump changes the fixture, which is the point: the console
// test then proves its generated DEFAULT_K8S_VERSION moved with it.
func TestK8sVersionResolutionParityFixture(t *testing.T) {
	built := buildK8sResolution()
	resolvedDefaults := 0
	for _, c := range built.Cases {
		if c.ConfigVersion == "" && c.Want != "" {
			resolvedDefaults++
		}
	}
	// Vacuity: a fixture in which no unset version resolved would pin nothing #5314 is about.
	if resolvedDefaults == 0 {
		t.Fatal("no unset version resolved to a default — the fixture would be vacuous")
	}

	wire, err := json.MarshalIndent(built, "", "\t")
	if err != nil {
		t.Fatalf("marshal fixture: %v", err)
	}
	wire = append(wire, '\n')

	path := filepath.Join("testdata", k8sResolutionFixture)
	if os.Getenv("UPDATE_FIXTURES") == "1" {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		if err := os.WriteFile(path, wire, 0o644); err != nil {
			t.Fatalf("write fixture: %v", err)
		}
		return
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s (regenerate with UPDATE_FIXTURES=1): %v", path, err)
	}
	if !bytes.Equal(got, wire) {
		t.Fatalf("%s is stale against ResolveK8sVersion — regenerate with UPDATE_FIXTURES=1 go test ./cloud/ -run TestK8sVersionResolutionParityFixture", path)
	}
}
