#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
# SPDX-License-Identifier: AGPL-3.0-only
#
# programme-fetch.sh — capture the LIVE board state that PROGRAMME.md's status half cannot derive
# from the tree, as one committed JSON file.
#
# WHY A SNAPSHOT AND NOT A DIRECT QUERY. `scripts/programme-rollup.mjs` is diff-gated on every PR.
# A diff gate whose input is a live GitHub query is flaky by construction — the same PR would be
# "stale" or "in sync" depending on whether somebody relabelled an issue in the meantime, and every
# PR's status would depend on the board. So the live read happens ONCE, in a cron, and is COMMITTED;
# the rollup then stays a deterministic function of files in the tree.
#
# WHY THIS FILE HAS NO LOGIC, AND NO --self-test. It is a pure `gh` transport: query, shape, write.
# Every judgement — what counts as blocked, whether a cited issue is closed, how staleness is
# reported — lives in the rollup, which IS self-tested against fixtures. That split is deliberate:
# the untestable part (the network) is kept trivial enough to read, and the part worth testing is
# kept offline. The same argument nightly-rollup.sh makes for its own derive/emit split.
#
# SECRETS: this writes variable and secret NAMES, never values. `gh variable list` returns values
# for variables (they are not secret) but we deliberately drop them anyway — the rollup only ever
# asks "is this gate wired?", and a committed file in a PUBLIC repo is the wrong place for even a
# non-secret role ARN. `gh secret list` cannot return values at all.
#
# Usage:  scripts/programme-fetch.sh [output-path]
#         GH_REPO=owner/repo scripts/programme-fetch.sh   # override the target repo
set -euo pipefail

OUT="${1:-docs/testing/programme-snapshot.json}"
REPO="${GH_REPO:-alethialabs-io/alethialabs}"

command -v gh >/dev/null || {
	echo "programme-fetch: gh is required" >&2
	exit 3
}
command -v jq >/dev/null || {
	echo "programme-fetch: jq is required" >&2
	exit 3
}

# `derived_at` is the ONLY timestamp in the whole mechanism, and it lives here rather than in
# PROGRAMME.md's rendered text on purpose: a timestamp inside a diff-gated region would make every
# PR stale the moment it was opened. The rollup reads it to report staleness.
derived_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Open issues. `--limit 500` is well above the ~40 the board carries; if it is ever hit the count
# below makes the truncation visible rather than silently dropping the tail.
issues="$(gh issue list --repo "$REPO" --state open --limit 500 \
	--json number,title,labels,createdAt,updatedAt \
	--jq '[.[] | {number, title, labels: [.labels[].name], createdAt, updatedAt}]')"

# Issues the tree CITES must be resolvable even when closed — that is the whole point of the
# stale-citation check — so closed issues are captured too, most-recently-updated first.
closed="$(gh issue list --repo "$REPO" --state closed --limit 500 \
	--json number,title,labels \
	--jq '[.[] | {number, title, labels: [.labels[].name]}]')"

# Gate reality: NAMES ONLY (see the header).
vars="$(gh variable list --repo "$REPO" --json name --jq '[.[].name]' 2>/dev/null || echo '[]')"
secrets="$(gh secret list --repo "$REPO" --json name --jq '[.[].name]' 2>/dev/null || echo '[]')"

jq -n \
	--arg derived_at "$derived_at" \
	--arg repo "$REPO" \
	--argjson open_issues "$issues" \
	--argjson closed_issues "$closed" \
	--argjson variables "$vars" \
	--argjson secrets "$secrets" \
	'{
    "_doc": "GENERATED by scripts/programme-fetch.sh. Do not edit. The LIVE board state PROGRAMME.md cannot derive from the tree. Variable and secret NAMES only — never values.",
    derived_at: $derived_at,
    repo: $repo,
    open_issues: $open_issues,
    closed_issues: $closed_issues,
    variables: $variables,
    secrets: $secrets
  }' >"$OUT"

printf 'programme-fetch: wrote %s — %s open / %s closed issues, %s variables, %s secrets\n' \
	"$OUT" \
	"$(jq '.open_issues | length' "$OUT")" \
	"$(jq '.closed_issues | length' "$OUT")" \
	"$(jq '.variables | length' "$OUT")" \
	"$(jq '.secrets | length' "$OUT")"
