// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Integration (real Postgres): the authz_activity_log retention GC + its keyset read index.
//
// Proves two things a mocked db can't:
//   1. public.gc_authz_activity_log(age, limit) deletes ONLY rows older than the window (oldest
//      first, bounded), returns the deleted count, and is idempotent (a second pass deletes 0).
//   2. the hot read `WHERE org_id = ? ORDER BY id DESC LIMIT n` is served by an INDEX scan on the
//      (org_id, id DESC) composite — not a seq scan + sort. The composite lands via Drizzle
//      migration 0086 (generated by the orchestrator); until then this test creates it (IF NOT
//      EXISTS) so the plan assertion is meaningful on a freshly-migrated DB.

import { randomUUID } from "node:crypto";
import { and, desc, eq, sql } from "drizzle-orm";
import { afterAll, beforeAll, expect, it } from "vitest";
import { getServiceDb } from "@/lib/db";
import { authzActivityLog } from "@/lib/db/schema";
import { gcAuthzActivityLog } from "@/lib/reconcile/gc";
import { describeIfDb } from "./db";

describeIfDb("authz_activity_log retention GC + keyset index", () => {
	const orgId = randomUUID();
	const actorId = randomUUID();
	const OLD_ROWS = 40; // backdated > 365d — should be GC'd
	const RECENT_ROWS = 15; // recent — should survive

	beforeAll(async () => {
		const db = getServiceDb();
		// The composite read index (idx_authz_activity_org_id_desc) is created by migration 0086,
		// which the integration harness applies before this suite runs — so the EXPLAIN assertion
		// below exercises the real migrated index, not a test-local one.

		// Backdated rows (older than the 365d window): ts = now - 400d.
		const oldRows = Array.from({ length: OLD_ROWS }, (_, i) => ({
			org_id: orgId,
			actor_id: actorId,
			action: `org:read:old-${i}`,
			resource_type: "project",
			resource_id: null,
			decision: true,
			reason: "seed-old",
			ts: sql`now() - interval '400 days'`,
		}));
		// Recent rows (inside the window): ts = now.
		const recentRows = Array.from({ length: RECENT_ROWS }, (_, i) => ({
			org_id: orgId,
			actor_id: actorId,
			action: `org:read:recent-${i}`,
			resource_type: "project",
			resource_id: null,
			decision: true,
			reason: "seed-recent",
		}));
		await db.insert(authzActivityLog).values([...oldRows, ...recentRows]);

		// Noise rows for OTHER orgs so the table is large and `org_id = ?` is a selective
		// fraction — that's the regime where the composite index beats a seq scan + sort (on a
		// ~55-row table the planner would correctly seq-scan; the index earns its keep at scale).
		const NOISE = 3000;
		const noise = Array.from({ length: NOISE }, (_, i) => ({
			org_id: randomUUID(),
			actor_id: actorId,
			action: `noise-${i}`,
			resource_type: "project",
			resource_id: null,
			decision: i % 2 === 0,
			reason: "seed-noise",
		}));
		// Batch the inserts to stay under the bind-parameter cap.
		for (let i = 0; i < noise.length; i += 500) {
			await db.insert(authzActivityLog).values(noise.slice(i, i + 500));
		}

		// Give the planner realistic stats so the composite index is chosen over a seq scan.
		await db.execute(sql`ANALYZE public.authz_activity_log`);
	});

	afterAll(async () => {
		const db = getServiceDb();
		await db.delete(authzActivityLog).where(eq(authzActivityLog.org_id, orgId));
		// Remove the other-org noise rows too, keyed by their reason marker, so the suite is hermetic.
		await db
			.delete(authzActivityLog)
			.where(eq(authzActivityLog.reason, "seed-noise"));
	});

	/** Count this org's remaining rows. */
	async function countForOrg(): Promise<number> {
		const [row] = await getServiceDb()
			.select({ n: sql<number>`count(*)::int` })
			.from(authzActivityLog)
			.where(eq(authzActivityLog.org_id, orgId));
		return row.n;
	}

	it("deletes only rows older than the 365d window and returns the deleted count", async () => {
		expect(await countForOrg()).toBe(OLD_ROWS + RECENT_ROWS);

		// Call the programmable directly (the same SQL the reconcile wrapper runs).
		const [res] = await getServiceDb().execute<{ deleted: number }>(
			sql`select public.gc_authz_activity_log(make_interval(days => 365), 5000) as deleted`,
		);
		expect(Number(res.deleted)).toBe(OLD_ROWS);

		// Old gone, recent kept.
		expect(await countForOrg()).toBe(RECENT_ROWS);
		const [survivors] = await getServiceDb()
			.select({ n: sql<number>`count(*)::int` })
			.from(authzActivityLog)
			.where(
				and(
					eq(authzActivityLog.org_id, orgId),
					eq(authzActivityLog.reason, "seed-old"),
				),
			);
		expect(survivors.n).toBe(0);
	});

	it("is idempotent — a second pass deletes 0", async () => {
		const [res] = await getServiceDb().execute<{ deleted: number }>(
			sql`select public.gc_authz_activity_log(make_interval(days => 365), 5000) as deleted`,
		);
		expect(Number(res.deleted)).toBe(0);
		expect(await countForOrg()).toBe(RECENT_ROWS);
	});

	it("wrapper gcAuthzActivityLog runs and returns a deleted count", async () => {
		const { deleted } = await gcAuthzActivityLog(getServiceDb());
		expect(deleted).toBe(0); // nothing old remains after the first test
	});

	it("keyset read (WHERE org_id ORDER BY id DESC LIMIT) uses the composite index, not a seq scan", async () => {
		const plan = await getServiceDb().execute<{ "QUERY PLAN": string }>(
			sql`EXPLAIN (COSTS OFF) SELECT id FROM public.authz_activity_log WHERE org_id = ${orgId} ORDER BY id DESC LIMIT 50`,
		);
		const text = plan.map((r) => r["QUERY PLAN"]).join("\n");
		// Plan must scan via the composite index and must NOT seq-scan authz_activity_log.
		expect(text).toContain("idx_authz_activity_org_id_desc");
		expect(text).not.toMatch(/Seq Scan on authz_activity_log/);
	});
});
