// SPDX-FileCopyrightText: 2026 Alethia Labs OÜ <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// GENERATED by scripts/gen-integrations.mjs from packages/core/categories/catalog.json.
// Do NOT edit by hand — edit the manifest and run `pnpm -F console gen:integrations`.

/** Categories that support pluggable (non-cloud-native) provider backends. */
export const INTEGRATION_CATEGORIES = ["dns", "secrets", "registry", "observability"] as const;
export type IntegrationCategory = (typeof INTEGRATION_CATEGORIES)[number];

/** A single field collected for a credential or a component's provider_config. */
export interface IntegrationField {
	key: string;
	label: string;
	type: "text" | "password" | "boolean" | "select";
	secret?: boolean;
	required?: boolean;
	help?: string;
	default?: string | boolean;
	options?: string[];
}

export interface IntegrationProviderMeta {
	category: IntegrationCategory;
	slug: string;
	name: string;
	description: string;
	organization: string;
	icon_url: string;
	docs_url?: string;
	status: "active" | "coming_soon";
	sort_order: number;
	modulePath: string;
	credentialFields: IntegrationField[];
	providerConfigFields: IntegrationField[];
}

export const INTEGRATION_PROVIDERS: IntegrationProviderMeta[] = [
	{
		category: "dns",
		slug: "cloudflare",
		name: "Cloudflare",
		description: "Manage DNS records and certificates on Cloudflare instead of the cluster cloud's native DNS.",
		organization: "Cloudflare, Inc.",
		icon_url: "/connectors/cloudflare.svg",
		docs_url: "https://developers.cloudflare.com/dns/",
		status: "active",
		sort_order: 30,
		modulePath: "categories/dns/cloudflare",
		credentialFields: [{"key":"api_token","label":"API Token","type":"password","secret":true,"required":true,"help":"A scoped Cloudflare API token with Zone:DNS:Edit permission."}],
		providerConfigFields: [{"key":"zone_id","label":"Zone ID","type":"text","required":true,"help":"The Cloudflare Zone ID for the domain."},{"key":"proxied","label":"Proxy records through Cloudflare","type":"boolean","default":false}],
	},
	{
		category: "secrets",
		slug: "vault",
		name: "HashiCorp Vault",
		description: "Store and read application secrets from a HashiCorp Vault instance.",
		organization: "HashiCorp",
		icon_url: "/connectors/vault.svg",
		docs_url: "https://developer.hashicorp.com/vault/docs",
		status: "active",
		sort_order: 40,
		modulePath: "categories/secrets/vault",
		credentialFields: [{"key":"address","label":"Vault Address","type":"text","secret":false,"required":true,"help":"Base URL of the Vault server, e.g. https://vault.example.com:8200"},{"key":"token","label":"Vault Token","type":"password","secret":true,"required":true}],
		providerConfigFields: [{"key":"mount_path","label":"KV Mount Path","type":"text","default":"secret","required":true},{"key":"kv_version","label":"KV Version","type":"select","options":["1","2"],"default":"2"}],
	},
	{
		category: "registry",
		slug: "dockerhub",
		name: "Docker Hub",
		description: "Use a Docker Hub repository as the container registry instead of the cloud-native one.",
		organization: "Docker, Inc.",
		icon_url: "/connectors/dockerhub.svg",
		docs_url: "https://docs.docker.com/docker-hub/",
		status: "active",
		sort_order: 50,
		modulePath: "categories/registry/dockerhub",
		credentialFields: [{"key":"username","label":"Username","type":"text","secret":false,"required":true},{"key":"access_token","label":"Access Token","type":"password","secret":true,"required":true,"help":"A Docker Hub personal access token (Account Settings → Security)."}],
		providerConfigFields: [{"key":"namespace","label":"Namespace / Organization","type":"text","required":false,"help":"Defaults to the username if left blank."}],
	},
	{
		category: "observability",
		slug: "datadog",
		name: "Datadog",
		description: "Ship cluster metrics, logs, and traces to Datadog.",
		organization: "Datadog, Inc.",
		icon_url: "/connectors/datadog.svg",
		docs_url: "https://docs.datadoghq.com/",
		status: "active",
		sort_order: 60,
		modulePath: "categories/observability/datadog",
		credentialFields: [{"key":"api_key","label":"API Key","type":"password","secret":true,"required":true},{"key":"app_key","label":"Application Key","type":"password","secret":true,"required":true}],
		providerConfigFields: [{"key":"site","label":"Datadog Site","type":"select","options":["datadoghq.com","datadoghq.eu","us3.datadoghq.com","us5.datadoghq.com","ap1.datadoghq.com"],"default":"datadoghq.com"}],
	},
	{
		category: "observability",
		slug: "grafana",
		name: "Grafana Cloud",
		description: "Remote-write metrics to Grafana Cloud's managed Prometheus.",
		organization: "Grafana Labs",
		icon_url: "/connectors/grafana.svg",
		docs_url: "https://grafana.com/docs/grafana-cloud/",
		status: "active",
		sort_order: 70,
		modulePath: "categories/observability/grafana",
		credentialFields: [{"key":"instance_id","label":"Instance ID / Username","type":"text","secret":false,"required":true},{"key":"api_token","label":"API Token","type":"password","secret":true,"required":true}],
		providerConfigFields: [{"key":"remote_write_url","label":"Remote Write URL","type":"text","required":true,"help":"The Grafana Cloud Prometheus remote_write endpoint."}],
	},
	{
		category: "observability",
		slug: "prometheus",
		name: "Prometheus",
		description: "Install in-cluster Prometheus, optionally remote-writing to an external store.",
		organization: "Prometheus Authors",
		icon_url: "/connectors/prometheus.svg",
		docs_url: "https://prometheus.io/docs/",
		status: "active",
		sort_order: 80,
		modulePath: "categories/observability/prometheus",
		credentialFields: [{"key":"remote_write_username","label":"Remote Write Username","type":"text","secret":false,"required":false},{"key":"remote_write_password","label":"Remote Write Password","type":"password","secret":true,"required":false}],
		providerConfigFields: [{"key":"remote_write_url","label":"Remote Write URL","type":"text","required":false,"help":"Optional external Prometheus-compatible remote_write endpoint."},{"key":"retention_days","label":"Local Retention (days)","type":"text","default":"15"}],
	},
];

/** Pluggable providers offered for a category (excludes the cloud-native default). */
export function getProvidersForCategory(category: IntegrationCategory): IntegrationProviderMeta[] {
	return INTEGRATION_PROVIDERS.filter((p) => p.category === category);
}

/** Look up a provider by (category, slug), or undefined for the native default. */
export function getIntegrationProvider(
	category: string,
	slug: string | null | undefined,
): IntegrationProviderMeta | undefined {
	if (!slug || slug === "native") return undefined;
	return INTEGRATION_PROVIDERS.find((p) => p.category === category && p.slug === slug);
}

/** Look up a provider by slug alone (slugs are globally unique in the catalog). */
export function getIntegrationProviderBySlug(slug: string): IntegrationProviderMeta | undefined {
	return INTEGRATION_PROVIDERS.find((p) => p.slug === slug);
}
