---
project_name: "igxadp"
environment: "stg"
region: 'eu-west-1'
aws_account_id: '722377226063'
terraform_ver: "1.11.4"
# Source repository for the environment template
env_template_repo: "git@github.com:itgix/adp-tf-envtempl-standard.git"
env_template_repo_branch: "v1.2.7"
gitops_template_repo: "git@github.com:itgix/adp-k8s-templ-argoinfrasvcs.git"
gitops_template_repo_branch: "v1.2.11"
# gitops destination repo - where argocd will be pointed to, should be a http/s as this is the protocol Argo expects
gitops_destination_repo: "https://gitlab.itgix.com/rnd/app-platform/demo-environments/demo-argocd-services-client"
# Destination git repository for the environment that will be bootstrapped from template
gitops_argo_access_token: "glpat-yourtoken-here"

# Same as the gitops repo but for applications
applications_template_repo: "git@github.com:itgix/adp-k8s-templ-argoappsdemo.git"
applications_destination_repo: "https://gitlab.itgix.com/rnd/app-platform/demo-environments/demo-applications-client"
applications_argo_access_token: "glpat-yourtoken-here"

env_git_repo: "git@gitlab.itgix.com:rnd/app-platform/demo-environments/demo-client.git"
#argocd repo


#Backstage Installation
backstage_enabled: true

#Optional
backstage_image_registry: "709825985650.dkr.ecr.us-east-1.amazonaws.com"
backstage_image_repository: "itgix/itgix-adp-backstage"
backstage_image_tag: "v1.2.2"

# Node auto-scaling
enable_karpenter: true

# Workload auto-scaling
enabled_metrics_server: true
enable_vpa: true

# Terraform optional customizations
# VPC module
vpc_cidr: "10.51.0.0/16"
allowed_cidr_blocks:
  - "10.50.0.0/16"
  - "10.51.0.0/16"

# DNS
dns_hosted_zone: "Z2INQZ6AA9H9SI"
dns_main_domain: "itgix.eu"

#Automatically generate certificate
acm_certificate_enable: false

# Database related variables
rds_scaling_config:
  min_capacity: 0.5

# EKS related variable
# EKS config map users when IAM users are used.
eks_aws_auth_users:
  - username: "ytodorov"
    groups:
      - "system:masters"
  - username: "mvukadinoff"
    groups:
      - "system:masters"
  - username: "tkazanova"
    groups:
      - "system:masters"
  - username: "sracheva"
    groups:
      - "system:masters"
  - username: "htonev"
    groups:
      - "system:masters"
eks_aws_users_path: "/users/"

# elasticache redis
create_elasticache_redis: false

custom_secrets:
# Secrets needed for Backstage - warning those will end up the repository , use only as initial values and change afterwards !!!
  - secret_name: "backstage-secret-github-client-id"
    manual: true
    value: ""
  - secret_name: "backstage-secret-github-client-secret"
    manual: true
    value: ""
  - secret_name: "backstage-secret-github-token"
    manual: true
    value: ""
  - secret_name: "backstage-secret-gitlab-token"
    manual: true
    value: ""
  - secret_name: "backstage-secret-auth-secret"
    manual: true
    value: ""
  - secret_name: "backstage-postgres-password"
    length: 32
    special: true
    override_special: "$_+"
# Secrets needed for the AI profile
  - secret_name: "qdrant-env-secret"
    length:   20
    special:  false


#DynamoDB
ddb_create: false
ddb_table_configuration: 
  - table_name_suffix: "dynamodb-table"
    hash_key:          "Id"
    range_key:         "version"
    hash_key_type:     "S"
    range_key_type:    "N"
  


ddb_global_create: false
ddb_global_table_configuration: 
  - table_type:         "global"
    table_name_suffix:  "dynamodb-global-table"
    replicas:           ["us-east-2"]
    dynamodb_attributes: 
      - name: "Id"
        type: "S"
      
      - name: "version"
        type: "N"
    hash_key:                      "Id"
    range_key:                     "version"
    hash_key_type:                 "S"
    range_key_type:                "N"
    enable_point_in_time_recovery:  true
