// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by apps/console/scripts/gen-go-routes.ts; DO NOT EDIT.
// Regenerate with: pnpm -C apps/console run gen:go-routes
//
// Source of truth: apps/console/app/(private)/** through scripts/lib/console-routes.mjs, the
// same manifest the console's conformance guards read. A route the console renames or removes
// disappears from here, and every builder over it stops compiling.

package routing

// The console's private route patterns, as Next.js spells them.
const (
	RouteOrgProjectArchitecture     = "/[org]/[project]/architecture"
	RouteOrgProjectClusters         = "/[org]/[project]/clusters"
	RouteOrgProjectEnvironments     = "/[org]/[project]/environments"
	RouteOrgProjectJobs             = "/[org]/[project]/jobs"
	RouteOrgProject                 = "/[org]/[project]"
	RouteOrgProjectSettingsAccess   = "/[org]/[project]/settings/access"
	RouteOrgProjectSettingsActivity = "/[org]/[project]/settings/activity"
	RouteOrgProjectSettingsGeneral  = "/[org]/[project]/settings/general"
	RouteOrgProjectSettings         = "/[org]/[project]/settings"
	RouteOrgProjectSettingsPreview  = "/[org]/[project]/settings/preview"
	RouteOrgProjectUsage            = "/[org]/[project]/usage"
	RouteOrg                        = "/[org]"
	RouteOrgAlerts                  = "/[org]/~/alerts"
	RouteOrgClusters                = "/[org]/~/clusters"
	RouteOrgConnectors              = "/[org]/~/connectors"
	RouteOrgEvidence                = "/[org]/~/evidence"
	RouteOrgJobsID                  = "/[org]/~/jobs/[id]"
	RouteOrgJobs                    = "/[org]/~/jobs"
	RouteOrgNew                     = "/[org]/~/new"
	RouteOrgRunners                 = "/[org]/~/runners"
	RouteOrgSettingsAccess          = "/[org]/~/settings/access"
	RouteOrgSettingsActivity        = "/[org]/~/settings/activity"
	RouteOrgSettingsBillingInvoices = "/[org]/~/settings/billing/invoices"
	RouteOrgSettingsBilling         = "/[org]/~/settings/billing"
	RouteOrgSettingsClassification  = "/[org]/~/settings/classification"
	RouteOrgSettingsGeneral         = "/[org]/~/settings/general"
	RouteOrgSettingsMembers         = "/[org]/~/settings/members"
	RouteOrgSettings                = "/[org]/~/settings"
	RouteOrgSettingsRoles           = "/[org]/~/settings/roles"
	RouteOrgSettingsSso             = "/[org]/~/settings/sso"
	RouteOrgSettingsTeams           = "/[org]/~/settings/teams"
	RouteOrgSupportAbuse            = "/[org]/~/support/abuse"
	RouteOrgSupportAsk              = "/[org]/~/support/ask"
	RouteOrgSupportCasesID          = "/[org]/~/support/cases/[id]"
	RouteOrgSupportMyCases          = "/[org]/~/support/my-cases"
	RouteOrgSupport                 = "/[org]/~/support"
	RouteOrgSupportSubmit           = "/[org]/~/support/submit"
	RouteOrgUsage                   = "/[org]/~/usage"
	RouteCliLogin                   = "/cli/login"
)

// Routes is every pattern above, in manifest order — 39 routes.
var Routes = []string{
	RouteOrgProjectArchitecture,
	RouteOrgProjectClusters,
	RouteOrgProjectEnvironments,
	RouteOrgProjectJobs,
	RouteOrgProject,
	RouteOrgProjectSettingsAccess,
	RouteOrgProjectSettingsActivity,
	RouteOrgProjectSettingsGeneral,
	RouteOrgProjectSettings,
	RouteOrgProjectSettingsPreview,
	RouteOrgProjectUsage,
	RouteOrg,
	RouteOrgAlerts,
	RouteOrgClusters,
	RouteOrgConnectors,
	RouteOrgEvidence,
	RouteOrgJobsID,
	RouteOrgJobs,
	RouteOrgNew,
	RouteOrgRunners,
	RouteOrgSettingsAccess,
	RouteOrgSettingsActivity,
	RouteOrgSettingsBillingInvoices,
	RouteOrgSettingsBilling,
	RouteOrgSettingsClassification,
	RouteOrgSettingsGeneral,
	RouteOrgSettingsMembers,
	RouteOrgSettings,
	RouteOrgSettingsRoles,
	RouteOrgSettingsSso,
	RouteOrgSettingsTeams,
	RouteOrgSupportAbuse,
	RouteOrgSupportAsk,
	RouteOrgSupportCasesID,
	RouteOrgSupportMyCases,
	RouteOrgSupport,
	RouteOrgSupportSubmit,
	RouteOrgUsage,
	RouteCliLogin,
}
