// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

import { z } from "zod";

import type { NodeKind } from "@/components/design-project/canvas/graph/types";
import MANIFEST from "@/lib/cloud-providers/generated/template-knobs.json";

/**
 * The template-knob manifest — every variable the five project templates declare, which canvas
 * component it belongs to, and whether a user can actually set it.
 *
 * Generated by `apps/console/scripts/gen-template-knobs.mjs` from the templates and the Go providers,
 * diff-gated in CI, and parsed HERE rather than trusted. The parse is the point: a generated file is
 * still a file, and `import … from "*.json"` gives TypeScript a structural type derived from
 * whatever bytes happen to be on disk — a manifest truncated by a bad merge would type-check
 * perfectly and hand the card UI a `knobs` array of the wrong shape at runtime. `z.parse` at module
 * load turns that into a startup error naming the field, which is the only failure mode a UI can act
 * on.
 */
const KnobSchema = z.object({
	/** The template this knob belongs to: `aws`, `gcp`, `azure`, `alibaba`, `hetzner`. */
	cloud: z.string().min(1),
	/** A canvas `NodeKind`, or `platform` for a knob that belongs to no single component. */
	component: z.string().min(1),
	/** The tofu variable name, or — when `itemScope` is set — the attribute name on that variable. */
	name: z.string().min(1),
	/** The coarse type a control is picked from. `any` means the template declares no shape. */
	kind: z.enum(["string", "number", "bool", "list", "map", "object", "any"]),
	/** The full tofu type expression, for a control that wants to show what it accepts. */
	typeExpr: z.string(),
	/** The template's own default, when it declares one that is a literal. Absent when the variable is
	 * required, and absent when the default is an expression — a raw expression rendered as a value
	 * would be a value that is wrong. */
	default: z.unknown().optional(),
	required: z.boolean(),
	description: z.string(),
	sensitive: z.boolean(),
	/** `<path>:<line>` of the declaration, so a knob can be traced to the template that makes it. */
	declaredAt: z.string(),
	/** The template directories whose resource or module arguments consume it. EMPTY means the knob is
	 * declared and read by nothing — the `gke_spot` shape, which `check:template-knobs` fails on. */
	readBy: z.array(z.string()),
	/** A `provider_config` merge lands on it: a root-shaped merge for a root variable, an item-shaped
	 * one for an attribute of the variable the component is modelled as one entry of. */
	reachable: z.boolean(),
	/** The provider ALWAYS emits this key, so merge-if-absent can never reach it. */
	ownedByProvider: z.boolean(),
	/** A typed Go field already carries it, so the canvas collects it somewhere else and a generic
	 * control would be a second, silently-losing writer of the same value. */
	typed: z.boolean(),
	/** The root variable this knob is an ATTRIBUTE of (`sqs_queues`), when it is not a root variable
	 * itself. Its presence is what tells a caller the value lands on one entry of a map/list. */
	itemScope: z.string().optional(),
});

const ManifestSchema = z.object({
	generatedBy: z.string(),
	clouds: z.array(z.string()),
	counts: z.record(
		z.string(),
		z.object({ declared: z.number(), reachable: z.number(), settable: z.number(), dead: z.number() }),
	),
	knobs: z.array(KnobSchema),
});

/** One knob of one cloud's template. */
export type TemplateKnob = z.infer<typeof KnobSchema>;

/** The parsed manifest. Parsed once, at module load, so a malformed file fails loudly and early
 * rather than at the moment a user opens a card. */
export const TEMPLATE_KNOBS = ManifestSchema.parse(MANIFEST);

/**
 * The knobs a card may OFFER for one component on one cloud.
 *
 * Three filters, and each one removes a control that would lie to the user:
 *
 *   · `reachable` — a `provider_config` key that no merge lands on never reaches tofu. The control
 *     would save cleanly and change nothing.
 *   · `!ownedByProvider` — the provider writes this key unconditionally, and the merge is
 *     merge-if-absent, so the user's value loses every time. Silently.
 *   · `!typed` — the canvas already collects this value through a typed field. A generic control
 *     beside it is a second writer of one value, and which one wins is an implementation detail of
 *     the merge rather than anything a user could predict.
 *
 * Sorted by name so a card's controls do not reorder when the generator's file order changes.
 */
export function knobsFor(cloud: string, kind: NodeKind): TemplateKnob[] {
	return TEMPLATE_KNOBS.knobs
		.filter((k) => k.cloud === cloud && k.component === kind && k.reachable && !k.ownedByProvider && !k.typed)
		.sort((a, b) => a.name.localeCompare(b.name));
}
