// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

import { z } from "zod";

import type { NodeKind } from "@/components/design-project/canvas/graph/types";
import MANIFEST from "@/lib/cloud-providers/generated/template-knobs.json";

/**
 * The template-knob manifest — every variable the five project templates declare, which canvas
 * component it belongs to, and whether a user can actually set it.
 *
 * Generated by `apps/console/scripts/gen-template-knobs.mjs` from the templates and the Go providers,
 * diff-gated in CI, and parsed HERE rather than trusted. The parse is the point: a generated file is
 * still a file, and `import … from "*.json"` gives TypeScript a structural type derived from
 * whatever bytes happen to be on disk — a manifest truncated by a bad merge would type-check
 * perfectly and hand the card UI a `knobs` array of the wrong shape at runtime. `z.parse` at module
 * load turns that into a startup error naming the field, which is the only failure mode a UI can act
 * on.
 */
const KnobSchema = z.object({
	/** The template this knob belongs to: `aws`, `gcp`, `azure`, `alibaba`, `hetzner`. */
	cloud: z.string().min(1),
	/** A canvas `NodeKind`, or `platform` for a knob that belongs to no single component. */
	component: z.string().min(1),
	/** The tofu variable name, or — when `itemScope` is set — the attribute name on that variable. */
	name: z.string().min(1),
	/** The coarse type a control is picked from. `any` means the template declares no shape. */
	kind: z.enum(["string", "number", "bool", "list", "map", "object", "any"]),
	/** The full tofu type expression, for a control that wants to show what it accepts. */
	typeExpr: z.string(),
	/** The template's own default, when it declares one that is a literal. Absent when the variable is
	 * required, and absent when the default is an expression — a raw expression rendered as a value
	 * would be a value that is wrong. */
	default: z.unknown().optional(),
	required: z.boolean(),
	description: z.string(),
	sensitive: z.boolean(),
	/** `<path>:<line>` of the declaration, so a knob can be traced to the template that makes it. */
	declaredAt: z.string(),
	/** The template directories whose resource or module arguments consume it. EMPTY means the knob is
	 * declared and read by nothing — the `gke_spot` shape, which `check:template-knobs` fails on. */
	readBy: z.array(z.string()),
	/** An `output` block references it — the BROUGHT-resource contract (#4531): the caller supplies
	 * something they own, the template creates nothing and echoes the id back. The one shape where an
	 * empty `readBy` is correct rather than a knob that does nothing. */
	reportedByOutput: z.boolean(),
	/** Recorded under `ceiling:` in the knob ledger: declared and reachable, but the PROVIDER cannot
	 * honour it — nothing on that cloud could read it (#4320). Never offered; the canvas gates the
	 * matching typed control with a reason instead (e.g. Managed TLS on Alibaba). */
	ceiling: z.boolean(),
	/** A `provider_config` merge lands on it: a root-shaped merge for a root variable, an item-shaped
	 * one for an attribute of the variable the component is modelled as one entry of. */
	reachable: z.boolean(),
	/** The provider ALWAYS emits this key, so merge-if-absent can never reach it. */
	ownedByProvider: z.boolean(),
	/** A typed Go field already carries it, so the canvas collects it somewhere else and a generic
	 * control would be a second, silently-losing writer of the same value. */
	typed: z.boolean(),
	/** The root variable this knob is an ATTRIBUTE of (`sqs_queues`), when it is not a root variable
	 * itself. Its presence is what tells a caller the value lands on one entry of a map/list. */
	itemScope: z.string().optional(),
});

const ManifestSchema = z.object({
	generatedBy: z.string(),
	clouds: z.array(z.string()),
	counts: z.record(
		z.string(),
		z.object({ declared: z.number(), reachable: z.number(), settable: z.number(), dead: z.number() }),
	),
	knobs: z.array(KnobSchema),
});

/** One knob of one cloud's template. */
export type TemplateKnob = z.infer<typeof KnobSchema>;

/** The parsed manifest. Parsed once, at module load, so a malformed file fails loudly and early
 * rather than at the moment a user opens a card. */
export const TEMPLATE_KNOBS = ManifestSchema.parse(MANIFEST);

/** Does anything the template builds — or reports — consume this knob? False is the dead shape. */
export function isRead(knob: TemplateKnob): boolean {
	return knob.readBy.length > 0 || knob.reportedByOutput;
}

/**
 * The knobs a card may OFFER for one component on one cloud.
 *
 * Five filters, and each one removes a control that would lie to the user:
 *
 *   · `reachable` — a `provider_config` key that no merge lands on never reaches tofu. The control
 *     would save cleanly and change nothing.
 *   · READ — some resource or module argument consumes it (`readBy`), or an output echoes it back as
 *     a brought resource's id (`reportedByOutput`). A knob that is declared, reachable and read by
 *     NOTHING is the `gke_spot` / `gke_log_retention_days` shape: it reaches tofu and changes nothing
 *     there either. `check:template-knobs` keeps that set recorded and shrinking; this is what stops
 *     the recorded ones being OFFERED in the meantime, so the class cannot come back as a control
 *     (#4320, maintainer ruling 2026-09-23).
 *   · `!ceiling` — the cloud itself cannot honour it (a recorded provider ceiling). Implied by READ
 *     today, since a ceiling is by definition read by nothing; stated separately so the guarantee
 *     does not rest on that coincidence.
 *   · `!ownedByProvider` — the provider writes this key unconditionally, and the merge is
 *     merge-if-absent, so the user's value loses every time. Silently.
 *   · `!typed` — the canvas already collects this value through a typed field. A generic control
 *     beside it is a second writer of one value, and which one wins is an implementation detail of
 *     the merge rather than anything a user could predict.
 *   · `!isCredentialKnob` — a password, a token, a secret's own value. What a user types into a
 *     knob is stored in plaintext in the component's `provider_config` JSONB, copied into every
 *     config snapshot and passed to tofu as a variable. A credential belongs in a secret store, so
 *     it is never offered — on the canvas or through the CLI (#5565). The canvas renders a note in
 *     its place instead (`withheldCredentialKnobs`), and the project write actions refuse the key.
 *
 * Sorted by name so a card's controls do not reorder when the generator's file order changes.
 */
export function knobsFor(cloud: string, kind: NodeKind): TemplateKnob[] {
	return offerableKnobs(TEMPLATE_KNOBS.knobs, cloud, kind);
}

/**
 * `knobsFor` over an explicit knob list — the filters themselves, separated from the committed
 * manifest so they can be pinned against fixtures. The live manifest cannot prove a filter works once
 * the templates stop containing the shape it removes: after #4320 no offerable-but-dead knob remains,
 * so a test over the manifest alone would pass the day the READ filter was deleted.
 */
export function offerableKnobs(knobs: readonly TemplateKnob[], cloud: string, kind: NodeKind): TemplateKnob[] {
	return knobs
		.filter(
			(k) =>
				k.cloud === cloud &&
				k.component === kind &&
				k.reachable &&
				isRead(k) &&
				!k.ceiling &&
				!k.ownedByProvider &&
				!k.typed &&
				!isCredentialKnob(k),
		)
		.sort((a, b) => a.name.localeCompare(b.name));
}

/** A credential word as a whole `_`-separated segment of a knob name. */
const CREDENTIAL_NAME =
	/(^|_)(password|passwd|passphrase|credentials?|token|secret_key|access_key|private_key|api_key|client_secret)(_|$)/;

/** A credential attribute declared inside a knob's type (`object({ password = … })`). */
const CREDENTIAL_ATTRIBUTE =
	/\b(password|passwd|passphrase|token|secret_key|access_key|private_key|api_key|client_secret)\s*=/;

/**
 * A key name in the one spelling the credential rule matches: trimmed, camelCase split into
 * snake_case, and lower-cased — so `dbPassword`, `DB_PASSWORD`, `Rds_Extra_Credentials` and
 * `rds_extra_credentials ` (trailing space) all read as the name they imitate. HCL names are
 * case-sensitive, so those spellings never reach tofu; they would still be stored in plaintext
 * JSONB, which is the thing being prevented.
 */
export function normalizeKeyName(name: string): string {
	return name
		.trim()
		.replace(/([a-z0-9])([A-Z])/g, "$1_$2")
		.replace(/[\s-]+/g, "_")
		.toLowerCase();
}

/** True when a `provider_config` key's NAME carries a credential word (`hcloud_token`, `dbPassword`). */
export function isCredentialKeyName(name: string): boolean {
	return CREDENTIAL_NAME.test(normalizeKeyName(name));
}

/**
 * True when a JSON value carries a credential-named key anywhere inside it — `[{ password: … }]`
 * in a `list(object)` knob, `{ apiToken: … }` in a `map` knob. A knob that is not itself a
 * credential can still be used to smuggle one into `provider_config`, so a value is scanned as
 * well as its key. Key NAMES only: a value is never inspected for what it looks like.
 */
export function valueHoldsCredential(value: unknown): boolean {
	if (Array.isArray(value)) return value.some(valueHoldsCredential);
	if (typeof value !== "object" || value === null) return false;
	return Object.entries(value).some(
		([key, inner]) => isCredentialKeyName(key) || valueHoldsCredential(inner),
	);
}

/**
 * True when a knob carries a credential: the template marks it `sensitive`, its name or its declared
 * type names a credential (`rds_extra_credentials` declares a `password` attribute), or it is a
 * secret component's own material (`value`).
 *
 * The ONE definition. `offerableKnobs` excludes these, so the canvas and the CLI (which narrows that
 * same set) agree; the project write actions refuse them through `credentialKeysInDesign`.
 *
 * Deliberately a name-and-type rule, so it over-matches rather than under-matches: AWS's
 * `store_access_key_in_ssm` is a `bool` and matches on `access_key`. It is not offerable for other
 * reasons, so nothing is lost; a false positive costs a control, a false negative costs a plaintext
 * secret.
 */
export function isCredentialKnob(knob: TemplateKnob): boolean {
	if (knob.sensitive) return true;
	if (CREDENTIAL_NAME.test(knob.name)) return true;
	if (CREDENTIAL_ATTRIBUTE.test(knob.typeExpr)) return true;
	return knob.component === "secret" && knob.name === "value";
}

/**
 * The credential knobs one component WOULD offer on one cloud if they were not credentials — every
 * other `offerableKnobs` filter passes. These are the controls a user may remember (or read about in
 * an old doc), so the canvas renders a note where each used to be, saying where the value goes now.
 */
export function withheldCredentialKnobs(
	knobs: readonly TemplateKnob[],
	cloud: string,
	kind: NodeKind,
): TemplateKnob[] {
	return knobs
		.filter(
			(k) =>
				k.cloud === cloud &&
				k.component === kind &&
				k.reachable &&
				isRead(k) &&
				!k.ceiling &&
				!k.ownedByProvider &&
				!k.typed &&
				isCredentialKnob(k),
		)
		.sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Where a withheld credential's value is supplied instead, as one or two sentences for the canvas
 * note and the server's refusal. Keyed `<component>:<name>`; anything not listed gets the generic
 * pointer, which is still true for every credential: a secret store, never `provider_config`.
 */
const CREDENTIAL_GUIDANCE: Readonly<Record<string, string>> = {
	"database:rds_extra_credentials":
		"Alethia generates the extra database user's password and stores the user, password and database name in AWS Secrets Manager. Read them from there after deploy; the secret's ARN is recorded on the database as extra_secret_ref. The user name and database name share this one variable with the password, so they keep the template defaults (demouser on demodb).",
	"secret:value":
		"Turn off Auto-generate value: Alethia then creates the secret with a placeholder and you set the real value in AWS Secrets Manager after deploy. Or make a secrets connector (Vault, Doppler, Infisical, 1Password) the environment's secrets store and write the value there.",
};

/** Where a credential knob's value is supplied instead of `provider_config` (see `CREDENTIAL_GUIDANCE`). */
export function credentialGuidance(component: string, name: string): string {
	return (
		CREDENTIAL_GUIDANCE[`${component}:${name}`] ??
		"Store it as a Secret component or in a secrets connector instead."
	);
}
