-- Provision Broker: unified job queue, log streaming, and worker registry

-- 1. Workers registry
CREATE TABLE IF NOT EXISTS public.workers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid(),
    name TEXT NOT NULL,
    mode TEXT NOT NULL CHECK (mode IN ('self-hosted', 'cloud-hosted')),
    cloud_identity_id UUID REFERENCES public.cloud_identities(id) ON DELETE SET NULL,
    token_hash TEXT NOT NULL,
    status TEXT DEFAULT 'OFFLINE' CHECK (status IN ('ONLINE', 'OFFLINE', 'DRAINING')),
    last_heartbeat TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own workers"
    ON public.workers FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own workers"
    ON public.workers FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own workers"
    ON public.workers FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own workers"
    ON public.workers FOR DELETE
    USING (auth.uid() = user_id);

CREATE INDEX idx_workers_user ON public.workers(user_id);
CREATE INDEX idx_workers_token_hash ON public.workers(id, token_hash);

-- 2. Unified provision jobs queue
CREATE TABLE IF NOT EXISTS public.provision_jobs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid(),
    vineyard_id UUID NOT NULL REFERENCES public.vineyards(id) ON DELETE CASCADE,
    cloud_identity_id UUID REFERENCES public.cloud_identities(id) ON DELETE SET NULL,
    job_type TEXT NOT NULL CHECK (job_type IN ('BOOTSTRAP', 'DEPLOY', 'DESTROY')),
    cluster_id UUID REFERENCES public.clusters(id) ON DELETE SET NULL,
    configuration_id UUID REFERENCES public.configurations(id) ON DELETE SET NULL,
    config_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    configuration_hash TEXT,
    status TEXT NOT NULL DEFAULT 'QUEUED'
        CHECK (status IN ('QUEUED', 'CLAIMED', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED')),
    worker_id TEXT,
    claimed_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    execution_metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.provision_jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own jobs"
    ON public.provision_jobs FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own jobs"
    ON public.provision_jobs FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE INDEX idx_provision_jobs_queue ON public.provision_jobs(status, created_at)
    WHERE status = 'QUEUED';
CREATE INDEX idx_provision_jobs_user ON public.provision_jobs(user_id);
CREATE INDEX idx_provision_jobs_vineyard ON public.provision_jobs(vineyard_id);
CREATE INDEX idx_provision_jobs_worker ON public.provision_jobs(worker_id)
    WHERE worker_id IS NOT NULL;

-- 3. Job logs (streamed by workers, consumed by frontend via Realtime)
CREATE TABLE IF NOT EXISTS public.job_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL REFERENCES public.provision_jobs(id) ON DELETE CASCADE,
    log_chunk TEXT NOT NULL,
    stream_type TEXT DEFAULT 'STDOUT' CHECK (stream_type IN ('STDOUT', 'STDERR', 'SYSTEM')),
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.job_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view logs for their own jobs"
    ON public.job_logs FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.provision_jobs
            WHERE provision_jobs.id = job_logs.job_id
            AND provision_jobs.user_id = auth.uid()
        )
    );

CREATE INDEX idx_job_logs_job_id ON public.job_logs(job_id);

-- Enable Realtime for log streaming
ALTER PUBLICATION supabase_realtime ADD TABLE public.job_logs;

-- 4. RPCs for worker operations (SECURITY DEFINER to bypass RLS)

-- Claim next queued job atomically
CREATE OR REPLACE FUNCTION public.claim_next_job(
    p_worker_id UUID,
    p_worker_token_hash TEXT,
    p_cloud_identity_id UUID DEFAULT NULL
)
RETURNS SETOF public.provision_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_job_id UUID;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM public.workers
        WHERE id = p_worker_id AND token_hash = p_worker_token_hash
    ) THEN
        RAISE EXCEPTION 'Unauthorized worker';
    END IF;

    -- Update heartbeat as a side effect
    UPDATE public.workers
    SET last_heartbeat = now(), status = 'ONLINE'
    WHERE id = p_worker_id;

    -- Atomically claim the oldest queued job
    UPDATE public.provision_jobs
    SET status = 'CLAIMED',
        worker_id = p_worker_id::text,
        claimed_at = now(),
        updated_at = now()
    WHERE id = (
        SELECT pj.id FROM public.provision_jobs pj
        WHERE pj.status = 'QUEUED'
        AND (p_cloud_identity_id IS NULL OR pj.cloud_identity_id = p_cloud_identity_id)
        ORDER BY pj.created_at ASC
        LIMIT 1
        FOR UPDATE SKIP LOCKED
    )
    RETURNING id INTO v_job_id;

    IF v_job_id IS NULL THEN
        RETURN;
    END IF;

    RETURN QUERY SELECT * FROM public.provision_jobs WHERE id = v_job_id;
END;
$$;

-- Update job status
CREATE OR REPLACE FUNCTION public.update_job_status(
    p_worker_id UUID,
    p_worker_token_hash TEXT,
    p_job_id UUID,
    p_status TEXT,
    p_error_message TEXT DEFAULT NULL,
    p_execution_metadata JSONB DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM public.workers
        WHERE id = p_worker_id AND token_hash = p_worker_token_hash
    ) THEN
        RAISE EXCEPTION 'Unauthorized worker';
    END IF;

    UPDATE public.provision_jobs
    SET
        status = p_status,
        error_message = COALESCE(p_error_message, error_message),
        execution_metadata = COALESCE(p_execution_metadata, execution_metadata),
        started_at = CASE WHEN p_status = 'PROCESSING' AND started_at IS NULL THEN now() ELSE started_at END,
        completed_at = CASE WHEN p_status IN ('SUCCESS', 'FAILED', 'CANCELLED') THEN now() ELSE completed_at END,
        updated_at = now()
    WHERE id = p_job_id
        AND worker_id = p_worker_id::text;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Job not found or not owned by this worker';
    END IF;
END;
$$;

-- Insert a log chunk for a job
CREATE OR REPLACE FUNCTION public.insert_job_log(
    p_worker_id UUID,
    p_worker_token_hash TEXT,
    p_job_id UUID,
    p_log_chunk TEXT,
    p_stream_type TEXT DEFAULT 'STDOUT'
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM public.workers
        WHERE id = p_worker_id AND token_hash = p_worker_token_hash
    ) THEN
        RAISE EXCEPTION 'Unauthorized worker';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.provision_jobs
        WHERE id = p_job_id AND worker_id = p_worker_id::text
    ) THEN
        RAISE EXCEPTION 'Job not owned by this worker';
    END IF;

    INSERT INTO public.job_logs (job_id, log_chunk, stream_type)
    VALUES (p_job_id, p_log_chunk, p_stream_type);
END;
$$;

-- Worker heartbeat
CREATE OR REPLACE FUNCTION public.worker_heartbeat(
    p_worker_id UUID,
    p_worker_token_hash TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.workers
    SET last_heartbeat = now(), status = 'ONLINE'
    WHERE id = p_worker_id AND token_hash = p_worker_token_hash;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Unauthorized worker';
    END IF;
END;
$$;

-- 5. Stale job recovery: reset claimed/processing jobs whose worker went offline
CREATE OR REPLACE FUNCTION public.recover_stale_jobs()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_count INTEGER;
BEGIN
    UPDATE public.provision_jobs
    SET status = 'QUEUED',
        worker_id = NULL,
        claimed_at = NULL,
        started_at = NULL,
        updated_at = now()
    WHERE status IN ('CLAIMED', 'PROCESSING')
    AND claimed_at < now() - INTERVAL '15 minutes'
    AND (
        worker_id IS NULL
        OR NOT EXISTS (
            SELECT 1 FROM public.workers w
            WHERE w.id::text = provision_jobs.worker_id
            AND w.last_heartbeat > now() - INTERVAL '5 minutes'
        )
    );

    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN v_count;
END;
$$;
