-- Seed new integration entries (observability, registry, DNS, secrets) — all as coming_soon

INSERT INTO public.integrations (slug, name, description, category, auth_method, organization, icon_url, docs_url, support_url, privacy_url, status, sort_order) VALUES
('datadog',        'Datadog',          'Monitor your provisioned clusters, databases, and services with Datadog APM, logs, and infrastructure metrics.',              'observability', 'api_key', 'Datadog, Inc.',       '/icons/datadog/datadog-32x32.png',       'https://docs.datadoghq.com/',                        'https://www.datadoghq.com/support/',              'https://www.datadoghq.com/legal/privacy/',                'coming_soon', 80),
('grafana',        'Grafana Cloud',    'Connect Grafana Cloud for dashboards, alerting, and observability across your infrastructure and applications.',              'observability', 'api_key', 'Grafana Labs',        '/icons/grafana/grafana-32x32.png',       'https://grafana.com/docs/',                          'https://grafana.com/contact/',                    'https://grafana.com/legal/privacy-policy/',               'coming_soon', 90),
('prometheus',     'Prometheus',       'Self-hosted metrics collection and alerting for Kubernetes workloads and infrastructure components.',                         'observability', 'api_key', 'Cloud Native Computing Foundation', '/icons/prometheus/prometheus-32x32.png', 'https://prometheus.io/docs/',               'https://prometheus.io/community/',                'https://www.linuxfoundation.org/legal/privacy-policy',    'coming_soon', 100),
('dockerhub',      'Docker Hub',       'Pull and push container images from Docker Hub registries for your ArgoCD deployments and CI/CD pipelines.',                 'registry',      'api_key', 'Docker, Inc.',        '/icons/dockerhub/dockerhub-32x32.png',   'https://docs.docker.com/docker-hub/',                'https://hub.docker.com/support/',                 'https://www.docker.com/legal/privacy/',                   'coming_soon', 110),
('cloudflare',     'Cloudflare',       'Manage DNS records, SSL certificates, and DDoS protection for your provisioned infrastructure across all cloud providers.',  'dns',           'api_key', 'Cloudflare, Inc.',    '/icons/cloudflare/cloudflare-32x32.png', 'https://developers.cloudflare.com/dns/',             'https://support.cloudflare.com/',                 'https://www.cloudflare.com/privacypolicy/',               'coming_soon', 120),
('vault',          'HashiCorp Vault',  'Centralized secrets management across cloud providers. Store, rotate, and audit access to credentials and API keys.',       'secrets',       'api_key', 'HashiCorp, Inc.',     '/icons/vault/vault-32x32.png',           'https://developer.hashicorp.com/vault/docs',        'https://support.hashicorp.com/',                  'https://www.hashicorp.com/privacy',                       'coming_soon', 130);
