-- Migration: Add Bootstrap Jobs and Logs

CREATE TABLE IF NOT EXISTS public.bootstrap_jobs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    vineyard_id UUID REFERENCES public.vineyards(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    status TEXT NOT NULL DEFAULT 'IN_PROGRESS',
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ
);

ALTER TABLE public.bootstrap_jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own bootstrap jobs"
    ON public.bootstrap_jobs FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own bootstrap jobs"
    ON public.bootstrap_jobs FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own bootstrap jobs"
    ON public.bootstrap_jobs FOR UPDATE
    USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.bootstrap_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID REFERENCES public.bootstrap_jobs(id) ON DELETE CASCADE NOT NULL,
    log_chunk TEXT NOT NULL,
    stream_type TEXT NOT NULL DEFAULT 'SYSTEM',
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.bootstrap_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view logs for their bootstrap jobs"
    ON public.bootstrap_logs FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.bootstrap_jobs
            WHERE bootstrap_jobs.id = bootstrap_logs.job_id
            AND bootstrap_jobs.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can insert logs for their bootstrap jobs"
    ON public.bootstrap_logs FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.bootstrap_jobs
            WHERE bootstrap_jobs.id = bootstrap_logs.job_id
            AND bootstrap_jobs.user_id = auth.uid()
        )
    );

CREATE INDEX IF NOT EXISTS idx_bootstrap_jobs_vineyard_id ON public.bootstrap_jobs(vineyard_id);
CREATE INDEX IF NOT EXISTS idx_bootstrap_logs_job_id ON public.bootstrap_logs(job_id);
