-- SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
-- SPDX-License-Identifier: AGPL-3.0-only
-- GENERATED by scripts/gen-connectors.mjs from packages/core/categories/catalog.json.
-- Idempotent seed of the pluggable-connector catalog rows.

INSERT INTO connectors (slug, name, description, category, auth_method, organization, icon_url, docs_url, status, sort_order)
VALUES
  ('aws', 'Amazon Web Services', 'Provision EKS, networking, databases, and more in your AWS account via a cross-account IAM role.', 'cloud'::connector_category, 'iam_role'::connector_auth_method, 'Amazon Web Services, Inc.', '/aws/favicon_64x64.png', 'https://docs.aws.amazon.com/', 'active'::connector_status, 10),
  ('gcp', 'Google Cloud', 'Provision GKE and managed services in your GCP project via Workload Identity Federation.', 'cloud'::connector_category, 'service_account'::connector_auth_method, 'Google LLC', '/gcp/favicon_64x64.png', 'https://cloud.google.com/docs', 'active'::connector_status, 11),
  ('azure', 'Microsoft Azure', 'Provision AKS and managed services in your Azure subscription via federated identity credentials.', 'cloud'::connector_category, 'service_principal'::connector_auth_method, 'Microsoft Corporation', '/azure/favicon_64x64.png', 'https://learn.microsoft.com/azure/', 'active'::connector_status, 12),
  ('alibaba', 'Alibaba Cloud', 'Provision ACK and managed services on Alibaba Cloud via a RAM role (zero stored credentials).', 'cloud'::connector_category, 'ram_role'::connector_auth_method, 'Alibaba Cloud', '/alibaba/favicon_64x64.png', 'https://www.alibabacloud.com/help', 'active'::connector_status, 13),
  ('digitalocean', 'DigitalOcean', 'Connect DigitalOcean with a scoped API token to provision DOKS and managed services. Provisioning templates coming soon.', 'cloud'::connector_category, 'api_key'::connector_auth_method, 'DigitalOcean, LLC', '/digitalocean/favicon_64x64.png', 'https://docs.digitalocean.com/reference/api/', 'coming_soon'::connector_status, 14),
  ('hetzner', 'Hetzner Cloud', 'Connect Hetzner Cloud with a scoped API token to provision a self-managed Talos Linux Kubernetes cluster on cheap VMs, with in-cluster data services via Helm.', 'cloud'::connector_category, 'api_key'::connector_auth_method, 'Hetzner Online GmbH', '/hetzner/favicon_64x64.png', 'https://docs.hetzner.cloud/', 'active'::connector_status, 15),
  ('civo', 'Civo', 'Connect Civo with a scoped API token to provision managed K3s clusters. Provisioning templates coming soon.', 'cloud'::connector_category, 'api_key'::connector_auth_method, 'Civo Ltd', '/civo/favicon_64x64.png', 'https://www.civo.com/docs', 'coming_soon'::connector_status, 16),
  ('github', 'GitHub', 'Connect repositories and wire GitOps deployments from GitHub.', 'git'::connector_category, 'oauth'::connector_auth_method, 'GitHub, Inc.', '/icons/github/github-32x32.png', 'https://docs.github.com/', 'active'::connector_status, 20),
  ('gitlab', 'GitLab', 'Connect repositories and wire GitOps deployments from GitLab.', 'git'::connector_category, 'oauth'::connector_auth_method, 'GitLab Inc.', '/icons/gitlab/gitlab-32x32.png', 'https://docs.gitlab.com/', 'active'::connector_status, 21),
  ('bitbucket', 'Bitbucket', 'Connect repositories and wire GitOps deployments from Bitbucket.', 'git'::connector_category, 'oauth'::connector_auth_method, 'Atlassian', '/icons/bitbucket/bitbucket-32x32.png', 'https://support.atlassian.com/bitbucket-cloud/', 'active'::connector_status, 22),
  ('cloudflare', 'Cloudflare', 'Manage DNS records and certificates on Cloudflare instead of the cluster cloud''s native DNS.', 'dns'::connector_category, 'api_key'::connector_auth_method, 'Cloudflare, Inc.', '/icons/cloudflare/cloudflare-32x32.png', 'https://developers.cloudflare.com/dns/', 'active'::connector_status, 30),
  ('vault', 'HashiCorp Vault', 'Store and read application secrets from a HashiCorp Vault instance.', 'secrets'::connector_category, 'api_key'::connector_auth_method, 'HashiCorp', '/icons/vault/vault-32x32.png', 'https://developer.hashicorp.com/vault/docs', 'active'::connector_status, 40),
  ('dockerhub', 'Docker Hub', 'Use a Docker Hub repository as the container registry instead of the cloud-native one.', 'registry'::connector_category, 'api_key'::connector_auth_method, 'Docker, Inc.', '/icons/dockerhub/dockerhub-32x32.png', 'https://docs.docker.com/docker-hub/', 'active'::connector_status, 50),
  ('generic-cr', 'Generic Registry', 'Authenticate to any OCI/Docker registry with a URL, username, and password.', 'registry'::connector_category, 'api_key'::connector_auth_method, 'Self-hosted / any', '/icons/generic-cr/generic-cr-32x32.png', 'https://distribution.github.io/distribution/', 'active'::connector_status, 51),
  ('ghcr', 'GitHub Container Registry', 'Pull images from GitHub Container Registry (ghcr.io).', 'registry'::connector_category, 'api_key'::connector_auth_method, 'GitHub, Inc.', '/icons/github/github-32x32.png', 'https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry', 'active'::connector_status, 52),
  ('ghcr-enterprise', 'GitHub Enterprise Container Registry', 'Pull images from a GitHub Enterprise Server container registry.', 'registry'::connector_category, 'api_key'::connector_auth_method, 'GitHub, Inc.', '/icons/github/github-32x32.png', 'https://docs.github.com/en/enterprise-server@latest/packages/working-with-a-github-packages-registry/working-with-the-container-registry', 'active'::connector_status, 53),
  ('gitlab-cr', 'GitLab Container Registry', 'Pull images from the GitLab container registry.', 'registry'::connector_category, 'api_key'::connector_auth_method, 'GitLab B.V.', '/icons/gitlab/gitlab-32x32.png', 'https://docs.gitlab.com/ee/user/packages/container_registry/', 'active'::connector_status, 54),
  ('quay', 'Quay', 'Pull images from Quay.io or a self-hosted Quay registry.', 'registry'::connector_category, 'api_key'::connector_auth_method, 'Red Hat, Inc.', '/icons/quay/quay-32x32.png', 'https://docs.quay.io/', 'active'::connector_status, 55),
  ('harbor', 'Harbor', 'Pull images from a self-hosted Harbor registry.', 'registry'::connector_category, 'api_key'::connector_auth_method, 'CNCF / Harbor', '/icons/harbor/harbor-32x32.png', 'https://goharbor.io/docs/', 'active'::connector_status, 56),
  ('docr', 'DigitalOcean Container Registry', 'Pull images from the DigitalOcean container registry.', 'registry'::connector_category, 'api_key'::connector_auth_method, 'DigitalOcean, LLC', '/icons/docr/docr-32x32.png', 'https://docs.digitalocean.com/products/container-registry/', 'active'::connector_status, 57),
  ('scaleway-cr', 'Scaleway Container Registry', 'Pull images from the Scaleway container registry.', 'registry'::connector_category, 'api_key'::connector_auth_method, 'Scaleway', '/icons/scaleway-cr/scaleway-cr-32x32.png', 'https://www.scaleway.com/en/docs/container-registry/', 'active'::connector_status, 58),
  ('datadog', 'Datadog', 'Ship cluster metrics, logs, and traces to Datadog.', 'observability'::connector_category, 'api_key'::connector_auth_method, 'Datadog, Inc.', '/icons/datadog/datadog-32x32.png', 'https://docs.datadoghq.com/', 'active'::connector_status, 60),
  ('grafana', 'Grafana Cloud', 'Remote-write metrics to Grafana Cloud''s managed Prometheus.', 'observability'::connector_category, 'api_key'::connector_auth_method, 'Grafana Labs', '/icons/grafana/grafana-32x32.png', 'https://grafana.com/docs/grafana-cloud/', 'active'::connector_status, 70)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  auth_method = EXCLUDED.auth_method,
  organization = EXCLUDED.organization,
  icon_url = EXCLUDED.icon_url,
  docs_url = EXCLUDED.docs_url,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
