-- SPDX-FileCopyrightText: 2026 Alethia Labs OÜ <legal@alethialabs.io>
-- SPDX-License-Identifier: AGPL-3.0-only
-- GENERATED by scripts/gen-connectors.mjs from packages/core/categories/catalog.json.
-- Idempotent seed of the pluggable-connector catalog rows.

INSERT INTO connectors (slug, name, description, category, auth_method, organization, icon_url, docs_url, status, sort_order)
VALUES
  ('cloudflare', 'Cloudflare', 'Manage DNS records and certificates on Cloudflare instead of the cluster cloud''s native DNS.', 'dns'::connector_category, 'api_key'::connector_auth_method, 'Cloudflare, Inc.', '/connectors/cloudflare.svg', 'https://developers.cloudflare.com/dns/', 'active'::connector_status, 30),
  ('vault', 'HashiCorp Vault', 'Store and read application secrets from a HashiCorp Vault instance.', 'secrets'::connector_category, 'api_key'::connector_auth_method, 'HashiCorp', '/connectors/vault.svg', 'https://developer.hashicorp.com/vault/docs', 'active'::connector_status, 40),
  ('dockerhub', 'Docker Hub', 'Use a Docker Hub repository as the container registry instead of the cloud-native one.', 'registry'::connector_category, 'api_key'::connector_auth_method, 'Docker, Inc.', '/connectors/dockerhub.svg', 'https://docs.docker.com/docker-hub/', 'active'::connector_status, 50),
  ('datadog', 'Datadog', 'Ship cluster metrics, logs, and traces to Datadog.', 'observability'::connector_category, 'api_key'::connector_auth_method, 'Datadog, Inc.', '/connectors/datadog.svg', 'https://docs.datadoghq.com/', 'active'::connector_status, 60),
  ('grafana', 'Grafana Cloud', 'Remote-write metrics to Grafana Cloud''s managed Prometheus.', 'observability'::connector_category, 'api_key'::connector_auth_method, 'Grafana Labs', '/connectors/grafana.svg', 'https://grafana.com/docs/grafana-cloud/', 'active'::connector_status, 70),
  ('prometheus', 'Prometheus', 'Install in-cluster Prometheus, optionally remote-writing to an external store.', 'observability'::connector_category, 'api_key'::connector_auth_method, 'Prometheus Authors', '/connectors/prometheus.svg', 'https://prometheus.io/docs/', 'active'::connector_status, 80)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  auth_method = EXCLUDED.auth_method,
  organization = EXCLUDED.organization,
  icon_url = EXCLUDED.icon_url,
  docs_url = EXCLUDED.docs_url,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
