// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// T2 DAY-2 OFFER posture (#1440) — the PURE, reusable half. Deliberately UNTAGGED (like
// t2_day2_access.go / packages/core/drift) so its classify/verdict logic is unit-tested
// WITHOUT a cloud (t2_day2_offer_pure_test.go, which ci.yml runs) and `go mod tidy` sees its
// deps.
//
// The offer-parity matrix (docs/testing/offer-parity.md, generated by
// apps/console/scripts/check-offer-parity.mjs) answers "could this offer ever build" — a
// static, day-1 question. This surface adds the day-2 dimension the matrix cannot express:
// for each offer (database:postgres/mysql, cache:redis/valkey) × cloud, the three operations
// that follow a first apply —
//
//	update  — change a tunable (version / retention / parameters): does the plan CONVERGE in
//	          place, or does it FORCE-REPLACE a stateful resource (losing the data + endpoint)?
//	resize  — change the size axis (capacity / shards / storage): the same question, and the
//	          endpoint must survive.
//	destroy — teardown to zero, no orphans.
//
// It answers those from a `tofu plan -json` of the proposed change, mirroring
// packages/core/drift (which reads the refresh-only plan) and packages/core/verify (which
// reads the plan for policy): it classifies each managed resource_change's actions and renders
// a per-op verdict. The classifier is what a real-apply run-harness (the e2e_t2 half, and the
// nightly wiring, are follow-ups — see the PR) evaluates the live plan against; a cell only
// goes green with a real-apply proof in the e2e ledger (demos/proofs/provisioning-e2e-log.md),
// which docs/testing/provisioning-e2e-parity.md owns. This surface never restates that proof —
// it defines the day-2 gate the proof must pass.
//
// # The #1440 sharp edges, and how each surfaces here
//
//   - A database engine-family switch (postgres↔mysql) replaces the server resource → a
//     stateful `replace`.
//   - AWS redis↔valkey is a module swap: an ElastiCache replication group is DELETED and a
//     serverless cache is CREATED (two resources, not one `replace`) → a stateful `delete`.
//   - GCP redis↔valkey swaps google_redis_instance for the SEPARATE google_memorystore_instance
//     → a stateful `delete`.
//   - A GCP Valkey shard-count change crossing the 1→>1 cluster-mode boundary is whatever tofu
//     plans it as — an in-place `update` (safe) or a `replace` (hazard); this gate reports what
//     the plan actually says rather than guessing.
//
// Because the update/resize hazard is BOTH a single-resource `replace` AND an outright `delete`
// of a data-bearing resource, both the engine-family switch and the cross-resource cache swaps
// are caught.
//
// # Honest scope (vacuity defense)
//
//   - The verdict is DERIVED from the plan's resource_changes, never hardcoded per offer — so it
//     cannot drift from what tofu actually plans for the change.
//   - An EMPTY changeset for an update/resize/destroy is a HARD error: a day-2 op that plans no
//     managed change must fail loudly, not pass vacuously.
//   - Like drift, a plan only sees MANAGED resources (in state). Orphans OUTSIDE state (leaked
//     cloud resources) are invisible here; OrphanScanKnown=false says so, so a clean-destroy
//     verdict never implies out-of-state orphans were checked when they were not.

package e2e

import (
	"fmt"
	"strings"

	tfjson "github.com/hashicorp/terraform-json"
)

// Day2Op is one of the three post-first-apply operations #1440 establishes per offer.
type Day2Op string

const (
	// Day2Update changes a tunable (version / retention / parameters).
	Day2Update Day2Op = "update"
	// Day2Resize changes the size axis (capacity / shards / storage).
	Day2Resize Day2Op = "resize"
	// Day2Destroy tears the offer down to zero.
	Day2Destroy Day2Op = "destroy"
)

// Day2ChangeKind is the day-2 classification of a single managed resource_change's actions.
type Day2ChangeKind string

const (
	// Day2NoOp — the resource is unchanged.
	Day2NoOp Day2ChangeKind = "no-op"
	// Day2InPlace — updated without replacement (the safe day-2 shape).
	Day2InPlace Day2ChangeKind = "in-place"
	// Day2Replace — destroyed and recreated (data + endpoint loss for a stateful resource).
	Day2Replace Day2ChangeKind = "replace"
	// Day2Create — newly created.
	Day2Create Day2ChangeKind = "create"
	// Day2Delete — destroyed.
	Day2Delete Day2ChangeKind = "delete"
	// Day2Other — any other action shape.
	Day2Other Day2ChangeKind = "other"
)

// Day2ResourceChange is one managed resource's day-2 classification.
type Day2ResourceChange struct {
	Address  string         `json:"address"`
	Type     string         `json:"type"`
	Kind     Day2ChangeKind `json:"kind"`
	Stateful bool           `json:"stateful"` // data-bearing: its replacement/deletion loses data + endpoint
}

// Day2Posture is the verdict of one day-2 operation over a plan. Pure, deterministic, storable.
type Day2Posture struct {
	Op Day2Op `json:"op"`
	// Safe is the day-2 health verdict:
	//   update/resize — no STATEFUL resource is force-replaced or deleted (all stateful
	//                   resources no-op or update in place).
	//   destroy       — every changed managed resource is a delete and nothing lingers as
	//                   create/update/replace.
	Safe bool `json:"safe"`
	// Changed is the count of managed resources with a non-no-op action.
	Changed int `json:"changed"`
	// DataLossHazards are the stateful resources an update/resize plan destroys or replaces —
	// the "does it force replacement of a stateful resource" failure.
	DataLossHazards []Day2ResourceChange `json:"data_loss_hazards,omitempty"`
	// Lingering are the non-delete changes seen in a DESTROY plan — a teardown that does not go
	// to zero.
	Lingering []Day2ResourceChange `json:"lingering,omitempty"`
	// OrphanScanKnown reports whether out-of-state orphan detection ran (always false: a plan
	// only sees managed resources — the same honest limit as drift.Posture.UnmanagedKnown).
	OrphanScanKnown bool `json:"orphan_scan_known"`
	// Verdict is a one-line human summary.
	Verdict string `json:"verdict"`
}

// day2StatefulTypes are the data-bearing MANAGED resource types across the four clouds whose
// REPLACEMENT or DELETION loses the offer's data and drops its endpoint — so a day-2
// update/resize that force-replaces or deletes one of these is NOT a safe day-2 op (it is an
// engine/topology change in disguise). Exact-match (not substring) so aws_db_subnet_group /
// aws_db_parameter_group — which carry no data — are correctly NOT stateful.
var day2StatefulTypes = map[string]bool{
	// AWS — RDS + ElastiCache (replication group for redis, serverless cache for valkey).
	"aws_db_instance":                   true,
	"aws_rds_cluster":                   true,
	"aws_rds_cluster_instance":          true,
	"aws_elasticache_replication_group": true,
	"aws_elasticache_cluster":           true,
	"aws_elasticache_serverless_cache":  true,
	// GCP — Cloud SQL + Memorystore (redis instance, and the SEPARATE valkey resource).
	"google_sql_database_instance": true,
	"google_redis_instance":        true,
	"google_memorystore_instance":  true,
	// Azure — Flexible Servers + Redis.
	"azurerm_postgresql_flexible_server": true,
	"azurerm_mysql_flexible_server":      true,
	"azurerm_redis_cache":                true,
	"azurerm_redis_enterprise_cluster":   true,
	"azurerm_redis_enterprise_database":  true,
	// Alibaba — RDS + KVStore (Redis / Valkey).
	"alicloud_db_instance":      true,
	"alicloud_kvstore_instance": true,
}

// isDay2StatefulType reports whether a resource type is a data-bearing offer resource whose
// replacement or deletion loses data + endpoint.
func isDay2StatefulType(t string) bool { return day2StatefulTypes[t] }

// classifyDay2Actions maps a resource_change's actions to a Day2ChangeKind. Replace is checked
// before the single-action shapes so a [delete, create] pair is never mistaken for a bare
// create or delete.
func classifyDay2Actions(act tfjson.Actions) Day2ChangeKind {
	switch {
	case act.NoOp():
		return Day2NoOp
	case act.Replace():
		return Day2Replace
	case act.Create():
		return Day2Create
	case act.Delete():
		return Day2Delete
	case act.Update():
		return Day2InPlace
	default:
		return Day2Other
	}
}

// AnalyzeDay2 classifies a `tofu plan -json` for a proposed day-2 operation on an offer and
// returns its posture. Pure and deterministic. A nil plan, or one whose managed changeset is
// empty, is a HARD error — a day-2 op that plans no managed change cannot be asserted (it would
// pass vacuously).
func AnalyzeDay2(op Day2Op, plan *tfjson.Plan) (*Day2Posture, error) {
	if plan == nil {
		return nil, fmt.Errorf("day-2 %s: nil plan — no proposed change to assert", op)
	}
	p := &Day2Posture{Op: op}
	var changed []Day2ResourceChange
	for _, rc := range plan.ResourceChanges {
		if rc == nil || rc.Change == nil {
			continue
		}
		if rc.Mode == tfjson.DataResourceMode {
			continue // data sources are reads, not managed infrastructure
		}
		kind := classifyDay2Actions(rc.Change.Actions)
		if kind == Day2NoOp {
			continue
		}
		changed = append(changed, Day2ResourceChange{
			Address:  rc.Address,
			Type:     rc.Type,
			Kind:     kind,
			Stateful: isDay2StatefulType(rc.Type),
		})
	}
	p.Changed = len(changed)
	if p.Changed == 0 {
		return nil, fmt.Errorf("day-2 %s: plan has no managed resource changes — nothing to assert (a real day-2 op always plans at least one change)", op)
	}

	switch op {
	case Day2Destroy:
		// A clean teardown deletes managed resources and lets NOTHING linger as
		// create/update/replace. Orphans OUTSIDE state are invisible to a plan (OrphanScanKnown).
		for _, c := range changed {
			if c.Kind != Day2Delete {
				p.Lingering = append(p.Lingering, c)
			}
		}
		p.Safe = len(p.Lingering) == 0
	default: // Day2Update, Day2Resize
		// The change must converge in place: no STATEFUL resource may be force-replaced OR
		// deleted (a delete is how a cross-resource engine swap — AWS/GCP redis↔valkey — shows
		// up, distinct from a single-resource replace).
		for _, c := range changed {
			if c.Stateful && (c.Kind == Day2Replace || c.Kind == Day2Delete) {
				p.DataLossHazards = append(p.DataLossHazards, c)
			}
		}
		p.Safe = len(p.DataLossHazards) == 0
	}
	p.Verdict = renderDay2Verdict(p)
	return p, nil
}

// renderDay2Verdict renders the one-line human verdict embedded in Day2Posture.Verdict.
func renderDay2Verdict(p *Day2Posture) string {
	icon := "✅"
	if !p.Safe {
		icon = "❌"
	}
	switch p.Op {
	case Day2Destroy:
		if p.Safe {
			return fmt.Sprintf("%s day2-destroy: clean teardown — %d managed resource(s) deleted, none lingering (out-of-state orphans not scanned)", icon, p.Changed)
		}
		return fmt.Sprintf("%s day2-destroy: %d managed change(s), but %d did not delete cleanly: %s", icon, p.Changed, len(p.Lingering), day2Addrs(p.Lingering))
	default:
		if p.Safe {
			return fmt.Sprintf("%s day2-%s: converges in place — %d managed change(s), no stateful resource replaced or deleted", icon, p.Op, p.Changed)
		}
		return fmt.Sprintf("%s day2-%s: destroys/replaces %d stateful resource(s) (data + endpoint loss): %s", icon, p.Op, len(p.DataLossHazards), day2Addrs(p.DataLossHazards))
	}
}

// day2Addrs joins the addresses of a set of resource changes for a human verdict line.
func day2Addrs(cs []Day2ResourceChange) string {
	a := make([]string, 0, len(cs))
	for _, c := range cs {
		a = append(a, c.Address)
	}
	return strings.Join(a, ", ")
}
