// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// T2 DAY-2 OFFER posture (#1440) — the PURE, reusable half. Deliberately UNTAGGED (like
// t2_day2_access.go / packages/core/drift) so its classify/verdict logic is unit-tested
// WITHOUT a cloud (t2_day2_offer_pure_test.go, which ci.yml runs) and `go mod tidy` sees its
// deps.
//
// The offer-parity matrix (docs/testing/offer-parity.md, generated by
// apps/console/scripts/check-offer-parity.mjs) answers "could this offer ever build" — a
// static, day-1 question. This surface adds the day-2 dimension the matrix cannot express:
// for each offer (database:postgres/mysql, cache:redis/valkey) × cloud, the three operations
// that follow a first apply —
//
//	update  — change a tunable (version / retention / parameters): does the plan CONVERGE in
//	          place, or does it FORCE-REPLACE a stateful resource (losing the data + endpoint)?
//	resize  — change the size axis (capacity / shards / storage): the same question, and the
//	          endpoint must survive.
//	destroy — teardown to zero, no orphans.
//
// It answers those from a `tofu plan -json` of the proposed change, mirroring
// packages/core/drift (which reads the refresh-only plan) and packages/core/verify (which
// reads the plan for policy): it classifies each managed resource_change's actions and renders
// a per-op verdict. The classifier is what a real-apply run-harness (the e2e_t2 half, and the
// nightly wiring, are follow-ups — see the PR) evaluates the live plan against; a cell only
// goes green with a real-apply proof in the e2e ledger (demos/proofs/provisioning-e2e-log.md),
// which docs/testing/provisioning-e2e-parity.md owns. This surface never restates that proof —
// it defines the day-2 gate the proof must pass.
//
// # The #1440 sharp edges, and how each surfaces here
//
//   - A database engine-family switch (postgres↔mysql) replaces the server resource → a
//     stateful `replace`.
//   - AWS redis↔valkey is a module swap: an ElastiCache replication group is DELETED and a
//     serverless cache is CREATED (two resources, not one `replace`) → a stateful `delete`.
//   - GCP redis↔valkey swaps google_redis_instance for the SEPARATE google_memorystore_instance
//     → a stateful `delete`.
//   - A GCP Valkey shard-count change crossing the 1→>1 cluster-mode boundary is whatever tofu
//     plans it as — an in-place `update` (safe) or a `replace` (hazard); this gate reports what
//     the plan actually says rather than guessing.
//
// Because the update/resize hazard is BOTH a single-resource `replace` AND an outright `delete`
// of a data-bearing resource, both the engine-family switch and the cross-resource cache swaps
// are caught.
//
// # Honest scope (vacuity defense)
//
//   - The verdict is DERIVED from the plan's resource_changes, never hardcoded per offer — so it
//     cannot drift from what tofu actually plans for the change.
//   - An EMPTY changeset for an update/resize/destroy is a HARD error: a day-2 op that plans no
//     managed change must fail loudly, not pass vacuously.
//   - Like drift, a plan only sees MANAGED resources (in state). Orphans OUTSIDE state (leaked
//     cloud resources) are invisible here; OrphanScanKnown=false says so, so a clean-destroy
//     verdict never implies out-of-state orphans were checked when they were not.

package e2e

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"
	"time"

	tfjson "github.com/hashicorp/terraform-json"

	"github.com/alethialabs-io/alethialabs/packages/core/catalog"
	"github.com/alethialabs-io/alethialabs/packages/core/types"
)

// Day2Op is one of the three post-first-apply operations #1440 establishes per offer.
type Day2Op string

const (
	// Day2Update changes a tunable (version / retention / parameters).
	Day2Update Day2Op = "update"
	// Day2Resize changes the size axis (capacity / shards / storage).
	Day2Resize Day2Op = "resize"
	// Day2Destroy tears the offer down to zero.
	Day2Destroy Day2Op = "destroy"
)

// Day2ChangeKind is the day-2 classification of a single managed resource_change's actions.
type Day2ChangeKind string

const (
	// Day2NoOp — the resource is unchanged.
	Day2NoOp Day2ChangeKind = "no-op"
	// Day2InPlace — updated without replacement (the safe day-2 shape).
	Day2InPlace Day2ChangeKind = "in-place"
	// Day2Replace — destroyed and recreated (data + endpoint loss for a stateful resource).
	Day2Replace Day2ChangeKind = "replace"
	// Day2Create — newly created.
	Day2Create Day2ChangeKind = "create"
	// Day2Delete — destroyed.
	Day2Delete Day2ChangeKind = "delete"
	// Day2Other — any other action shape.
	Day2Other Day2ChangeKind = "other"
)

// Day2ResourceChange is one managed resource's day-2 classification.
type Day2ResourceChange struct {
	Address  string         `json:"address"`
	Type     string         `json:"type"`
	Kind     Day2ChangeKind `json:"kind"`
	Stateful bool           `json:"stateful"` // data-bearing: its replacement/deletion loses data + endpoint
}

// Day2Posture is the verdict of one day-2 operation over a plan. Pure, deterministic, storable.
type Day2Posture struct {
	Op Day2Op `json:"op"`
	// Safe is the day-2 health verdict:
	//   update/resize — no STATEFUL resource is force-replaced or deleted (all stateful
	//                   resources no-op or update in place).
	//   destroy       — every changed managed resource is a delete and nothing lingers as
	//                   create/update/replace.
	Safe bool `json:"safe"`
	// Changed is the count of managed resources with a non-no-op action.
	Changed int `json:"changed"`
	// DataLossHazards are the stateful resources an update/resize plan destroys or replaces —
	// the "does it force replacement of a stateful resource" failure.
	DataLossHazards []Day2ResourceChange `json:"data_loss_hazards,omitempty"`
	// Lingering are the non-delete changes seen in a DESTROY plan — a teardown that does not go
	// to zero.
	Lingering []Day2ResourceChange `json:"lingering,omitempty"`
	// OrphanScanKnown reports whether out-of-state orphan detection ran (always false: a plan
	// only sees managed resources — the same honest limit as drift.Posture.UnmanagedKnown).
	OrphanScanKnown bool `json:"orphan_scan_known"`
	// Verdict is a one-line human summary.
	Verdict string `json:"verdict"`
}

// day2StatefulTypes are the data-bearing MANAGED resource types across the four clouds whose
// REPLACEMENT or DELETION loses the offer's data and drops its endpoint — so a day-2
// update/resize that force-replaces or deletes one of these is NOT a safe day-2 op (it is an
// engine/topology change in disguise). Exact-match (not substring) so aws_db_subnet_group /
// aws_db_parameter_group — which carry no data — are correctly NOT stateful.
var day2StatefulTypes = map[string]bool{
	// AWS — RDS + ElastiCache (replication group for redis, serverless cache for valkey).
	"aws_db_instance":                   true,
	"aws_rds_cluster":                   true,
	"aws_rds_cluster_instance":          true,
	"aws_elasticache_replication_group": true,
	"aws_elasticache_cluster":           true,
	"aws_elasticache_serverless_cache":  true,
	// GCP — Cloud SQL + Memorystore (redis instance, and the SEPARATE valkey resource).
	"google_sql_database_instance": true,
	"google_redis_instance":        true,
	"google_memorystore_instance":  true,
	// Azure — Flexible Servers + Redis. `azurerm_managed_redis` is what the template ACTUALLY builds
	// (infra/templates/project/azure/modules/azure-cache-redis): Azure Cache for Redis is retiring and
	// `azurerm_redis_cache` can no longer be created. Its absence here was a silent false PASS — the
	// gate saw an unknown type, called replacing Azure's cache Safe, and the offer read as proven when
	// nothing had checked it. The retired types stay: state predating the migration still carries them.
	"azurerm_postgresql_flexible_server": true,
	"azurerm_mysql_flexible_server":      true,
	"azurerm_managed_redis":              true,
	"azurerm_redis_cache":                true,
	"azurerm_redis_enterprise_cluster":   true,
	"azurerm_redis_enterprise_database":  true,
	// Alibaba — RDS + KVStore (Redis / Valkey).
	"alicloud_db_instance":      true,
	"alicloud_kvstore_instance": true,

	// Queues. Added with ordered delivery (#1812), and NOT as hardening: ordered delivery is
	// create-time-only on every cloud that has it, so the canvas switch that #1812 just wired is a
	// switch that DESTROYS the queue and everything in flight. `aws_sqs_queue.fifo_queue`,
	// `azurerm_servicebus_queue.requires_session` and
	// `google_pubsub_subscription.enable_message_ordering` are all ForceNew, and all three services
	// refuse the change at the API too — so there is no provider workaround to wait for. Without
	// these entries AnalyzeDay2 sees an unknown type, returns Safe, and a checkbox that wipes a
	// message backlog reads as a routine day-2 update.
	//
	// The SQS entry covers the dead-letter queue as well: it is the same resource type, and it is
	// replaced alongside its primary because AWS requires a FIFO queue's DLQ to be FIFO too.
	//
	// `alicloud_message_service_queue` is here for the OTHER reason: #1812 deliberately wires
	// nothing onto it (queue:ordered on Alibaba is a documented exclusion — see
	// infra/offer-exclusions.yaml), so no switch this PR ships can replace it. It is listed because
	// it holds messages, and this map is a map of what LOSES DATA, not of what this PR touched.
	"aws_sqs_queue":                  true,
	"azurerm_servicebus_queue":       true,
	"google_pubsub_subscription":     true,
	"alicloud_message_service_queue": true,

	// Buckets and NoSQL tables. Same reason as the Alibaba queue above, and equally NOT reachable
	// from an ordering switch — every one of them was returning Safe on replacement. The sibling
	// offer-parity lanes have since landed switches onto exactly these resources (#1813
	// bucket:public_access / bucket:versioning, #1814 bucket:encryption_enabled, #1815
	// nosql:point_in_time_recovery) and none of them added its type here, so the gap is live rather
	// than hypothetical. A switch landing on a create-time-only argument of an UNLISTED type is the
	// silent-false-PASS shape above: AnalyzeDay2 sees a type it does not know and calls the
	// replacement Safe.
	//
	// The offer-parity guard does not require these entries — it reports the same day-2 coverage
	// with or without them — so this is hardening carried past the strict boundary of #1812 on
	// purpose, not something a check forced.
	"aws_s3_bucket":             true,
	"google_storage_bucket":     true,
	"azurerm_storage_container": true,
	"alicloud_oss_bucket":       true,
	"google_firestore_database": true,
	"alicloud_ots_table":        true,
}

// isDay2StatefulType reports whether a resource type is a data-bearing offer resource whose
// replacement or deletion loses data + endpoint.
func isDay2StatefulType(t string) bool { return day2StatefulTypes[t] }

// classifyDay2Actions maps a resource_change's actions to a Day2ChangeKind. Replace is checked
// before the single-action shapes so a [delete, create] pair is never mistaken for a bare
// create or delete.
func classifyDay2Actions(act tfjson.Actions) Day2ChangeKind {
	switch {
	case act.NoOp():
		return Day2NoOp
	case act.Replace():
		return Day2Replace
	case act.Create():
		return Day2Create
	case act.Delete():
		return Day2Delete
	case act.Update():
		return Day2InPlace
	default:
		return Day2Other
	}
}

// AnalyzeDay2 classifies a `tofu plan -json` for a proposed day-2 operation on an offer and
// returns its posture. Pure and deterministic. A nil plan, or one whose managed changeset is
// empty, is a HARD error — a day-2 op that plans no managed change cannot be asserted (it would
// pass vacuously).
func AnalyzeDay2(op Day2Op, plan *tfjson.Plan) (*Day2Posture, error) {
	if plan == nil {
		return nil, fmt.Errorf("day-2 %s: nil plan — no proposed change to assert", op)
	}
	p := &Day2Posture{Op: op}
	var changed []Day2ResourceChange
	for _, rc := range plan.ResourceChanges {
		if rc == nil || rc.Change == nil {
			continue
		}
		if rc.Mode == tfjson.DataResourceMode {
			continue // data sources are reads, not managed infrastructure
		}
		kind := classifyDay2Actions(rc.Change.Actions)
		if kind == Day2NoOp {
			continue
		}
		changed = append(changed, Day2ResourceChange{
			Address:  rc.Address,
			Type:     rc.Type,
			Kind:     kind,
			Stateful: isDay2StatefulType(rc.Type),
		})
	}
	p.Changed = len(changed)
	if p.Changed == 0 {
		return nil, fmt.Errorf("day-2 %s: plan has no managed resource changes — nothing to assert (a real day-2 op always plans at least one change)", op)
	}

	switch op {
	case Day2Destroy:
		// A clean teardown deletes managed resources and lets NOTHING linger as
		// create/update/replace. Orphans OUTSIDE state are invisible to a plan (OrphanScanKnown).
		for _, c := range changed {
			if c.Kind != Day2Delete {
				p.Lingering = append(p.Lingering, c)
			}
		}
		p.Safe = len(p.Lingering) == 0
	default: // Day2Update, Day2Resize
		// The change must converge in place: no STATEFUL resource may be force-replaced OR
		// deleted (a delete is how a cross-resource engine swap — AWS/GCP redis↔valkey — shows
		// up, distinct from a single-resource replace).
		for _, c := range changed {
			if c.Stateful && (c.Kind == Day2Replace || c.Kind == Day2Delete) {
				p.DataLossHazards = append(p.DataLossHazards, c)
			}
		}
		p.Safe = len(p.DataLossHazards) == 0
	}
	p.Verdict = renderDay2Verdict(p)
	return p, nil
}

// renderDay2Verdict renders the one-line human verdict embedded in Day2Posture.Verdict.
func renderDay2Verdict(p *Day2Posture) string {
	icon := "✅"
	if !p.Safe {
		icon = "❌"
	}
	switch p.Op {
	case Day2Destroy:
		if p.Safe {
			return fmt.Sprintf("%s day2-destroy: clean teardown — %d managed resource(s) deleted, none lingering (out-of-state orphans not scanned)", icon, p.Changed)
		}
		return fmt.Sprintf("%s day2-destroy: %d managed change(s), but %d did not delete cleanly: %s", icon, p.Changed, len(p.Lingering), day2Addrs(p.Lingering))
	default:
		if p.Safe {
			return fmt.Sprintf("%s day2-%s: converges in place — %d managed change(s), no stateful resource replaced or deleted", icon, p.Op, p.Changed)
		}
		return fmt.Sprintf("%s day2-%s: destroys/replaces %d stateful resource(s) (data + endpoint loss): %s", icon, p.Op, len(p.DataLossHazards), day2Addrs(p.DataLossHazards))
	}
}

// day2Addrs joins the addresses of a set of resource changes for a human verdict line.
func day2Addrs(cs []Day2ResourceChange) string {
	a := make([]string, 0, len(cs))
	for _, c := range cs {
		a = append(a, c.Address)
	}
	return strings.Join(a, ", ")
}

// ─────────────────────── run-harness support (#1495) ───────────────────────
// Everything below is what the e2e_t2 run-harness (t2_day2_offer_run_test.go) needs in order
// to DRIVE the classifier above against a live environment. It lives in this untagged file so
// it is unit-tested without a cloud — the mutation planner especially, since a mutation that
// plans no change is the one way this gate can fail open.

// Day2OfferEnabled reports whether this run should assert the day-2 OFFER postures (opt-in;
// the nightly turns it on with the full bar).
func Day2OfferEnabled() bool {
	return os.Getenv("ALETHIA_E2E_DAY2_OFFER") == "1"
}

// Day2OfferTimeout bounds each day-2 PLAN — ALETHIA_E2E_DAY2_OFFER_TIMEOUT when set (a Go
// duration), else 15m. A `tofu plan` against live state does real provider refreshes, so the
// default is generous; the bound exists so a wedged provider call cannot hang the nightly.
func Day2OfferTimeout() time.Duration {
	if v := strings.TrimSpace(os.Getenv("ALETHIA_E2E_DAY2_OFFER_TIMEOUT")); v != "" {
		if d, err := time.ParseDuration(v); err == nil && d > 0 {
			return d
		}
	}
	return 15 * time.Minute
}

// day2ResizeClass is the database instance class each cloud RESIZES TO. Resize is the one day-2
// axis that cannot be expressed cloud-indifferently: ProjectDatabaseConfig.InstanceClass is a
// concrete provider SKU, so naming a target means naming it per cloud. Each value is a real,
// valid class for that provider and DIFFERENT from the template default it replaces
// (aws db.serverless · gcp db-f1-micro · azure B_Standard_B1ms · alibaba pg.n2.small.2c), which
// is what makes the plan non-empty. Nothing is ever applied — this only has to plan.
var day2ResizeClass = map[string]string{
	"aws":     "db.t3.medium",
	"gcp":     "db-g1-small",
	"azure":   "B_Standard_B2s",
	"alibaba": "pg.n2.medium.2c",
}

// Day2Mutation describes the change a day-2 op proposes, for the summary and for the error a
// vacuous plan produces. Applied is false when this provider/offer combination has no mutation
// to make — recorded rather than silently skipped.
type Day2Mutation struct {
	Op      Day2Op `json:"op"`
	Field   string `json:"field"`
	Detail  string `json:"detail"`
	Applied bool   `json:"applied"`
	// Offers names what this mutation ACTUALLY touched ("database", "cache"). Applied says the
	// plan is worth running; this says what the plan COVERS, and they are not the same once an op
	// spans more than one offer. An environment with databases but no caches must not be read as
	// cache coverage — OffersExercised is built from this, never from the op alone.
	Offers []string `json:"offers,omitempty"`
}

// applyDay2Update mutates a TUNABLE on every database offer: backup retention, +1 day.
//
// Retention is the only tunable all four clouds wire from the cloud-indifferent config
// (BackupRetentionDays → aws/gcp/azure/alibaba), it converges in place on every one of them,
// and it needs no per-cloud SKU vocabulary. Engine version was the obvious alternative and is
// rejected: a version string valid on one cloud is invalid on the next, and an invalid one
// fails at plan time — which would look identical to the hazard this gate hunts for.
//
// Caches are still NOT mutated on the UPDATE leg — but for a narrower reason than before #1526,
// and no longer for the reason the old comment gave. MemoryGB now reaches all four clouds (#1526
// gave azure the axis; alibaba already had it), so the SIZE axis is covered — on the RESIZE leg,
// where it belongs. What the cache offer still has no candidate for is a NON-size tunable that
// converges in place everywhere:
//
//	NumCacheNodes  — aws + gcp + azure only; alibaba never reads it.
//	EngineVersion  — per-cloud vocabulary, exactly the reason retention beat it for databases.
//	MultiAz        — universal, but it is a TOPOLOGY change: on several clouds it legitimately
//	                 plans a replace, so an update leg built on it would report a hazard that
//	                 says nothing about whether updates converge.
//
// So the update leg stays database-only and says so, rather than reaching for MultiAz to make the
// table look full. The summary records which offers each op actually exercised.
func applyDay2Update(dbs []types.ProjectDatabaseConfig) Day2Mutation {
	m := Day2Mutation{Op: Day2Update, Field: "databases[].backup_retention_days"}
	if len(dbs) == 0 {
		m.Detail = "no database offer in this environment"
		return m
	}
	for i := range dbs {
		cur := 7
		if dbs[i].BackupRetentionDays != nil {
			cur = *dbs[i].BackupRetentionDays
		}
		next := cur + 1
		dbs[i].BackupRetentionDays = &next
	}
	m.Applied = true
	m.Offers = []string{"database"}
	m.Detail = fmt.Sprintf("backup retention +1 day on %d database offer(s)", len(dbs))
	return m
}

// applyDay2Resize mutates the SIZE axis on every database AND cache offer.
//
// The two offers reach it differently, and that asymmetry is the point. A database's size is
// `InstanceClass`, a concrete provider SKU, so its target has to be named per cloud
// (day2ResizeClass). A cache's size is `MemoryGB` — cloud-indifferent since #1526, read by all
// four providers — so its target needs NO per-cloud table: ask the catalog for the next tier up
// and every cloud resolves that number to its own SKU. A hand-kept cache table would have been a
// second copy of packages/core/catalog/catalog.json, drifting from it on the first refresh.
//
// Each leg applies independently: a provider with no database target, or an environment with no
// caches, skips that leg and the other still runs. Applied is true when EITHER did, and Offers
// records which — so a database-only environment can never be read as cache coverage.
func applyDay2Resize(
	dbs []types.ProjectDatabaseConfig,
	caches []types.ProjectCacheConfig,
	provider string,
) Day2Mutation {
	m := Day2Mutation{Op: Day2Resize}
	var fields, details, skipped []string

	// ── databases: a per-cloud SKU ────────────────────────────────────────────────────────
	switch target, ok := day2ResizeClass[provider]; {
	case !ok:
		skipped = append(skipped, fmt.Sprintf("database: no resize target recorded for provider %q", provider))
	case len(dbs) == 0:
		skipped = append(skipped, "database: no database offer in this environment")
	default:
		// A resize to the class the offer already runs plans nothing. Refuse rather than emit a
		// mutation the caller would read as applied and then fail on an empty changeset.
		already := false
		for i := range dbs {
			if dbs[i].InstanceClass == target {
				already = true
			}
		}
		if already {
			skipped = append(skipped, fmt.Sprintf("database: already runs %s — no resize to propose", target))
		} else {
			for i := range dbs {
				dbs[i].InstanceClass = target
			}
			m.Offers = append(m.Offers, "database")
			fields = append(fields, "databases[].instance_class")
			details = append(details, fmt.Sprintf("instance class → %s on %d database offer(s)", target, len(dbs)))
		}
	}

	// ── caches: the cloud-indifferent size ────────────────────────────────────────────────
	if len(caches) == 0 {
		skipped = append(skipped, "cache: no cache offer in this environment")
	} else if next, tier, ok := day2NextCacheTier(provider, caches); !ok {
		skipped = append(skipped, fmt.Sprintf("cache: no larger tier than the current one on %s", provider))
	} else {
		for i := range caches {
			caches[i].MemoryGB = next
			// A stale explicit SKU would shadow nothing (MemoryGB wins in resolveCacheNodeType),
			// but leaving it would make the config say two different sizes. Clear it so the
			// snapshot and the plan agree about what was asked for.
			caches[i].NodeType = ""
		}
		m.Offers = append(m.Offers, "cache")
		fields = append(fields, "caches[].memory_gb")
		details = append(details, fmt.Sprintf("memory → %gGB (%s) on %d cache offer(s)", next, tier, len(caches)))
	}

	m.Applied = len(m.Offers) > 0
	m.Field = strings.Join(fields, " + ")
	if m.Applied {
		m.Detail = strings.Join(details, "; ")
		if len(skipped) > 0 {
			m.Detail += " (" + strings.Join(skipped, "; ") + ")"
		}
	} else {
		m.Detail = strings.Join(skipped, "; ")
	}
	return m
}

// day2Exercised renders a mutation's Offers as its OffersExercised entries — "cache (resize)".
//
// It reads Offers, never the op, because the two answer different questions: the op is what was
// attempted, Offers is what the plan actually covers. An environment with databases and no caches
// runs the resize op and must still report only "database (resize)", or the summary claims a
// coverage the nightly never proved — the vacuity this whole surface exists to refuse.
func day2Exercised(m Day2Mutation) []string {
	out := make([]string, 0, len(m.Offers))
	for _, offer := range m.Offers {
		out = append(out, fmt.Sprintf("%s (%s)", offer, m.Op))
	}
	return out
}

// day2NextCacheTier returns the memory size of the catalog tier ABOVE the one these caches
// currently resolve to on this provider, plus that tier's SKU for the summary line.
//
// "Above the LARGEST of them" — with several caches in one environment, moving to a tier one of
// them already occupies would plan nothing for that one. Reports false at the top of the
// provider's inventory, which the caller records as an honest skip.
func day2NextCacheTier(provider string, caches []types.ProjectCacheConfig) (float64, string, bool) {
	cp, ok := catalog.MustLoad().Cache[provider]
	if !ok || len(cp.Tiers) == 0 {
		return 0, "", false
	}
	// The floor to beat. An unsized cache (MemoryGB 0) runs the template's own default, so the
	// smallest tier still counts as a move away from it.
	var current float64
	for i := range caches {
		if caches[i].MemoryGB > current {
			current = caches[i].MemoryGB
		}
	}
	var next *catalog.CacheTier
	for i := range cp.Tiers {
		t := &cp.Tiers[i]
		if t.MemoryGB > current && (next == nil || t.MemoryGB < next.MemoryGB) {
			next = t
		}
	}
	if next == nil {
		return 0, "", false
	}
	return next.MemoryGB, next.Value, true
}

// planFromMap converts the provisioner's PlanResult.PlanJSON (an untyped map, because it
// crosses the runner's result.json boundary) into the typed plan AnalyzeDay2 reads. A nil or
// empty map is an error: "no plan" and "a plan with no changes" are opposite findings, and
// AnalyzeDay2 must never be handed the former dressed as the latter.
func planFromMap(raw map[string]interface{}) (*tfjson.Plan, error) {
	if len(raw) == 0 {
		return nil, errors.New("plan JSON is empty — the plan was not produced, which is not the same as a plan with no changes")
	}
	b, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("re-marshal plan JSON: %w", err)
	}
	var plan tfjson.Plan
	if err := json.Unmarshal(b, &plan); err != nil {
		return nil, fmt.Errorf("decode plan JSON: %w", err)
	}
	return &plan, nil
}

// OfferSummary is the machine-readable result of the day-2 OFFER assertion, written to
// ALETHIA_E2E_DAY2_OFFER_SUMMARY so the proof/verdict capture can fold a day-2 line into the
// per-provider step summary. Booleans, counts and resource addresses only — no secrets.
type OfferSummary struct {
	Enabled  bool   `json:"enabled"`
	Provider string `json:"provider"`
	// Postures is one entry per op that RAN. An op whose mutation did not apply is absent
	// here and present in Skipped — the two must stay distinguishable.
	Postures  []*Day2Posture `json:"postures,omitempty"`
	Mutations []Day2Mutation `json:"mutations,omitempty"`
	Skipped   []string       `json:"skipped,omitempty"`
	// OffersExercised names what update/resize actually touched, built from each mutation's
	// Offers rather than from the op — so it reports coverage, not intent. The gate covers the
	// database offer on every cloud for both ops, and the cache offer on resize (#1526); a cache
	// UPDATE has no cloud-indifferent tunable to move, so caches remain destroy-only there (the
	// reasoning is on applyDay2Update).
	OffersExercised []string `json:"offers_exercised,omitempty"`
	Verdict         string   `json:"verdict"`
}

// offerVerdictPass reports whether every day-2 posture that RAN is Safe. An op that could not
// run does not gate — but it is never counted as a pass either, and a run where NOTHING ran is
// a failure: that is the vacuous shape this whole surface exists to refuse.
func offerVerdictPass(s OfferSummary) bool {
	if !s.Enabled || len(s.Postures) == 0 {
		return false
	}
	for _, p := range s.Postures {
		if p == nil || !p.Safe {
			return false
		}
	}
	return true
}

// offerSummaryVerdict renders the one-line human verdict embedded in OfferSummary.Verdict.
func offerSummaryVerdict(s OfferSummary) string {
	if !s.Enabled {
		return "day2-offer: skipped (ALETHIA_E2E_DAY2_OFFER unset)"
	}
	icon := "✅"
	if !offerVerdictPass(s) {
		icon = "❌"
	}
	parts := make([]string, 0, len(s.Postures))
	for _, p := range s.Postures {
		if p == nil {
			continue
		}
		parts = append(parts, fmt.Sprintf("%s=%t", p.Op, p.Safe))
	}
	if len(parts) == 0 {
		parts = append(parts, "none ran")
	}
	out := fmt.Sprintf("%s day2-offer (%s): %s", icon, s.Provider, strings.Join(parts, " · "))
	if len(s.Skipped) > 0 {
		out += fmt.Sprintf(" · skipped: %s", strings.Join(s.Skipped, "; "))
	}
	return out
}

// writeOfferSummary persists the day-2 offer summary as indented JSON.
func writeOfferSummary(path string, s OfferSummary) error {
	b, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}
