// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// The Go half of the formatter contract.
//
// `packages/format/conformance/format-cases.json` is generated by TypeScript from the real
// `@repo/format` implementation, over inputs a human curates. This file drives the SAME rows through
// the Go implementation and requires the same answers. The three layers, from the table's own header:
//
//	1. packages/format/tests/conformance.test.ts — TS changed and the table did not
//	2. the CI diff-gate                          — the table is stale
//	3. THIS FILE                                 — Go disagrees with the table
//
// Go cannot write the file, so it has no way to make itself right. Neither side drifts alone.
//
// NEVER run `pnpm -F console gen:format-conformance --write` to make this file go green. That is
// exactly what somebody does when a Go test is red, and it converts a disagreement into a silently
// rewritten expectation. If Go is wrong, fix Go. If the TABLE is wrong, change the TypeScript and
// let the generator move the row, where the changed-case summary shows it in review.

package format

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const tableRel = "packages/format/conformance/format-cases.json"

// regenerate is printed on every failure that could be a stale table rather than a real disagreement.
const regenerate = "If the TABLE is stale, regenerate it from TypeScript: pnpm -F console gen:format-conformance"

type tableFile struct {
	Version  int                         `json:"version"`
	Excluded map[string]string           `json:"excluded"`
	Cases    map[string][]map[string]any `json:"cases"`
}

// monorepoRoot walks up to the directory holding go.work. Returns "" outside a monorepo checkout, so
// packages/core stays vendorable standalone — the same escape secrets_runtime_read_mirror_test uses.
func monorepoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

func loadTable(t *testing.T) tableFile {
	t.Helper()
	root := monorepoRoot(t)
	if root == "" {
		// Vendored standalone. There is no table to drive, and that is not a failure.
		t.Skip("not a monorepo checkout — no conformance table to drive")
	}
	// The root EXISTS and the file does not: that IS a failure, and a different one.
	raw, err := os.ReadFile(filepath.Join(root, tableRel))
	if err != nil {
		t.Fatalf("read %s: %v\n%s", tableRel, err, regenerate)
	}
	var tbl tableFile
	if err := json.Unmarshal(raw, &tbl); err != nil {
		t.Fatalf("decode %s: %v\n%s", tableRel, err, regenerate)
	}
	return tbl
}

// num reads a numeric input. JSON `null` is the table's sentinel for "not a finite number" — NaN is
// not representable in JSON — so it decodes to NaN here, which is what the TS side passes too.
func num(t *testing.T, row map[string]any, key string) float64 {
	t.Helper()
	v, present := row[key]
	if !present {
		t.Fatalf("row %v has no %q", row["id"], key)
	}
	if v == nil {
		return math.NaN()
	}
	f, ok := v.(float64)
	if !ok {
		t.Fatalf("row %v: %q is %T, want a number", row["id"], key, v)
	}
	return f
}

func str(t *testing.T, row map[string]any, key string) string {
	t.Helper()
	v, ok := row[key].(string)
	if !ok {
		t.Fatalf("row %v: %q is %T, want a string", row["id"], key, row[key])
	}
	return v
}

// drivers unpack each section's row into a call. This is the whole contract: one line per section,
// mirroring DRIVERS in packages/format/tests/conformance.test.ts.
var drivers = map[string]func(*testing.T, map[string]any) string{
	"minutes":  func(t *testing.T, r map[string]any) string { return Minutes(num(t, r, "in")) },
	"quota":    func(t *testing.T, r map[string]any) string { return Quota(num(t, r, "used"), num(t, r, "included")) },
	"duration": func(t *testing.T, r map[string]any) string { return Duration(millis(num(t, r, "in"))) },
	"bytes":    func(t *testing.T, r map[string]any) string { return Bytes(num(t, r, "in")) },
	"money":    func(t *testing.T, r map[string]any) string { return Money(num(t, r, "cents"), str(t, r, "currency")) },
	"monthlyRate": func(t *testing.T, r map[string]any) string {
		return MonthlyRate(num(t, r, "amount"), RateStyle(str(t, r, "style")), str(t, r, "currency"))
	},
	"monthlyDelta": func(t *testing.T, r map[string]any) string {
		return MonthlyDelta(num(t, r, "amount"), RateStyle(str(t, r, "style")), str(t, r, "currency"))
	},
	"date": func(t *testing.T, r map[string]any) string {
		loc, err := time.LoadLocation(str(t, r, "timeZone"))
		if err != nil {
			// A zone the runtime cannot resolve is an environment fault, not a disagreement — and
			// it is the exact failure `_ "time/tzdata"` exists to prevent, so say so.
			t.Fatalf("row %v: LoadLocation(%q): %v — is `_ \"time/tzdata\"` still imported in format.go?",
				r["id"], str(t, r, "timeZone"), err)
		}
		raw, isString := r["value"].(string)
		if !isString {
			// The table's null-date case. Go has no nullable time, so the zero value carries it.
			return Date(time.Time{}, DateStyle(str(t, r, "style")), loc)
		}
		parsed, err := time.Parse(time.RFC3339, raw)
		if err != nil {
			// The table's unparseable-date case. The TS side hands `new Date` a string it cannot
			// read and gets the em dash; Go's caller cannot construct a time at all, so the zero
			// value stands in for the same thing.
			return Date(time.Time{}, DateStyle(str(t, r, "style")), loc)
		}
		return Date(parsed, DateStyle(str(t, r, "style")), loc)
	},
}

// millis converts the table's millisecond numbers to a Duration. NaN and negatives both land at or
// below zero, which is what the `nonfinite-clamps` and `negative-clamps` rows expect.
func millis(ms float64) time.Duration {
	if math.IsNaN(ms) || math.IsInf(ms, 0) {
		return 0
	}
	return time.Duration(ms) * time.Millisecond
}

func TestGoMatchesTheConformanceTable(t *testing.T) {
	tbl := loadTable(t)
	for _, problem := range tableProblems(tbl) {
		t.Fatal(problem)
	}

	for section, rows := range tbl.Cases {
		drive, ok := drivers[section]
		if !ok {
			continue // reported by tableProblems above; do not also fail per-row
		}
		for _, row := range rows {
			id, _ := row["id"].(string)
			want, _ := row["want"].(string)
			t.Run(id, func(t *testing.T) {
				if got := drive(t, row); got != want {
					t.Errorf("%s\n  got  %q\n  want %q\n%s", id, got, want, regenerate)
				}
			})
		}
	}
}

// ── the guard ──────────────────────────────────────────────────────────────────────────────────

// requiredIDs are the rows that exist because the two languages disagreed, or would. Named, NOT
// counted: a count floor is cleared by unrelated rows, so every case a guard protects can be deleted
// while the threshold still passes. That defect shipped twice in this repo before it was believed.
//
// Deliberately duplicated from packages/format/tests/conformance.test.ts rather than derived from
// the table: this is Go stating what it REQUIRES of a file TypeScript writes. A list generated from
// the table would be regenerated by the same command that removed the row.
var requiredIDs = []string{
	// Go's %.0f rounds half to EVEN; JavaScript rounds half away from zero. The reason this
	// package exists, and the reason cmd/clusters_list.go printed $12 for $12.50.
	"monthlyRate/estimate/HALF-CENT-ROUNDS-AWAY-FROM-ZERO",
	"monthlyRate/exact/HALF-CENT-ROUNDS-AWAY-FROM-ZERO",
	// Rounding happens once, BEFORE the hour test.
	"minutes/HALF-ROUNDS-UP-ACROSS-THE-HOUR-BOUNDARY",
	"minutes/the-0.943-bug",
	// The used side humanises; the allowance never does, and it keeps its separator.
	"quota/used-exceeds-allowance-is-not-clamped",
	"quota/ALLOWANCE-KEEPS-THOUSANDS-SEPARATOR",
	// The duration ruling, and the boundary in both directions.
	"duration/TWO-HOURS-ROLLS-INTO-HOURS",
	"duration/JUST-UNDER-AN-HOUR-DOES-NOT-ROLL",
	"duration/EXACTLY-AN-HOUR",
	// hourCycle h23, not hour12:false — the option that renders midnight as 24:00 in some locales.
	"date/MIDNIGHT-IS-00-NOT-24",
	// A zone that shifts the calendar day is the case `_ "time/tzdata"` is imported for.
	"date/zone-shifts-the-day",
	// A currency with no minor unit, and one whose symbol is not its ISO prefix.
	"monthlyRate/estimate/JPY-HAS-NO-MINOR-UNIT",
	"money/EUR-NARROW-SYMBOL-NOT-EUR-PREFIX",
	// The credit register (#3768, #3895). ONE ROW PER WAY OF GETTING IT WRONG, and every one of
	// those mistakes renders the REST of the block correctly, which is what makes each row
	// load-bearing rather than decorative: dropping the sign, signing the zero, rounding half to
	// EVEN — this package's founding defect, met again at a register that rounds to whole units —
	// deciding the sign on the raw amount rather than on the rendered magnitude, which resurrects
	// `+$0/mo` for a change too small to show, rounding the decimal a human typed rather than the
	// binary product the scale produces, and pre-rounding at a fixed two places rather than at the
	// places being printed.
	//
	// NO COUNT IN THAT SENTENCE, deliberately. It read "Four separate mistakes ... so all four are
	// named" over five ids, and had been wrong since the fifth was added: a hand-typed number in a
	// comment beside a list is a second source of truth for the list's length and decays the first
	// time the list grows. The identical sentence carried the identical error in
	// packages/format/tests/conformance.test.ts.
	"monthlyDelta/estimate/A-SAVING-KEEPS-ITS-SIGN",
	"monthlyDelta/estimate/AN-INCREASE-IS-SIGNED-TOO",
	"monthlyDelta/exact/ZERO-CARRIES-NO-SIGN-AND-NO-MINOR-UNITS",
	"monthlyDelta/exact/JPY-HALF-ROUNDS-AWAY-FROM-ZERO",
	"monthlyDelta/estimate/A-SUB-UNIT-INCREASE-ROUNDS-TO-NO-CHANGE",
	// #3895. Three decimals, so `roundHalfAwayFromZero`'s multiply lands on the far side of a half
	// from the literal — `8.165 * 100` is 816.4999999999999. Every other row in this section stays
	// inside two decimals, where the binary product is exact and the two languages cannot disagree,
	// so the section looked like it pinned the rounding rule and pinned a different one.
	"monthlyDelta/exact/BINARY-SCALE-8.165-ROUNDS-DOWN",
	"monthlyDelta/exact/BINARY-SCALE-8.165-ROUNDS-DOWN-A-SAVING-TOO",
	"monthlyDelta/exact/BINARY-SCALE-1.005-ROUNDS-DOWN",
	"monthlyDelta/exact/BINARY-SCALE-1.005-ROUNDS-DOWN-A-SAVING-TOO",
	// ...and the rows that hold the OTHER side to `render`'s "round once, at the places you print"
	// rule. A TypeScript pre-round hardcoded to two places double-rounds 12.496 up to 13 in every
	// zero-decimal register, against Go's 12.
	"monthlyDelta/estimate/DOUBLE-ROUNDING-12.496-IS-NOT-A-HALF",
	"monthlyDelta/exact/DOUBLE-ROUNDING-12.496-IS-NOT-A-HALF-AT-JPY",
	// MonthlyRate clamps a negative, and that is a REFUSAL rather than a gap now that MonthlyDelta
	// exists. These two rows are the only statement that the clamp is deliberate; without them a
	// later reader "fixes" it and every absolute call site starts rendering signed money.
	"monthlyRate/estimate/negative-REFUSED-see-monthlyDelta",
	"monthlyRate/exact/negative-REFUSED-see-monthlyDelta",
}

// tableProblems IS the guard. Both the check above and the mutation test that proves it works call
// this one function.
//
// That is not a stylistic preference. The first cut of this pattern elsewhere in the repo
// re-implemented the maps and the loops inline in the mutation test, so it verified a COPY of the
// guard and would have passed against a revert to the inert count-threshold form. A test that
// re-implements what it is testing tests nothing about the thing.
//
// Returns one message per unsatisfied requirement; empty means the table still carries what this
// mirror exists to lock.
func tableProblems(tbl tableFile) []string {
	var problems []string

	if len(tbl.Cases) == 0 {
		return []string{fmt.Sprintf("%s parsed to zero sections — every assertion below is unreachable and this test would pass vacuously.\n%s", tableRel, regenerate)}
	}

	// Every section must be driven or declared excluded. A section with neither is a silent gap —
	// the TypeScript generator already refuses one, and Go refusing it too is what keeps the two
	// halves the same shape.
	for section, rows := range tbl.Cases {
		if len(rows) == 0 {
			problems = append(problems, fmt.Sprintf("section %q carries zero rows — 'ran nothing' must not read as 'nothing wrong'", section))
		}
		if _, driven := drivers[section]; !driven {
			problems = append(problems, fmt.Sprintf(
				"section %q has no Go driver. Either implement it and add a line to `drivers`, or — if Go "+
					"deliberately does not mirror it — the TypeScript side must move it to `excluded` with a "+
					"stated reason. A section Go quietly skips is the gap this file exists to close.", section))
		}
	}
	for section := range drivers {
		if _, present := tbl.Cases[section]; !present {
			problems = append(problems, fmt.Sprintf(
				"Go drives section %q but the table has no such section — the driver asserts nothing", section))
		}
	}

	// The one declared exclusion, asserted rather than assumed. If TypeScript ever ports Relative,
	// this fires and Go is told to mirror it instead of silently continuing not to.
	if _, ok := tbl.Excluded["formatRelative"]; !ok {
		problems = append(problems, "the table no longer excludes formatRelative — Go must either mirror it or the exclusion must be restored with its reason")
	}
	for name, reason := range tbl.Excluded {
		if len(strings.TrimSpace(reason)) < 40 {
			problems = append(problems, fmt.Sprintf("exclusion %q has no real reason (%q) — an absence with a stated reason is reviewable, %q is not", name, reason, "n/a"))
		}
	}

	// Named rows, present AND still carrying their recorded answer. Presence alone is not enough: a
	// row retained but regenerated to a different expectation proves nothing about the boundary it
	// was written for.
	seen := map[string]bool{}
	for _, rows := range tbl.Cases {
		for _, row := range rows {
			if id, ok := row["id"].(string); ok {
				if want, ok := row["want"].(string); ok && want != "" {
					seen[id] = true
				}
			}
		}
	}
	for _, id := range requiredIDs {
		if !seen[id] {
			problems = append(problems, fmt.Sprintf(
				"row %q is missing from the table, or no longer carries an expectation — it is one of the "+
					"rows this mirror exists to lock. If it is genuinely obsolete, delete it from requiredIDs "+
					"in the same commit and say why in the PR.", id))
		}
	}
	return problems
}

// The guard is only worth having if it FAILS on the mutations it describes, so this drives them
// through tableProblems itself rather than asserting them in a comment.
func TestTableGuardFailsOnEachMutation(t *testing.T) {
	base := loadTable(t)
	if got := tableProblems(base); len(got) != 0 {
		t.Fatalf("the unmutated table already fails the guard, so this test cannot prove anything: %v", got)
	}

	t.Run("a removed required row is detected", func(t *testing.T) {
		victim := requiredIDs[0]
		mutated := cloneWithout(base, victim)
		problems := tableProblems(mutated)
		if len(problems) != 1 {
			t.Fatalf("removing %q should leave exactly 1 problem, got %d: %v", victim, len(problems), problems)
		}
		if !strings.Contains(problems[0], victim) {
			t.Errorf("the guard fired but did not name the row that was removed: %q", problems[0])
		}
	})

	t.Run("an undriven section is detected", func(t *testing.T) {
		mutated := clone(base)
		mutated.Cases["percent"] = []map[string]any{{"id": "percent/x", "want": "1%"}}
		problems := tableProblems(mutated)
		if len(problems) != 1 || !strings.Contains(problems[0], "percent") {
			t.Fatalf("a new section with no Go driver must be reported, got %v", problems)
		}
	})

	t.Run("a dropped exclusion is detected", func(t *testing.T) {
		mutated := clone(base)
		delete(mutated.Excluded, "formatRelative")
		problems := tableProblems(mutated)
		if len(problems) != 1 || !strings.Contains(problems[0], "formatRelative") {
			t.Fatalf("dropping the declared exclusion must be reported, got %v", problems)
		}
	})

	t.Run("an empty table is detected", func(t *testing.T) {
		problems := tableProblems(tableFile{Cases: map[string][]map[string]any{}})
		if len(problems) != 1 || !strings.Contains(problems[0], "vacuously") {
			t.Fatalf("a table with no sections must be reported as vacuous, got %v", problems)
		}
	})
}

func clone(in tableFile) tableFile {
	out := tableFile{Version: in.Version, Excluded: map[string]string{}, Cases: map[string][]map[string]any{}}
	for k, v := range in.Excluded {
		out.Excluded[k] = v
	}
	for section, rows := range in.Cases {
		out.Cases[section] = append([]map[string]any(nil), rows...)
	}
	return out
}

func cloneWithout(in tableFile, id string) tableFile {
	out := clone(in)
	for section, rows := range out.Cases {
		kept := make([]map[string]any, 0, len(rows))
		for _, r := range rows {
			if r["id"] != id {
				kept = append(kept, r)
			}
		}
		out.Cases[section] = kept
	}
	return out
}
