// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by apps/console/scripts/gen-go-enums.ts; DO NOT EDIT.
// Regenerate with: pnpm -F console gen:go-enums
//
// These mirror the drizzle enum SSOT (apps/console/lib/db/schema/enums.ts). Reference
// the constants (not bare strings) in Go so a removed enum value fails to compile and a
// new one is caught by the exhaustive linter + coverage tests.

package types

// JobType mirrors the provision_job_type enum (lib/db/schema/enums.ts).
type JobType string

const (
	JobTypeDestroyRunner JobType = "DESTROY_RUNNER"
	JobTypeDeploy        JobType = "DEPLOY"
	JobTypeDestroy       JobType = "DESTROY"
	JobTypePlan          JobType = "PLAN"
	JobTypeDeployRunner  JobType = "DEPLOY_RUNNER"
	JobTypeUpdateRunner  JobType = "UPDATE_RUNNER"
	JobTypeAnalyzeRepo   JobType = "ANALYZE_REPO"
	JobTypeDetectDrift   JobType = "DETECT_DRIFT"
	JobTypeAudit         JobType = "AUDIT"
	JobTypeChartScan     JobType = "CHART_SCAN"
	JobTypeIacScan       JobType = "IAC_SCAN"
	JobTypeStateSurgery  JobType = "STATE_SURGERY"
	JobTypeProbeCluster  JobType = "PROBE_CLUSTER"
)

// AllJobTypes is every provision_job_type value, in schema order.
var AllJobTypes = []JobType{
	JobTypeDestroyRunner,
	JobTypeDeploy,
	JobTypeDestroy,
	JobTypePlan,
	JobTypeDeployRunner,
	JobTypeUpdateRunner,
	JobTypeAnalyzeRepo,
	JobTypeDetectDrift,
	JobTypeAudit,
	JobTypeChartScan,
	JobTypeIacScan,
	JobTypeStateSurgery,
	JobTypeProbeCluster,
}

// JobStatus mirrors the provision_job_status enum (lib/db/schema/enums.ts).
type JobStatus string

const (
	JobStatusQueued     JobStatus = "QUEUED"
	JobStatusClaimed    JobStatus = "CLAIMED"
	JobStatusProcessing JobStatus = "PROCESSING"
	JobStatusSuccess    JobStatus = "SUCCESS"
	JobStatusFailed     JobStatus = "FAILED"
	JobStatusCancelled  JobStatus = "CANCELLED"
)

// AllJobStatuses is every provision_job_status value, in schema order.
var AllJobStatuses = []JobStatus{
	JobStatusQueued,
	JobStatusClaimed,
	JobStatusProcessing,
	JobStatusSuccess,
	JobStatusFailed,
	JobStatusCancelled,
}

// CloudProvider mirrors the cloud_provider enum (lib/db/schema/enums.ts).
type CloudProvider string

const (
	CloudProviderAws          CloudProvider = "aws"
	CloudProviderAzure        CloudProvider = "azure"
	CloudProviderGcp          CloudProvider = "gcp"
	CloudProviderAlibaba      CloudProvider = "alibaba"
	CloudProviderDigitalocean CloudProvider = "digitalocean"
	CloudProviderHetzner      CloudProvider = "hetzner"
	CloudProviderCivo         CloudProvider = "civo"
)

// AllCloudProviders is every cloud_provider value, in schema order.
var AllCloudProviders = []CloudProvider{
	CloudProviderAws,
	CloudProviderAzure,
	CloudProviderGcp,
	CloudProviderAlibaba,
	CloudProviderDigitalocean,
	CloudProviderHetzner,
	CloudProviderCivo,
}
